import Mathlib.Util.AssertNoSorry
import Lean4Tutorial.i002_replicate_MP_v2.MP1994V2.All

/-!
# MP1994 v2 audit through Milestone M10.1

This module checks the public foundation interfaces without adding substantive
economic theorems.
-/

#check MP1994V2.Primitives
#check MP1994V2.CoreEconomicAssumptions
#check MP1994V2.ShockAssumptions
#check MP1994V2.ShockNormalizationAssumptions
#check MP1994V2.MatchingAssumptions
#check MP1994V2.Primitives.cdf
#check MP1994V2.Primitives.IsShockUpperBound
#check MP1994V2.MarketTightness
#check MP1994V2.Primitives.vacancyMeetingRate
#check MP1994V2.Primitives.workerMeetingRate
#check MP1994V2.surplus
#check MP1994V2.activeSurplus
#check MP1994V2.continuationTerm
#check MP1994V2.ValueCandidate
#check MP1994V2.ValueEquilibrium
#check MP1994V2.continuationTerm_eq_integral_activeSurplus_sub
#check MP1994V2.ValueEquilibrium.firm_share
#check MP1994V2.ValueEquilibrium.surplus_flow_equation
#check MP1994V2.ValueEquilibrium.surplus_bellman_of_probability
#check MP1994V2.ValueEquilibrium.surplus_bellman
#check MP1994V2.CoreEconomicAssumptions.r_add_lambda_pos
#check MP1994V2.CoreEconomicAssumptions.r_add_lambda_ne
#check MP1994V2.CoreEconomicAssumptions.sigma_ne
#check MP1994V2.CoreEconomicAssumptions.surplus_slope_pos
#check MP1994V2.CoreEconomicAssumptions.one_sub_beta_pos
#check MP1994V2.ValueEquilibrium.surplus_difference_scaled_of_probability
#check MP1994V2.ValueEquilibrium.surplus_difference_scaled
#check MP1994V2.ValueEquilibrium.surplus_difference
#check MP1994V2.ValueEquilibrium.surplus_difference_of_shockAssumptions
#check MP1994V2.ValueEquilibrium.surplus_strictMono
#check MP1994V2.ValueEquilibrium.surplus_strictMono_of_shockAssumptions
#check MP1994V2.ValueEquilibrium.reservationCutoff
#check MP1994V2.ValueEquilibrium.surplus_reservationCutoff_eq_zero
#check MP1994V2.ValueEquilibrium.surplus_reservationCutoff_eq_zero_of_shockAssumptions
#check MP1994V2.ValueEquilibrium.surplus_eq_zero_iff
#check MP1994V2.ValueEquilibrium.existsUnique_surplus_zero
#check MP1994V2.ValueEquilibrium.existsUnique_surplus_zero_of_shockAssumptions
#check MP1994V2.ValueEquilibrium.vacancy_value_eq_zero
#check MP1994V2.ValueEquilibrium.vacancy_meeting_mul_upper_firm_value_eq_cost
#check MP1994V2.ValueEquilibrium.upper_firm_value_pos
#check MP1994V2.ValueEquilibrium.upper_surplus_pos
#check MP1994V2.ValueEquilibrium.reservationCutoff_lt_epsUpper
#check MP1994V2.ValueEquilibrium.reservationCutoff_is_admissible
#check MP1994V2.ValueEquilibrium.equation12
#check MP1994V2.ValueEquilibrium.equation12_of_shockAssumptions
#check MP1994V2.ValueEquilibrium.surplus_eq_slope_mul_sub_cutoff
#check MP1994V2.ValueEquilibrium.surplus_eq_slope_mul_sub_cutoff_of_shockAssumptions
#check MP1994V2.ValueEquilibrium.surplus_neg_iff_lt_reservationCutoff
#check MP1994V2.ValueEquilibrium.surplus_pos_iff_reservationCutoff_lt
#check MP1994V2.ValueEquilibrium.surplus_nonneg_iff_reservationCutoff_le
#check MP1994V2.ValueEquilibrium.firm_value_neg_iff_lt_reservationCutoff
#check MP1994V2.ValueEquilibrium.firm_value_eq_zero_iff
#check MP1994V2.ValueEquilibrium.firm_value_nonneg_iff_reservationCutoff_le
#check MP1994V2.ValueEquilibrium.activeSurplus_eq_slope_mul_positivePart
#check MP1994V2.ValueEquilibrium.milestone2_capstone
#check MP1994V2.Primitives.expectedExcess
#check MP1994V2.Primitives.tailProbability
#check MP1994V2.Primitives.tailOptionValue
#check MP1994V2.Primitives.measureReal_Ioi_eq_one_sub_cdf
#check MP1994V2.Primitives.expectedExcess_nonneg
#check MP1994V2.positivePart_nonneg
#check MP1994V2.measurable_positivePart_sub
#check MP1994V2.ValueEquilibrium.positivePart_sub_cutoff_integrable
#check MP1994V2.ValueEquilibrium.expectedExcess_cutoff_eq_tailOptionValue
#check MP1994V2.ValueEquilibrium.integral_activeSurplus_eq_slope_mul_expectedExcess
#check MP1994V2.ValueEquilibrium.integral_activeSurplus_eq_slope_mul_tailOptionValue
#check MP1994V2.ValueEquilibrium.equation9_measure
#check MP1994V2.ValueEquilibrium.equation9
#check MP1994V2.Primitives.jobDestructionResidualMeasure
#check MP1994V2.Primitives.jobDestructionResidual
#check MP1994V2.Primitives.SatisfiesJobDestructionMeasure
#check MP1994V2.Primitives.SatisfiesJobDestruction
#check MP1994V2.ValueEquilibrium.search_gain_eq
#check MP1994V2.ValueEquilibrium.equation10_measure
#check MP1994V2.ValueEquilibrium.equation10
#check MP1994V2.ValueEquilibrium.satisfiesJobDestructionMeasure
#check MP1994V2.ValueEquilibrium.satisfiesJobDestruction
#check MP1994V2.Primitives.jobCreationResidual
#check MP1994V2.Primitives.SatisfiesJobCreation
#check MP1994V2.ValueEquilibrium.job_creation_product_identity
#check MP1994V2.Primitives.withCommonProductivity
#check MP1994V2.Primitives.withUnemploymentIncome
#check MP1994V2.Primitives.withShockArrivalRate
#check MP1994V2.Primitives.withDiscountRate
#check MP1994V2.CoreEconomicAssumptions.withCommonProductivity
#check MP1994V2.CoreEconomicAssumptions.withUnemploymentIncome
#check MP1994V2.CoreEconomicAssumptions.withShockArrivalRate
#check MP1994V2.CoreEconomicAssumptions.withDiscountRate
#check MP1994V2.ShockAssumptions.withCommonProductivity
#check MP1994V2.ShockAssumptions.withUnemploymentIncome
#check MP1994V2.ShockAssumptions.withShockArrivalRate
#check MP1994V2.ShockAssumptions.withDiscountRate
#check MP1994V2.MatchingAssumptions.withCommonProductivity
#check MP1994V2.MatchingAssumptions.withUnemploymentIncome
#check MP1994V2.MatchingAssumptions.withShockArrivalRate
#check MP1994V2.MatchingAssumptions.withDiscountRate
#check MP1994V2.shockArrivalFraction_monotone
#check MP1994V2.discountFraction_antitone
#check MP1994V2.cutoff_strictAnti_commonProductivity_at_fixed_theta
#check MP1994V2.cutoff_strictMono_unemploymentIncome_at_fixed_theta
#check MP1994V2.cutoff_antitone_shockArrival_at_fixed_theta
#check MP1994V2.cutoff_monotone_discountRate_at_fixed_theta
#check MP1994V2.cutoff_strictAnti_shockArrival_at_fixed_theta_of_expectedExcess_pos
#check MP1994V2.cutoff_strictMono_discountRate_at_fixed_theta_of_optionValue_pos
#check MP1994V2.jobCreation_curve_antitone
#check MP1994V2.ReducedEquilibrium.order_of_commonProductivity
#check MP1994V2.ReducedEquilibrium.order_of_unemploymentIncome
#check MP1994V2.ReducedEquilibrium.cutoff_strictAnti_shockArrival
#check MP1994V2.ReducedEquilibrium.theta_strictAnti_discountRate
#check MP1994V2.Primitives.strictShockBelow_mono
#check MP1994V2.Primitives.jobSeparationRate_mono_cutoff
#check MP1994V2.Primitives.jobFindingRate_mono
#check MP1994V2.Primitives.jobCreationFlow_mono_of_findingRate
#check MP1994V2.Primitives.jobDestructionFlow_mono_of_separationRate
#check MP1994V2.steadyUnemployment_monotone
#check MP1994V2.SteadyStateEquilibrium.aggregateProductivity_initialFlows
#check MP1994V2.SteadyStateEquilibrium.aggregateProductivity_capstone
#check MP1994V2.SteadyStateEquilibrium.unemploymentIncome_initialFlows
#check MP1994V2.SteadyStateEquilibrium.unemploymentIncome_capstone
#check MP1994V2.m7_aggregateNetProductivity_capstone
#check MP1994V2.m7_otherParameters_capstone
#check MP1994V2.ValueEquilibrium.equation13
#check MP1994V2.ValueEquilibrium.satisfiesJobCreation
#check MP1994V2.ValueEquilibrium.milestone3_capstone
#check MP1994V2.Primitives.SatisfiesJobCreationProduct
#check MP1994V2.ReducedEquilibrium
#check MP1994V2.ReducedEquilibrium.cutoff_le_epsUpper
#check MP1994V2.ReducedEquilibrium.epsUpper_sub_cutoff_pos
#check MP1994V2.ReducedEquilibrium.epsUpper_sub_cutoff_ne
#check MP1994V2.ReducedEquilibrium.ext
#check MP1994V2.Primitives.positivePart_sub_integrable
#check MP1994V2.Primitives.expectedExcess_eq_tailOptionValue
#check MP1994V2.ReducedEquilibrium.expectedExcess_eq_tailOptionValue
#check MP1994V2.ReducedEquilibrium.equation10_measure
#check MP1994V2.ReducedEquilibrium.equation10
#check MP1994V2.ReducedEquilibrium.equation13
#check MP1994V2.ReducedEquilibrium.satisfiesJobDestruction
#check MP1994V2.ReducedEquilibrium.satisfiesJobCreation
#check MP1994V2.ValueEquilibrium.satisfiesJobCreationProduct
#check MP1994V2.ValueEquilibrium.toReducedEquilibrium
#check MP1994V2.ValueEquilibrium.toReducedEquilibrium_theta
#check MP1994V2.ValueEquilibrium.toReducedEquilibrium_cutoff
#check MP1994V2.ValueEquilibrium.toReducedEquilibrium_satisfies_paper_conditions
#check MP1994V2.ReducedEquilibrium.surplusCandidate
#check MP1994V2.ReducedEquilibrium.vacancyValueCandidate
#check MP1994V2.ReducedEquilibrium.firmValueCandidate
#check MP1994V2.ReducedEquilibrium.unemploymentValueCandidate
#check MP1994V2.ReducedEquilibrium.workerValueCandidate
#check MP1994V2.ReducedEquilibrium.wageCandidate
#check MP1994V2.ReducedEquilibrium.toValueCandidate
#check MP1994V2.ReducedEquilibrium.toValueCandidate_theta
#check MP1994V2.ReducedEquilibrium.toValueCandidate_surplus
#check MP1994V2.ReducedEquilibrium.toValueCandidate_activeSurplus
#check MP1994V2.ReducedEquilibrium.activeSurplus_integrable
#check MP1994V2.ReducedEquilibrium.search_gain_eq
#check MP1994V2.ReducedEquilibrium.vacancy_meeting_mul_firm_value_eq_cost
#check MP1994V2.ReducedEquilibrium.wage_search_term_eq
#check MP1994V2.ReducedEquilibrium.integral_activeSurplus_eq
#check MP1994V2.ReducedEquilibrium.surplus_bellman
#check MP1994V2.ReducedEquilibrium.continuation_eq
#check MP1994V2.ReducedEquilibrium.vacancy_bellman
#check MP1994V2.ReducedEquilibrium.free_entry
#check MP1994V2.ReducedEquilibrium.nash_sharing
#check MP1994V2.ReducedEquilibrium.unemployed_bellman
#check MP1994V2.ReducedEquilibrium.worker_bellman
#check MP1994V2.ReducedEquilibrium.filled_job_bellman
#check MP1994V2.ReducedEquilibrium.toValueEquilibrium
#check MP1994V2.ReducedEquilibrium.toValueEquilibrium_theta
#check MP1994V2.ReducedEquilibrium.toValueEquilibrium_surplus
#check MP1994V2.ReducedEquilibrium.toValueEquilibrium_reservationCutoff
#check MP1994V2.ReducedEquilibrium.toValue_toReduced
#check MP1994V2.ValueEquilibrium.wage_eq_nash_formula
#check MP1994V2.ValueEquilibrium.reconstructed_surplus_eq
#check MP1994V2.ValueEquilibrium.reconstruction_components
#check MP1994V2.ValueEquilibrium.reconstruction_economic_roundtrip
#check MP1994V2.valueEquilibrium_nonempty_iff_reducedEquilibrium_nonempty
#check MP1994V2.exists_valueEquilibrium_iff_exists_reducedEquilibrium
#check MP1994V2.m4_representation_capstone
#check MP1994V2.Primitives.positivePart_sub_antitone
#check MP1994V2.Primitives.positivePart_sub_dist_le
#check MP1994V2.Primitives.expectedExcess_antitone
#check MP1994V2.Primitives.expectedExcess_lipschitz
#check MP1994V2.Primitives.expectedExcess_continuous
#check MP1994V2.Primitives.searchOpportunityCostCoefficient
#check MP1994V2.Primitives.jobCreationScale
#check MP1994V2.Primitives.jobDestructionNet
#check MP1994V2.Primitives.jobDestructionTheta
#check MP1994V2.Primitives.satisfiesJobDestructionMeasure_iff
#check MP1994V2.Primitives.jobDestructionNet_strictMono
#check MP1994V2.Primitives.jobDestructionTheta_strictMono
#check MP1994V2.Primitives.jobDestructionTheta_continuous
#check MP1994V2.Primitives.staticCrossingResidual
#check MP1994V2.Primitives.IsAdmissibleStaticCutoff
#check MP1994V2.Primitives.staticCrossingResidual_epsUpper
#check MP1994V2.Primitives.staticCrossingResidual_strictAntiOn
#check MP1994V2.jobDestruction_curve_strictMono
#check MP1994V2.jobCreation_curve_strictAnti
#check MP1994V2.ReducedEquilibrium.unique
#check MP1994V2.reducedEquilibrium_atMostOne
#check MP1994V2.StaticExistenceAssumptions
#check MP1994V2.Primitives.staticCrossingResidual_continuousOn_Icc
#check MP1994V2.exists_staticCrossing
#check MP1994V2.reducedEquilibrium_nonempty
#check MP1994V2.staticReducedEquilibrium
#check MP1994V2.HasUniqueReducedEquilibrium
#check MP1994V2.reducedEquilibrium_existsUnique
#check MP1994V2.ReducedEquilibrium.theta_eq
#check MP1994V2.ReducedEquilibrium.cutoff_eq
#check MP1994V2.valueEquilibrium_nonempty
#check MP1994V2.ValueEquilibrium.theta_eq
#check MP1994V2.ValueEquilibrium.reservationCutoff_eq
#check MP1994V2.ValueEquilibrium.EconomicallyEquivalent
#check MP1994V2.ValueEquilibrium.economically_unique
#check MP1994V2.valueEquilibrium_exists_economicallyUnique
#check MP1994V2.m5_static_equilibrium_capstone
#check MP1994V2.Primitives.strictShockBelow
#check MP1994V2.Primitives.strictShockBelow_eq_cdf
#check MP1994V2.Primitives.strictShockBelow_nonneg
#check MP1994V2.Primitives.jobSeparationRate
#check MP1994V2.Primitives.jobSeparationRate_eq_lambda_mul_cdf
#check MP1994V2.Primitives.jobFindingRate
#check MP1994V2.Primitives.employmentFromUnemployment
#check MP1994V2.Primitives.vacanciesFromTightness
#check MP1994V2.Primitives.jobDestructionFlow
#check MP1994V2.Primitives.jobCreationFlow
#check MP1994V2.Primitives.unemploymentFlowResidual
#check MP1994V2.Primitives.HasPositiveSeparationAt
#check MP1994V2.Primitives.jobSeparationRate_nonneg
#check MP1994V2.Primitives.jobFindingRate_pos
#check MP1994V2.Primitives.totalTransitionHazard_pos
#check MP1994V2.Primitives.jobDestructionFlow_nonneg
#check MP1994V2.Primitives.jobCreationFlow_nonneg
#check MP1994V2.Primitives.jobDestructionFlow_eq_lambda_cdf_mul_employment
#check MP1994V2.Primitives.hasPositiveSeparationAt_of_lambda_cdf_pos
#check MP1994V2.Primitives.steadyStateUnemployment
#check MP1994V2.Primitives.steadyStateUnemployment_nonneg
#check MP1994V2.Primitives.steadyStateUnemployment_lt_one
#check MP1994V2.Primitives.steadyStateUnemployment_flow_balance
#check MP1994V2.Primitives.flow_balance_iff_unemployment_eq
#check MP1994V2.Primitives.steadyStateUnemployment_eq_equation14
#check MP1994V2.SteadyStateEquilibrium
#check MP1994V2.SteadyStateEquilibrium.employment
#check MP1994V2.SteadyStateEquilibrium.vacancies
#check MP1994V2.SteadyStateEquilibrium.ext
#check MP1994V2.ReducedEquilibrium.toSteadyStateEquilibrium
#check MP1994V2.ReducedEquilibrium.toSteadyStateEquilibrium_theta
#check MP1994V2.ReducedEquilibrium.toSteadyStateEquilibrium_cutoff
#check MP1994V2.ReducedEquilibrium.toSteadyStateEquilibrium_unemployment
#check MP1994V2.SteadyStateEquilibrium.unemployment_eq_closedForm
#check MP1994V2.SteadyStateEquilibrium.equation14
#check MP1994V2.SteadyStateEquilibrium.employment_nonneg
#check MP1994V2.SteadyStateEquilibrium.employment_le_one
#check MP1994V2.SteadyStateEquilibrium.employment_pos
#check MP1994V2.SteadyStateEquilibrium.vacancies_nonneg
#check MP1994V2.SteadyStateEquilibrium.jobCreationFlow_eq_q_mul_vacancies
#check MP1994V2.SteadyStateEquilibrium.jobDestructionFlow_eq_lambda_cdf_mul_employment
#check MP1994V2.SteadyStateEquilibrium.jobCreation_eq_jobDestruction
#check MP1994V2.SteadyStateEquilibrium.unemployment_pos_of_positiveSeparation
#check MP1994V2.SteadyStateEquilibrium.unemployment_mem_Ioo_of_positiveSeparation
#check MP1994V2.SteadyStateEquilibrium.vacancies_pos_of_positiveSeparation
#check MP1994V2.SteadyStateEquilibrium.vacancies_div_unemployment_eq_theta
#check MP1994V2.SteadyStateEquilibrium.unemployment_eq_zero_of_separation_eq_zero
#check MP1994V2.SteadyStateEquilibrium.vacancies_eq_zero_of_separation_eq_zero
#check MP1994V2.ReducedEquilibrium.toSteady_toReduced
#check MP1994V2.SteadyStateEquilibrium.toReduced_toSteady
#check MP1994V2.steadyStateEquivReduced
#check MP1994V2.SteadyStateEquilibrium.toValueEquilibrium
#check MP1994V2.SteadyStateEquilibrium.toValueEquilibrium_theta
#check MP1994V2.SteadyStateEquilibrium.toValueEquilibrium_reservationCutoff
#check MP1994V2.SteadyStateEquilibrium.unique
#check MP1994V2.steadyStateEquilibrium_atMostOne
#check MP1994V2.steadyStateEquilibrium_nonempty
#check MP1994V2.steadyStateEquilibrium_nonempty_iff_reducedEquilibrium_nonempty
#check MP1994V2.HasUniqueSteadyStateEquilibrium
#check MP1994V2.steadyStateEquilibrium_existsUnique
#check MP1994V2.m6_stock_completion_capstone
#check MP1994V2.m6_conditional_existence_capstone
#check MP1994V2.m6_full_steady_state_capstone

-- Existence-only interfaces deliberately require no matching bundle.
example {P : MP1994V2.Primitives}
    (A : MP1994V2.CoreEconomicAssumptions P)
    (D : MP1994V2.ShockAssumptions P)
    (X : MP1994V2.StaticExistenceAssumptions P) :
    Nonempty (MP1994V2.ReducedEquilibrium P) :=
  MP1994V2.reducedEquilibrium_nonempty A D X

example {P : MP1994V2.Primitives}
    (A : MP1994V2.CoreEconomicAssumptions P)
    (D : MP1994V2.ShockAssumptions P)
    (X : MP1994V2.StaticExistenceAssumptions P) :
    Nonempty (MP1994V2.ValueEquilibrium P) :=
  MP1994V2.valueEquilibrium_nonempty A D X

assert_no_sorry MP1994V2.Primitives.workerMeetingRate_pos
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_eq
assert_no_sorry MP1994V2.continuationTerm_eq_integral_activeSurplus_sub
assert_no_sorry MP1994V2.ValueEquilibrium.firm_share
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_flow_equation
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_bellman_of_probability
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_bellman
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_difference_scaled_of_probability
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_difference
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_strictMono
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_reservationCutoff_eq_zero
assert_no_sorry MP1994V2.ValueEquilibrium.existsUnique_surplus_zero
assert_no_sorry MP1994V2.ValueEquilibrium.vacancy_value_eq_zero
assert_no_sorry MP1994V2.ValueEquilibrium.upper_firm_value_pos
assert_no_sorry MP1994V2.ValueEquilibrium.upper_surplus_pos
assert_no_sorry MP1994V2.ValueEquilibrium.reservationCutoff_lt_epsUpper
assert_no_sorry MP1994V2.ValueEquilibrium.equation12
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_neg_iff_lt_reservationCutoff
assert_no_sorry MP1994V2.ValueEquilibrium.firm_value_neg_iff_lt_reservationCutoff
assert_no_sorry MP1994V2.ValueEquilibrium.activeSurplus_eq_slope_mul_positivePart
assert_no_sorry MP1994V2.ValueEquilibrium.milestone2_capstone
assert_no_sorry MP1994V2.ValueEquilibrium.positivePart_sub_cutoff_integrable
assert_no_sorry MP1994V2.Primitives.measureReal_Ioi_eq_one_sub_cdf
assert_no_sorry MP1994V2.ValueEquilibrium.expectedExcess_cutoff_eq_tailOptionValue
assert_no_sorry MP1994V2.ValueEquilibrium.integral_activeSurplus_eq_slope_mul_expectedExcess
assert_no_sorry MP1994V2.ValueEquilibrium.equation9_measure
assert_no_sorry MP1994V2.ValueEquilibrium.equation9
assert_no_sorry MP1994V2.ValueEquilibrium.search_gain_eq
assert_no_sorry MP1994V2.ValueEquilibrium.equation10_measure
assert_no_sorry MP1994V2.ValueEquilibrium.equation10
assert_no_sorry MP1994V2.ValueEquilibrium.satisfiesJobDestruction
assert_no_sorry MP1994V2.ValueEquilibrium.job_creation_product_identity
assert_no_sorry MP1994V2.ValueEquilibrium.equation13
assert_no_sorry MP1994V2.ValueEquilibrium.satisfiesJobCreation
assert_no_sorry MP1994V2.ValueEquilibrium.milestone3_capstone
assert_no_sorry MP1994V2.Primitives.positivePart_sub_integrable
assert_no_sorry MP1994V2.Primitives.expectedExcess_eq_tailOptionValue
assert_no_sorry MP1994V2.ReducedEquilibrium.equation10
assert_no_sorry MP1994V2.ReducedEquilibrium.equation13
assert_no_sorry MP1994V2.ValueEquilibrium.toReducedEquilibrium
assert_no_sorry MP1994V2.ReducedEquilibrium.toValueCandidate_surplus
assert_no_sorry MP1994V2.ReducedEquilibrium.activeSurplus_integrable
assert_no_sorry MP1994V2.ReducedEquilibrium.search_gain_eq
assert_no_sorry MP1994V2.ReducedEquilibrium.surplus_bellman
assert_no_sorry MP1994V2.ReducedEquilibrium.vacancy_bellman
assert_no_sorry MP1994V2.ReducedEquilibrium.filled_job_bellman
assert_no_sorry MP1994V2.ReducedEquilibrium.worker_bellman
assert_no_sorry MP1994V2.ReducedEquilibrium.unemployed_bellman
assert_no_sorry MP1994V2.ReducedEquilibrium.toValueEquilibrium
assert_no_sorry MP1994V2.ReducedEquilibrium.toValueEquilibrium_reservationCutoff
assert_no_sorry MP1994V2.ReducedEquilibrium.toValue_toReduced
assert_no_sorry MP1994V2.ValueEquilibrium.wage_eq_nash_formula
assert_no_sorry MP1994V2.ValueEquilibrium.reconstruction_components
assert_no_sorry MP1994V2.ValueEquilibrium.reconstruction_economic_roundtrip
assert_no_sorry MP1994V2.valueEquilibrium_nonempty_iff_reducedEquilibrium_nonempty
assert_no_sorry MP1994V2.m4_representation_capstone
assert_no_sorry MP1994V2.Primitives.expectedExcess_antitone
assert_no_sorry MP1994V2.Primitives.expectedExcess_lipschitz
assert_no_sorry MP1994V2.Primitives.expectedExcess_continuous
assert_no_sorry MP1994V2.Primitives.satisfiesJobDestructionMeasure_iff
assert_no_sorry MP1994V2.Primitives.jobDestructionNet_strictMono
assert_no_sorry MP1994V2.Primitives.jobDestructionTheta_strictMono
assert_no_sorry MP1994V2.Primitives.staticCrossingResidual_strictAntiOn
assert_no_sorry MP1994V2.jobDestruction_curve_strictMono
assert_no_sorry MP1994V2.jobCreation_curve_strictAnti
assert_no_sorry MP1994V2.ReducedEquilibrium.unique
assert_no_sorry MP1994V2.exists_staticCrossing
assert_no_sorry MP1994V2.reducedEquilibrium_nonempty
assert_no_sorry MP1994V2.reducedEquilibrium_existsUnique
assert_no_sorry MP1994V2.valueEquilibrium_nonempty
assert_no_sorry MP1994V2.ValueEquilibrium.theta_eq
assert_no_sorry MP1994V2.ValueEquilibrium.reservationCutoff_eq
assert_no_sorry MP1994V2.ValueEquilibrium.economically_unique
assert_no_sorry MP1994V2.m5_static_equilibrium_capstone
assert_no_sorry MP1994V2.Primitives.strictShockBelow_eq_cdf
assert_no_sorry MP1994V2.Primitives.jobSeparationRate_eq_lambda_mul_cdf
assert_no_sorry MP1994V2.Primitives.totalTransitionHazard_pos
assert_no_sorry MP1994V2.Primitives.steadyStateUnemployment_nonneg
assert_no_sorry MP1994V2.Primitives.steadyStateUnemployment_lt_one
assert_no_sorry MP1994V2.Primitives.steadyStateUnemployment_flow_balance
assert_no_sorry MP1994V2.Primitives.flow_balance_iff_unemployment_eq
assert_no_sorry MP1994V2.Primitives.steadyStateUnemployment_eq_equation14
assert_no_sorry MP1994V2.ReducedEquilibrium.toSteadyStateEquilibrium
assert_no_sorry MP1994V2.SteadyStateEquilibrium.equation14
assert_no_sorry MP1994V2.SteadyStateEquilibrium.jobCreationFlow_eq_q_mul_vacancies
assert_no_sorry MP1994V2.SteadyStateEquilibrium.jobDestructionFlow_eq_lambda_cdf_mul_employment
assert_no_sorry MP1994V2.SteadyStateEquilibrium.jobCreation_eq_jobDestruction
assert_no_sorry MP1994V2.SteadyStateEquilibrium.unemployment_pos_of_positiveSeparation
assert_no_sorry MP1994V2.SteadyStateEquilibrium.vacancies_div_unemployment_eq_theta
assert_no_sorry MP1994V2.ReducedEquilibrium.toSteady_toReduced
assert_no_sorry MP1994V2.SteadyStateEquilibrium.toReduced_toSteady
assert_no_sorry MP1994V2.SteadyStateEquilibrium.unique
assert_no_sorry MP1994V2.steadyStateEquilibrium_nonempty
assert_no_sorry MP1994V2.steadyStateEquilibrium_existsUnique
assert_no_sorry MP1994V2.m6_stock_completion_capstone
assert_no_sorry MP1994V2.m6_conditional_existence_capstone
assert_no_sorry MP1994V2.m6_full_steady_state_capstone
assert_no_sorry MP1994V2.cutoff_strictAnti_commonProductivity_at_fixed_theta
assert_no_sorry MP1994V2.cutoff_strictMono_unemploymentIncome_at_fixed_theta
assert_no_sorry MP1994V2.cutoff_antitone_shockArrival_at_fixed_theta
assert_no_sorry MP1994V2.cutoff_monotone_discountRate_at_fixed_theta
assert_no_sorry MP1994V2.cutoff_strictAnti_shockArrival_at_fixed_theta_of_expectedExcess_pos
assert_no_sorry MP1994V2.cutoff_strictMono_discountRate_at_fixed_theta_of_optionValue_pos
assert_no_sorry MP1994V2.ReducedEquilibrium.order_of_commonProductivity
assert_no_sorry MP1994V2.ReducedEquilibrium.order_of_unemploymentIncome
assert_no_sorry MP1994V2.ReducedEquilibrium.cutoff_strictAnti_shockArrival
assert_no_sorry MP1994V2.ReducedEquilibrium.theta_strictAnti_discountRate
assert_no_sorry MP1994V2.Primitives.strictShockBelow_mono
assert_no_sorry MP1994V2.Primitives.jobSeparationRate_mono_cutoff
assert_no_sorry MP1994V2.Primitives.jobFindingRate_mono
assert_no_sorry MP1994V2.Primitives.jobCreationFlow_mono_of_findingRate
assert_no_sorry MP1994V2.Primitives.jobDestructionFlow_mono_of_separationRate
assert_no_sorry MP1994V2.steadyUnemployment_monotone
assert_no_sorry MP1994V2.SteadyStateEquilibrium.aggregateProductivity_initialFlows
assert_no_sorry MP1994V2.SteadyStateEquilibrium.aggregateProductivity_capstone
assert_no_sorry MP1994V2.SteadyStateEquilibrium.unemploymentIncome_initialFlows
assert_no_sorry MP1994V2.SteadyStateEquilibrium.unemploymentIncome_capstone
assert_no_sorry MP1994V2.m7_aggregateNetProductivity_capstone
assert_no_sorry MP1994V2.m7_otherParameters_capstone

#print axioms MP1994V2.Primitives.workerMeetingRate_pos
#print axioms MP1994V2.ValueEquilibrium.surplus_eq
#print axioms MP1994V2.ValueEquilibrium.surplus_bellman_of_probability
#print axioms MP1994V2.ValueEquilibrium.surplus_bellman
#print axioms MP1994V2.ValueEquilibrium.equation12
#print axioms MP1994V2.ValueEquilibrium.existsUnique_surplus_zero
#print axioms MP1994V2.ValueEquilibrium.reservationCutoff_is_admissible
#print axioms MP1994V2.ValueEquilibrium.activeSurplus_eq_slope_mul_positivePart
#print axioms MP1994V2.ValueEquilibrium.milestone2_capstone
#print axioms MP1994V2.ValueEquilibrium.expectedExcess_cutoff_eq_tailOptionValue
#print axioms MP1994V2.ValueEquilibrium.equation9
#print axioms MP1994V2.ValueEquilibrium.equation10
#print axioms MP1994V2.ValueEquilibrium.equation13
#print axioms MP1994V2.ValueEquilibrium.milestone3_capstone
#print axioms MP1994V2.Primitives.expectedExcess_eq_tailOptionValue
#print axioms MP1994V2.ReducedEquilibrium.toValueEquilibrium
#print axioms MP1994V2.ReducedEquilibrium.toValueEquilibrium_reservationCutoff
#print axioms MP1994V2.ReducedEquilibrium.toValue_toReduced
#print axioms MP1994V2.ValueEquilibrium.reconstruction_components
#print axioms MP1994V2.ValueEquilibrium.reconstruction_economic_roundtrip
#print axioms MP1994V2.valueEquilibrium_nonempty_iff_reducedEquilibrium_nonempty
#print axioms MP1994V2.m4_representation_capstone
#print axioms MP1994V2.Primitives.expectedExcess_lipschitz
#print axioms MP1994V2.ReducedEquilibrium.unique
#print axioms MP1994V2.exists_staticCrossing
#print axioms MP1994V2.reducedEquilibrium_nonempty
#print axioms MP1994V2.reducedEquilibrium_existsUnique
#print axioms MP1994V2.valueEquilibrium_nonempty
#print axioms MP1994V2.ValueEquilibrium.economically_unique
#print axioms MP1994V2.m5_static_equilibrium_capstone
#print axioms MP1994V2.Primitives.strictShockBelow_eq_cdf
#print axioms MP1994V2.Primitives.steadyStateUnemployment_eq_equation14
#print axioms MP1994V2.ReducedEquilibrium.toSteadyStateEquilibrium
#print axioms MP1994V2.SteadyStateEquilibrium.toReduced_toSteady
#print axioms MP1994V2.SteadyStateEquilibrium.unique
#print axioms MP1994V2.steadyStateEquilibrium_nonempty
#print axioms MP1994V2.m6_stock_completion_capstone
#print axioms MP1994V2.m6_conditional_existence_capstone
#print axioms MP1994V2.m6_full_steady_state_capstone
#print axioms MP1994V2.ReducedEquilibrium.order_of_commonProductivity
#print axioms MP1994V2.cutoff_strictAnti_shockArrival_at_fixed_theta_of_expectedExcess_pos
#print axioms MP1994V2.cutoff_strictMono_discountRate_at_fixed_theta_of_optionValue_pos
#print axioms MP1994V2.ReducedEquilibrium.order_of_unemploymentIncome
#print axioms MP1994V2.ReducedEquilibrium.cutoff_strictAnti_shockArrival
#print axioms MP1994V2.ReducedEquilibrium.theta_strictAnti_discountRate
#print axioms MP1994V2.SteadyStateEquilibrium.aggregateProductivity_capstone
#print axioms MP1994V2.SteadyStateEquilibrium.unemploymentIncome_capstone
#print axioms MP1994V2.m7_aggregateNetProductivity_capstone
#print axioms MP1994V2.m7_otherParameters_capstone

/-! ## Milestone 8: Appendix derivative comparative statics -/

#check MP1994V2.Primitives.matchingElasticity
#check MP1994V2.AppendixMatchingAssumptions
#check MP1994V2.Primitives.deriv_q_eq_neg_elasticity_mul
#check MP1994V2.Primitives.deriv_q_neg
#check MP1994V2.Primitives.one_sub_matchingElasticity_pos
#check MP1994V2.Primitives.withDispersion
#check MP1994V2.CoreEconomicAssumptions.withDispersion
#check MP1994V2.ShockAssumptions.withDispersion
#check MP1994V2.ShockNormalizationAssumptions.withDispersion
#check MP1994V2.MatchingAssumptions.withDispersion
#check MP1994V2.LocalReducedEquilibriumPath
#check MP1994V2.LambdaEquilibriumPath
#check MP1994V2.DiscountEquilibriumPath
#check MP1994V2.DispersionEquilibriumPath
#check MP1994V2.FixedTightnessSigmaPath
#check MP1994V2.Primitives.cdf_continuous
#check MP1994V2.Primitives.cdf_continuousAt
#check MP1994V2.Primitives.hasDerivAt_expectedExcess
#check MP1994V2.Primitives.expectedExcess_le_epsUpper_sub
#check MP1994V2.Primitives.expectedExcess_lt_epsUpper_sub
#check MP1994V2.appendixA2_normalize
#check MP1994V2.appendixA2_paper
#check MP1994V2.appendixA3_of_A1_A2
#check MP1994V2.appendixA5_solve
#check MP1994V2.appendixA7_of_normalized_A6
#check MP1994V2.appendixA8_of_A5_A7
#check MP1994V2.appendixA9_normalize
#check MP1994V2.appendixA10_of_crossMultiplied
#check MP1994V2.appendixA11_slopeEquation_of_A9_A10
#check MP1994V2.appendixA12_slopeEquation_of_A9_A10
#check MP1994V2.FixedTightnessSigmaPath.equation11
#check MP1994V2.FixedTightnessSigmaPath.cutoffSlope_pos_iff
#check MP1994V2.LambdaEquilibriumPath.equationA1
#check MP1994V2.LambdaEquilibriumPath.equationA2_crossMultiplied
#check MP1994V2.LambdaEquilibriumPath.equationA2_normalized
#check MP1994V2.LambdaEquilibriumPath.equationA2
#check MP1994V2.LambdaEquilibriumPath.cutoffSlope_neg
#check MP1994V2.LambdaEquilibriumPath.equationA3
#check MP1994V2.LambdaEquilibriumPath.equationA4
#check MP1994V2.LambdaEquilibriumPath.thetaSlope_neg
#check MP1994V2.DiscountEquilibriumPath.equationA5
#check MP1994V2.DiscountEquilibriumPath.equationA6
#check MP1994V2.DiscountEquilibriumPath.thetaSlope_neg
#check MP1994V2.DiscountEquilibriumPath.equationA7
#check MP1994V2.DiscountEquilibriumPath.equationA8
#check MP1994V2.DiscountEquilibriumPath.cutoffSlope_pos_iff_A8_rhs_pos
#check MP1994V2.Primitives.epsUpper_pos_of_normalization
#check MP1994V2.Primitives.tailMoment_eq_cutoff_mul_tail_add_expectedExcess
#check MP1994V2.DispersionEquilibriumPath.equationA9
#check MP1994V2.DispersionEquilibriumPath.equationA10
#check MP1994V2.DispersionEquilibriumPath.equationA11_signCarrier_pos
#check MP1994V2.DispersionEquilibriumPath.equationA11_slopeEquation
#check MP1994V2.DispersionEquilibriumPath.thetaSlope_pos
#check MP1994V2.DispersionEquilibriumPath.equationA12
#check MP1994V2.DispersionEquilibriumPath.equationA12_slopeEquation
#check MP1994V2.DispersionEquilibriumPath.cutoffSlope_pos_iff_A12_expression_pos
#check MP1994V2.DispersionEquilibriumPath.cutoffSlope_pos_of_b_le_p
#check MP1994V2.FixedTightnessSigmaPath.m8_fixedTightness_capstone
#check MP1994V2.LambdaEquilibriumPath.m8_lambda_capstone
#check MP1994V2.DiscountEquilibriumPath.m8_discount_capstone
#check MP1994V2.DispersionEquilibriumPath.m8_dispersion_capstone
#check MP1994V2.m8_appendix_capstone

assert_no_sorry MP1994V2.Primitives.cdf_continuous
assert_no_sorry MP1994V2.Primitives.hasDerivAt_expectedExcess
assert_no_sorry MP1994V2.Primitives.expectedExcess_le_epsUpper_sub
assert_no_sorry MP1994V2.Primitives.expectedExcess_lt_epsUpper_sub
assert_no_sorry MP1994V2.appendixA2_normalize
assert_no_sorry MP1994V2.appendixA2_paper
assert_no_sorry MP1994V2.appendixA3_of_A1_A2
assert_no_sorry MP1994V2.appendixA5_solve
assert_no_sorry MP1994V2.appendixA7_of_normalized_A6
assert_no_sorry MP1994V2.appendixA8_of_A5_A7
assert_no_sorry MP1994V2.appendixA9_normalize
assert_no_sorry MP1994V2.appendixA10_of_crossMultiplied
assert_no_sorry MP1994V2.appendixA11_slopeEquation_of_A9_A10
assert_no_sorry MP1994V2.appendixA12_slopeEquation_of_A9_A10
assert_no_sorry MP1994V2.Primitives.epsUpper_pos_of_normalization
assert_no_sorry MP1994V2.Primitives.tailMoment_eq_cutoff_mul_tail_add_expectedExcess
assert_no_sorry MP1994V2.FixedTightnessSigmaPath.equation11
assert_no_sorry MP1994V2.FixedTightnessSigmaPath.cutoffSlope_pos_iff
assert_no_sorry MP1994V2.LambdaEquilibriumPath.equationA1
assert_no_sorry MP1994V2.LambdaEquilibriumPath.equationA2
assert_no_sorry MP1994V2.LambdaEquilibriumPath.cutoffSlope_neg
assert_no_sorry MP1994V2.LambdaEquilibriumPath.equationA3
assert_no_sorry MP1994V2.LambdaEquilibriumPath.equationA4
assert_no_sorry MP1994V2.LambdaEquilibriumPath.thetaSlope_neg
assert_no_sorry MP1994V2.LambdaEquilibriumPath.m8_lambda_capstone
assert_no_sorry MP1994V2.DiscountEquilibriumPath.equationA5
assert_no_sorry MP1994V2.DiscountEquilibriumPath.equationA6
assert_no_sorry MP1994V2.DiscountEquilibriumPath.thetaSlope_neg
assert_no_sorry MP1994V2.DiscountEquilibriumPath.equationA7
assert_no_sorry MP1994V2.DiscountEquilibriumPath.equationA8
assert_no_sorry MP1994V2.DiscountEquilibriumPath.cutoffSlope_pos_iff_A8_rhs_pos
assert_no_sorry MP1994V2.DiscountEquilibriumPath.m8_discount_capstone
assert_no_sorry MP1994V2.DispersionEquilibriumPath.equationA9
assert_no_sorry MP1994V2.DispersionEquilibriumPath.equationA10
assert_no_sorry MP1994V2.DispersionEquilibriumPath.equationA11_signCarrier_pos
assert_no_sorry MP1994V2.DispersionEquilibriumPath.thetaSlope_pos
assert_no_sorry MP1994V2.DispersionEquilibriumPath.equationA12
assert_no_sorry MP1994V2.DispersionEquilibriumPath.cutoffSlope_pos_iff_A12_expression_pos
assert_no_sorry MP1994V2.DispersionEquilibriumPath.cutoffSlope_pos_of_b_le_p
assert_no_sorry MP1994V2.DispersionEquilibriumPath.m8_dispersion_capstone
assert_no_sorry MP1994V2.FixedTightnessSigmaPath.m8_fixedTightness_capstone
assert_no_sorry MP1994V2.m8_appendix_capstone

#print axioms MP1994V2.Primitives.hasDerivAt_expectedExcess
#print axioms MP1994V2.LambdaEquilibriumPath.m8_lambda_capstone
#print axioms MP1994V2.DiscountEquilibriumPath.m8_discount_capstone
#print axioms MP1994V2.DispersionEquilibriumPath.m8_dispersion_capstone
#print axioms MP1994V2.m8_appendix_capstone

/-! ## M8b.1: local implicit-function paths -/

#check MP1994V2.AppendixIFTAssumptions
#check MP1994V2.Primitives.contDiffAt_expectedExcess
#check MP1994V2.Primitives.hasDerivAt_jobDestructionTheta
#check MP1994V2.Primitives.hasDerivAt_staticCrossingResidual
#check MP1994V2.ReducedEquilibrium.fixedTightnessSigma_cutoffDerivative_pos
#check MP1994V2.ReducedEquilibrium.lambdaStaticResidual_cutoffDerivative_neg
#check MP1994V2.exists_localImplicitCutoffPath
#check MP1994V2.ReducedEquilibrium.exists_fixedTightnessSigmaPath_of_ift
#check MP1994V2.ReducedEquilibrium.toFixedTightnessSigmaPathIFT
#check MP1994V2.ReducedEquilibrium.exists_lambdaEquilibriumPath_of_ift
#check MP1994V2.ReducedEquilibrium.toLambdaEquilibriumPathIFT
#check MP1994V2.ReducedEquilibrium.m8b_fixedTightness_capstone
#check MP1994V2.ReducedEquilibrium.m8b_lambda_capstone
#check MP1994V2.m8b1_implicit_paths_capstone

assert_no_sorry MP1994V2.Primitives.contDiffAt_expectedExcess
assert_no_sorry MP1994V2.Primitives.hasDerivAt_jobDestructionTheta
assert_no_sorry MP1994V2.Primitives.hasDerivAt_staticCrossingResidual
assert_no_sorry MP1994V2.ReducedEquilibrium.fixedTightnessSigma_cutoffDerivative_pos
assert_no_sorry MP1994V2.ReducedEquilibrium.lambdaStaticResidual_cutoffDerivative_neg
assert_no_sorry MP1994V2.exists_localImplicitCutoffPath
assert_no_sorry MP1994V2.ReducedEquilibrium.exists_fixedTightnessSigmaPath_of_ift
assert_no_sorry MP1994V2.ReducedEquilibrium.exists_lambdaEquilibriumPath_of_ift
assert_no_sorry MP1994V2.ReducedEquilibrium.m8b_fixedTightness_capstone
assert_no_sorry MP1994V2.ReducedEquilibrium.m8b_lambda_capstone
assert_no_sorry MP1994V2.m8b1_implicit_paths_capstone

#print axioms MP1994V2.exists_localImplicitCutoffPath
#print axioms MP1994V2.ReducedEquilibrium.exists_fixedTightnessSigmaPath_of_ift
#print axioms MP1994V2.ReducedEquilibrium.exists_lambdaEquilibriumPath_of_ift
#print axioms MP1994V2.m8b1_implicit_paths_capstone

/-! ## M8b.2: discount and dispersion implicit-function paths -/

#check MP1994V2.Primitives.discountStaticResidual
#check MP1994V2.ReducedEquilibrium.discountStaticResidual_base_eq_zero
#check MP1994V2.ReducedEquilibrium.discountStaticResidual_cutoffDerivative_neg
#check MP1994V2.ReducedEquilibrium.discountStaticResidual_cutoffDerivative_ne
#check MP1994V2.ReducedEquilibrium.discountStaticResidual_contDiffAt
#check MP1994V2.ReducedEquilibrium.exists_discountEquilibriumPath_of_ift
#check MP1994V2.ReducedEquilibrium.toDiscountEquilibriumPathIFT
#check MP1994V2.ReducedEquilibrium.m8b_discount_capstone
#check MP1994V2.Primitives.dispersionStaticResidual
#check MP1994V2.ReducedEquilibrium.dispersionStaticResidual_base_eq_zero
#check MP1994V2.ReducedEquilibrium.dispersionStaticResidual_cutoffDerivative_neg
#check MP1994V2.ReducedEquilibrium.dispersionStaticResidual_cutoffDerivative_ne
#check MP1994V2.ReducedEquilibrium.dispersionStaticResidual_contDiffAt
#check MP1994V2.ReducedEquilibrium.exists_dispersionEquilibriumPath_of_ift
#check MP1994V2.ReducedEquilibrium.toDispersionEquilibriumPathIFT
#check MP1994V2.ReducedEquilibrium.m8b_dispersion_capstone
#check MP1994V2.ReducedEquilibrium.m8b_full_appendix_capstone

assert_no_sorry MP1994V2.ReducedEquilibrium.discountStaticResidual_base_eq_zero
assert_no_sorry MP1994V2.ReducedEquilibrium.discountStaticResidual_cutoffDerivative_neg
assert_no_sorry MP1994V2.ReducedEquilibrium.discountStaticResidual_cutoffDerivative_ne
assert_no_sorry MP1994V2.ReducedEquilibrium.discountStaticResidual_contDiffAt
assert_no_sorry MP1994V2.ReducedEquilibrium.exists_discountEquilibriumPath_of_ift
assert_no_sorry MP1994V2.ReducedEquilibrium.toDiscountEquilibriumPathIFT
assert_no_sorry MP1994V2.ReducedEquilibrium.m8b_discount_capstone
assert_no_sorry MP1994V2.ReducedEquilibrium.dispersionStaticResidual_base_eq_zero
assert_no_sorry MP1994V2.ReducedEquilibrium.dispersionStaticResidual_cutoffDerivative_neg
assert_no_sorry MP1994V2.ReducedEquilibrium.dispersionStaticResidual_cutoffDerivative_ne
assert_no_sorry MP1994V2.ReducedEquilibrium.dispersionStaticResidual_contDiffAt
assert_no_sorry MP1994V2.ReducedEquilibrium.exists_dispersionEquilibriumPath_of_ift
assert_no_sorry MP1994V2.ReducedEquilibrium.toDispersionEquilibriumPathIFT
assert_no_sorry MP1994V2.ReducedEquilibrium.m8b_dispersion_capstone
assert_no_sorry MP1994V2.ReducedEquilibrium.m8b_full_appendix_capstone

#print axioms MP1994V2.ReducedEquilibrium.discountStaticResidual_base_eq_zero
#print axioms MP1994V2.ReducedEquilibrium.discountStaticResidual_cutoffDerivative_neg
#print axioms MP1994V2.ReducedEquilibrium.discountStaticResidual_contDiffAt
#print axioms MP1994V2.ReducedEquilibrium.exists_discountEquilibriumPath_of_ift
#print axioms MP1994V2.ReducedEquilibrium.toDiscountEquilibriumPathIFT
#print axioms MP1994V2.ReducedEquilibrium.m8b_discount_capstone
#print axioms MP1994V2.ReducedEquilibrium.dispersionStaticResidual_base_eq_zero
#print axioms MP1994V2.ReducedEquilibrium.dispersionStaticResidual_cutoffDerivative_neg
#print axioms MP1994V2.ReducedEquilibrium.dispersionStaticResidual_contDiffAt
#print axioms MP1994V2.ReducedEquilibrium.exists_dispersionEquilibriumPath_of_ift
#print axioms MP1994V2.ReducedEquilibrium.toDispersionEquilibriumPathIFT
#print axioms MP1994V2.ReducedEquilibrium.m8b_dispersion_capstone
#print axioms MP1994V2.ReducedEquilibrium.m8b_full_appendix_capstone

/-! ## M9.1: anticipated two-state foundations -/

#check MP1994V2.AggregateState.other
#check MP1994V2.TwoStatePrimitives.statePrimitives
#check MP1994V2.TwoStateValueCandidate.surplus
#check MP1994V2.TwoStateValueEquilibrium
#check MP1994V2.TwoStateValueEquilibrium.vacancy_value_eq_zero
#check MP1994V2.TwoStateValueEquilibrium.firm_share
#check MP1994V2.TwoStateValueEquilibrium.aggregate_transition_surplus_identity
#check MP1994V2.TwoStateValueEquilibrium.surplus_flow_equation
#check MP1994V2.TwoStateValueEquilibrium.coupled_surplus_bellman
#check MP1994V2.TwoStateValueEquilibrium.recession_surplus_bellman
#check MP1994V2.TwoStateValueEquilibrium.boom_surplus_bellman
#check MP1994V2.TwoStateValueEquilibrium.equation16_of_boom_surplus_nonneg
#check MP1994V2.TwoStateValueEquilibrium.equation17_of_recession_surplus_nonneg
#check MP1994V2.TwoStateValueEquilibrium.equation18_of_recession_surplus_nonpos
#check MP1994V2.TwoStateValueEquilibrium.m9_1_two_state_foundations

assert_no_sorry MP1994V2.AggregateState.other_other
assert_no_sorry MP1994V2.TwoStateEconomicAssumptions.productivity_recession_lt_boom
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.vacancy_value_eq_zero
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.firm_share
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.aggregate_transition_surplus_identity
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.surplus_flow_equation
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.coupled_surplus_bellman
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.recession_surplus_bellman
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_surplus_bellman
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation16_of_boom_surplus_nonneg
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation17_of_recession_surplus_nonneg
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation18_of_recession_surplus_nonpos
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.m9_1_two_state_foundations

#print axioms MP1994V2.TwoStateEconomicAssumptions.productivity_recession_lt_boom
#print axioms MP1994V2.TwoStateValueEquilibrium.vacancy_value_eq_zero
#print axioms MP1994V2.TwoStateValueEquilibrium.firm_share
#print axioms MP1994V2.TwoStateValueEquilibrium.aggregate_transition_surplus_identity
#print axioms MP1994V2.TwoStateValueEquilibrium.surplus_flow_equation
#print axioms MP1994V2.TwoStateValueEquilibrium.coupled_surplus_bellman
#print axioms MP1994V2.TwoStateValueEquilibrium.equation16_of_boom_surplus_nonneg
#print axioms MP1994V2.TwoStateValueEquilibrium.equation17_of_recession_surplus_nonneg
#print axioms MP1994V2.TwoStateValueEquilibrium.equation18_of_recession_surplus_nonpos
#print axioms MP1994V2.TwoStateValueEquilibrium.m9_1_two_state_foundations

/-! ## M9.2A: ordering-independent statewise cutoffs -/

#check MP1994V2.positivePart_mono
#check MP1994V2.positivePart_sub_nonneg
#check MP1994V2.positivePart_sub_le
#check MP1994V2.le_positivePart_sub_of_sub_nonpos
#check MP1994V2.abs_positivePart_sub_le
#check MP1994V2.TwoStateValueEquilibrium.recession_surplus_difference
#check MP1994V2.TwoStateValueEquilibrium.boom_surplus_difference
#check MP1994V2.TwoStateValueEquilibrium.surplus_increment_pos
#check MP1994V2.TwoStateValueEquilibrium.surplus_strictMono
#check MP1994V2.TwoStateValueEquilibrium.surplus_difference_lowerBound
#check MP1994V2.TwoStateValueEquilibrium.surplus_difference_upperBound
#check MP1994V2.TwoStateValueEquilibrium.surplus_lipschitz
#check MP1994V2.TwoStateValueEquilibrium.surplus_continuous
#check MP1994V2.TwoStateValueEquilibrium.upper_firm_value_pos
#check MP1994V2.TwoStateValueEquilibrium.upper_surplus_pos
#check MP1994V2.TwoStateValueEquilibrium.exists_surplus_neg
#check MP1994V2.TwoStateValueEquilibrium.reservationCutoff
#check MP1994V2.TwoStateValueEquilibrium.surplus_reservationCutoff_eq_zero
#check MP1994V2.TwoStateValueEquilibrium.surplus_eq_zero_iff
#check MP1994V2.TwoStateValueEquilibrium.existsUnique_surplus_zero
#check MP1994V2.TwoStateValueEquilibrium.reservationCutoff_lt_epsUpper
#check MP1994V2.TwoStateValueEquilibrium.surplus_neg_iff_lt_reservationCutoff
#check MP1994V2.TwoStateValueEquilibrium.surplus_pos_iff_reservationCutoff_lt
#check MP1994V2.TwoStateValueEquilibrium.surplus_nonneg_iff_reservationCutoff_le
#check MP1994V2.TwoStateValueEquilibrium.firm_value_neg_iff_lt_reservationCutoff
#check MP1994V2.TwoStateValueEquilibrium.firm_value_eq_zero_iff
#check MP1994V2.TwoStateValueEquilibrium.firm_value_nonneg_iff_reservationCutoff_le
#check MP1994V2.TwoStateValueEquilibrium.survivingSurplusIntegral
#check MP1994V2.TwoStateValueEquilibrium.integral_activeSurplus_eq_survivingSurplusIntegral
#check MP1994V2.TwoStateValueEquilibrium.statewise_continuation_integral_eq

assert_no_sorry MP1994V2.positivePart_sub_le
assert_no_sorry MP1994V2.le_positivePart_sub_of_sub_nonpos
assert_no_sorry MP1994V2.abs_positivePart_sub_le
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.recession_surplus_difference
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_surplus_difference
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.surplus_increment_pos
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.surplus_strictMono
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.surplus_difference_lowerBound
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.surplus_difference_upperBound
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.surplus_lipschitz
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.surplus_continuous
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.upper_surplus_pos
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.exists_surplus_neg
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.surplus_reservationCutoff_eq_zero
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.existsUnique_surplus_zero
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.reservationCutoff_lt_epsUpper
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.firm_value_eq_zero_iff
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.integral_activeSurplus_eq_survivingSurplusIntegral
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.statewise_continuation_integral_eq

#print axioms MP1994V2.TwoStateValueEquilibrium.surplus_increment_pos
#print axioms MP1994V2.TwoStateValueEquilibrium.surplus_difference_upperBound
#print axioms MP1994V2.TwoStateValueEquilibrium.surplus_lipschitz
#print axioms MP1994V2.TwoStateValueEquilibrium.exists_surplus_neg
#print axioms MP1994V2.TwoStateValueEquilibrium.existsUnique_surplus_zero
#print axioms MP1994V2.TwoStateValueEquilibrium.integral_activeSurplus_eq_survivingSurplusIntegral

/-! ## M9.2B: maximum-principle cutoff ordering -/

#check MP1994V2.TwoStateValueEquilibrium.surplus_gap_eq_at_recession_cutoff_of_le_recession_cutoff
#check MP1994V2.TwoStateValueEquilibrium.surplus_gap_eq_at_boom_cutoff_of_boom_cutoff_le
#check MP1994V2.TwoStateValueEquilibrium.boom_surplus_le_recession_surplus_of_reverse_cutoff_order
#check MP1994V2.TwoStateValueEquilibrium.statewise_q_mul_surplus_upper_eq
#check MP1994V2.TwoStateValueEquilibrium.boom_tightness_le_recession_tightness_of_reverse_order
#check MP1994V2.TwoStateValueEquilibrium.upper_surplus_gap_le_activeSurplus_gap_of_reverse_order
#check MP1994V2.TwoStateValueEquilibrium.upper_surplus_gap_le_integral_activeSurplus_gap_of_reverse_order
#check MP1994V2.TwoStateValueEquilibrium.statewise_search_gain_eq
#check MP1994V2.TwoStateValueEquilibrium.upper_surplus_gap_equation
#check MP1994V2.TwoStateValueEquilibrium.not_recession_cutoff_le_boom_cutoff
#check MP1994V2.TwoStateValueEquilibrium.boom_cutoff_lt_recession_cutoff
#check MP1994V2.TwoStateValueEquilibrium.recession_upper_surplus_lt_boom_upper_surplus
#check MP1994V2.TwoStateValueEquilibrium.recession_tightness_lt_boom_tightness
#check MP1994V2.TwoStateValueEquilibrium.m9_2B_cutoff_ordering_capstone

assert_no_sorry MP1994V2.TwoStateValueEquilibrium.surplus_gap_eq_at_recession_cutoff_of_le_recession_cutoff
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.surplus_gap_eq_at_boom_cutoff_of_boom_cutoff_le
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_surplus_le_recession_surplus_of_reverse_cutoff_order
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.statewise_q_mul_surplus_upper_eq
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_tightness_le_recession_tightness_of_reverse_order
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.upper_surplus_gap_le_activeSurplus_gap_of_reverse_order
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.upper_surplus_gap_le_integral_activeSurplus_gap_of_reverse_order
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.statewise_search_gain_eq
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.upper_surplus_gap_equation
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.not_recession_cutoff_le_boom_cutoff
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_cutoff_lt_recession_cutoff
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.recession_upper_surplus_lt_boom_upper_surplus
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.recession_tightness_lt_boom_tightness
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.m9_2B_cutoff_ordering_capstone

#print axioms MP1994V2.TwoStateValueEquilibrium.surplus_gap_eq_at_recession_cutoff_of_le_recession_cutoff
#print axioms MP1994V2.TwoStateValueEquilibrium.surplus_gap_eq_at_boom_cutoff_of_boom_cutoff_le
#print axioms MP1994V2.TwoStateValueEquilibrium.boom_surplus_le_recession_surplus_of_reverse_cutoff_order
#print axioms MP1994V2.TwoStateValueEquilibrium.boom_tightness_le_recession_tightness_of_reverse_order
#print axioms MP1994V2.TwoStateValueEquilibrium.upper_surplus_gap_le_integral_activeSurplus_gap_of_reverse_order
#print axioms MP1994V2.TwoStateValueEquilibrium.upper_surplus_gap_equation
#print axioms MP1994V2.TwoStateValueEquilibrium.not_recession_cutoff_le_boom_cutoff
#print axioms MP1994V2.TwoStateValueEquilibrium.boom_cutoff_lt_recession_cutoff
#print axioms MP1994V2.TwoStateValueEquilibrium.m9_2B_cutoff_ordering_capstone

/-! ## M9.2C: ordered regional equations (16)--(24) -/

#check MP1994V2.Primitives.tailProbability_antitone
#check MP1994V2.Primitives.tailOptionValue_sub_eq_interval
#check MP1994V2.TwoStateValueEquilibrium.equation16_ordered
#check MP1994V2.TwoStateValueEquilibrium.equation17_ordered
#check MP1994V2.TwoStateValueEquilibrium.equation18_ordered
#check MP1994V2.TwoStateValueEquilibrium.recession_surplus_difference_above_recession_cutoff
#check MP1994V2.TwoStateValueEquilibrium.boom_surplus_difference_above_recession_cutoff
#check MP1994V2.TwoStateValueEquilibrium.boom_surplus_difference_between_cutoffs
#check MP1994V2.TwoStateValueEquilibrium.equation21_difference
#check MP1994V2.TwoStateValueEquilibrium.recession_surplus_above_recession_cutoff
#check MP1994V2.TwoStateValueEquilibrium.boom_surplus_between_cutoffs
#check MP1994V2.TwoStateValueEquilibrium.boom_surplus_above_recession_cutoff
#check MP1994V2.TwoStateValueEquilibrium.regionalBoomSlope_pos
#check MP1994V2.TwoStateValueEquilibrium.upperRegionalSlope_pos
#check MP1994V2.TwoStateValueEquilibrium.regionalBoomSlope_lt_upperRegionalSlope
#check MP1994V2.TwoStateValueEquilibrium.recession_activeSurplus_hinge
#check MP1994V2.TwoStateValueEquilibrium.boom_activeSurplus_hinge
#check MP1994V2.TwoStateValueEquilibrium.recession_activeSurplus_integral_eq_expectedExcess
#check MP1994V2.TwoStateValueEquilibrium.recession_activeSurplus_integral_eq_tailOptionValue
#check MP1994V2.TwoStateValueEquilibrium.boom_activeSurplus_integral_eq_expectedExcess
#check MP1994V2.TwoStateValueEquilibrium.boom_activeSurplus_integral_eq_expectedExcess_difference
#check MP1994V2.TwoStateValueEquilibrium.boom_activeSurplus_integral_eq_tailIntervals
#check MP1994V2.TwoStateValueEquilibrium.equation19
#check MP1994V2.TwoStateValueEquilibrium.equation20
#check MP1994V2.TwoStateValueEquilibrium.equation22
#check MP1994V2.TwoStateValueEquilibrium.equation23
#check MP1994V2.TwoStateValueEquilibrium.equation24
#check MP1994V2.TwoStateValueEquilibrium.SatisfiesM92COrderedEquations
#check MP1994V2.TwoStateValueEquilibrium.m9_2C_ordered_equations_capstone
#check MP1994V2.TwoStateValueEquilibrium.m9_2_full_cutoff_capstone

assert_no_sorry MP1994V2.Primitives.tailProbability_antitone
assert_no_sorry MP1994V2.Primitives.tailOptionValue_sub_eq_interval
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation16_ordered
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation17_ordered
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation18_ordered
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.recession_surplus_difference_above_recession_cutoff
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_surplus_difference_above_recession_cutoff
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_surplus_difference_between_cutoffs
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation21_difference
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.recession_surplus_above_recession_cutoff
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_surplus_between_cutoffs
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_surplus_above_recession_cutoff
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.regionalBoomSlope_pos
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.upperRegionalSlope_pos
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.regionalBoomSlope_lt_upperRegionalSlope
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.recession_activeSurplus_hinge
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_activeSurplus_hinge
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.recession_activeSurplus_integral_eq_expectedExcess
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.recession_activeSurplus_integral_eq_tailOptionValue
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_activeSurplus_integral_eq_expectedExcess
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_activeSurplus_integral_eq_expectedExcess_difference
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_activeSurplus_integral_eq_tailIntervals
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation19
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation20
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation22
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation23
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation24
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.m9_2C_ordered_equations_capstone
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.m9_2_full_cutoff_capstone

#print axioms MP1994V2.TwoStateValueEquilibrium.equation16_ordered
#print axioms MP1994V2.TwoStateValueEquilibrium.equation21_difference
#print axioms MP1994V2.TwoStateValueEquilibrium.boom_activeSurplus_hinge
#print axioms MP1994V2.TwoStateValueEquilibrium.boom_activeSurplus_integral_eq_tailIntervals
#print axioms MP1994V2.TwoStateValueEquilibrium.equation20
#print axioms MP1994V2.TwoStateValueEquilibrium.equation24
#print axioms MP1994V2.TwoStateValueEquilibrium.m9_2C_ordered_equations_capstone
#print axioms MP1994V2.TwoStateValueEquilibrium.m9_2_full_cutoff_capstone
#print axioms MP1994V2.Primitives.tailOptionValue_sub_eq_interval
#print axioms MP1994V2.TwoStateValueEquilibrium.boom_activeSurplus_integral_eq_expectedExcess

/-! ## M9.3: job creation, labor flows, and aggregate-shock impact -/

#check MP1994V2.TwoStateValueEquilibrium.equation25
#check MP1994V2.TwoStateValueEquilibrium.equation26
#check MP1994V2.TwoStateValueEquilibrium.equation27
#check MP1994V2.TwoStateValueEquilibrium.equation28
#check MP1994V2.TwoStateValueEquilibrium.equation29
#check MP1994V2.TwoStateValueEquilibrium.boomJobCreationDenominator
#check MP1994V2.TwoStateValueEquilibrium.boomJobCreationDenominator_eq
#check MP1994V2.TwoStateValueEquilibrium.boomJobCreationDenominator_pos
#check MP1994V2.TwoStateValueEquilibrium.equation30
#check MP1994V2.TwoStateValueEquilibrium.boomJobCreationDenominator_lt_staticGap
#check MP1994V2.TwoStateValueEquilibrium.staticJobCreationTarget_lt_boomVacancyMeetingRate
#check MP1994V2.TwoStateValueEquilibrium.SatisfiesM93JobCreation
#check MP1994V2.TwoStateValueEquilibrium.m9_3_jobCreation_capstone

#check MP1994V2.TwoStateValueEquilibrium.idiosyncraticDestructionHazard
#check MP1994V2.TwoStateValueEquilibrium.workerMeetingHazard
#check MP1994V2.TwoStateValueEquilibrium.jobCreationFlow
#check MP1994V2.TwoStateValueEquilibrium.idiosyncraticDestructionFlow
#check MP1994V2.TwoStateValueEquilibrium.idiosyncraticDestructionHazard_nonneg
#check MP1994V2.TwoStateValueEquilibrium.workerMeetingHazard_pos
#check MP1994V2.TwoStateValueEquilibrium.jobCreationFlow_nonneg
#check MP1994V2.TwoStateValueEquilibrium.idiosyncraticDestructionFlow_nonneg
#check MP1994V2.TwoStateValueEquilibrium.workerMeetingHazard_strictMonoOn_pos
#check MP1994V2.TwoStateValueEquilibrium.boom_destructionHazard_le_recession
#check MP1994V2.TwoStateValueEquilibrium.recession_workerMeetingHazard_lt_boom
#check MP1994V2.TwoStateValueEquilibrium.boom_destructionHazard_lt_recession
#check MP1994V2.TwoStateValueEquilibrium.recession_jobCreationFlow_lt_boom
#check MP1994V2.TwoStateValueEquilibrium.boom_idiosyncraticDestructionFlow_le_recession
#check MP1994V2.TwoStateValueEquilibrium.boom_idiosyncraticDestructionFlow_lt_recession

#check MP1994V2.TwoStateValueEquilibrium.unemploymentInflow
#check MP1994V2.TwoStateValueEquilibrium.unemploymentOutflow
#check MP1994V2.TwoStateValueEquilibrium.unemploymentDrift
#check MP1994V2.TwoStateValueEquilibrium.equation15
#check MP1994V2.TwoStateValueEquilibrium.SatisfiesEquation15
#check MP1994V2.TwoStateValueEquilibrium.unemploymentDrift_affine
#check MP1994V2.TwoStateValueEquilibrium.stationaryUnemployment
#check MP1994V2.TwoStateValueEquilibrium.stationaryUnemployment_denominator_pos
#check MP1994V2.TwoStateValueEquilibrium.stationaryUnemployment_nonneg
#check MP1994V2.TwoStateValueEquilibrium.stationaryUnemployment_lt_one
#check MP1994V2.TwoStateValueEquilibrium.unemploymentDrift_stationary_eq_zero
#check MP1994V2.TwoStateValueEquilibrium.unemploymentDrift_pos_of_lt_stationary
#check MP1994V2.TwoStateValueEquilibrium.unemploymentDrift_neg_of_stationary_lt
#check MP1994V2.TwoStateValueEquilibrium.boom_unemploymentDrift_lt_recession
#check MP1994V2.TwoStateValueEquilibrium.SatisfiesM93UnemploymentDynamics
#check MP1994V2.TwoStateValueEquilibrium.m9_3_unemployment_capstone

#check MP1994V2.StateEmploymentDistribution
#check MP1994V2.StateEmploymentDistribution.ae_mem_Ici_cutoff
#check MP1994V2.StateEmploymentDistribution.afterAggregateShock
#check MP1994V2.StateEmploymentDistribution.afterAggregateShock_measure_le
#check MP1994V2.StateEmploymentDistribution.impactDestructionMass
#check MP1994V2.StateEmploymentDistribution.impactCreationMass
#check MP1994V2.StateEmploymentDistribution.impactCreationMass_eq_zero
#check MP1994V2.StateEmploymentDistribution.recession_to_boom_employmentMeasure_eq
#check MP1994V2.StateEmploymentDistribution.recession_to_boom_impactDestruction_zero
#check MP1994V2.StateEmploymentDistribution.recession_to_boom_no_impact_employment_change
#check MP1994V2.StateEmploymentDistribution.boom_to_recession_measure_decomposition
#check MP1994V2.StateEmploymentDistribution.boom_to_recession_impactDestruction_eq
#check MP1994V2.StateEmploymentDistribution.boom_to_recession_totalMass_accounting
#check MP1994V2.StateEmploymentDistribution.boom_to_recession_employmentMass_lt
#check MP1994V2.StateEmploymentDistribution.employmentMass
#check MP1994V2.StateEmploymentDistribution.unemploymentMass
#check MP1994V2.StateEmploymentDistribution.employmentMass_nonneg
#check MP1994V2.StateEmploymentDistribution.employmentMass_le_one
#check MP1994V2.StateEmploymentDistribution.unemploymentMass_nonneg
#check MP1994V2.StateEmploymentDistribution.unemploymentMass_le_one
#check MP1994V2.StateEmploymentDistribution.employmentMass_add_unemploymentMass
#check MP1994V2.StateEmploymentDistribution.boom_to_recession_unemploymentMass_eq
#check MP1994V2.StateEmploymentDistribution.recession_to_boom_unemploymentMass_eq
#check MP1994V2.TwoStateValueEquilibrium.m9_3_impact_asymmetry_capstone
#check MP1994V2.TwoStateValueEquilibrium.m9_3_full_cyclical_dynamics_capstone

assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation25
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation26
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation27
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation28
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation29
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boomJobCreationDenominator_eq
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boomJobCreationDenominator_pos
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation30
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boomJobCreationDenominator_lt_staticGap
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.staticJobCreationTarget_lt_boomVacancyMeetingRate
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.m9_3_jobCreation_capstone

assert_no_sorry MP1994V2.TwoStateValueEquilibrium.idiosyncraticDestructionHazard_nonneg
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.workerMeetingHazard_pos
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.jobCreationFlow_nonneg
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.idiosyncraticDestructionFlow_nonneg
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.workerMeetingHazard_strictMonoOn_pos
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_destructionHazard_le_recession
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.recession_workerMeetingHazard_lt_boom
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_destructionHazard_lt_recession
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.recession_jobCreationFlow_lt_boom
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_idiosyncraticDestructionFlow_le_recession
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_idiosyncraticDestructionFlow_lt_recession

assert_no_sorry MP1994V2.TwoStateValueEquilibrium.equation15
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.unemploymentDrift_affine
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.stationaryUnemployment_denominator_pos
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.stationaryUnemployment_nonneg
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.stationaryUnemployment_lt_one
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.unemploymentDrift_stationary_eq_zero
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.unemploymentDrift_pos_of_lt_stationary
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.unemploymentDrift_neg_of_stationary_lt
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.boom_unemploymentDrift_lt_recession
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.m9_3_unemployment_capstone

assert_no_sorry MP1994V2.StateEmploymentDistribution.ae_mem_Ici_cutoff
assert_no_sorry MP1994V2.StateEmploymentDistribution.afterAggregateShock_measure_le
assert_no_sorry MP1994V2.StateEmploymentDistribution.impactCreationMass_eq_zero
assert_no_sorry MP1994V2.StateEmploymentDistribution.recession_to_boom_employmentMeasure_eq
assert_no_sorry MP1994V2.StateEmploymentDistribution.recession_to_boom_impactDestruction_zero
assert_no_sorry MP1994V2.StateEmploymentDistribution.recession_to_boom_no_impact_employment_change
assert_no_sorry MP1994V2.StateEmploymentDistribution.boom_to_recession_measure_decomposition
assert_no_sorry MP1994V2.StateEmploymentDistribution.boom_to_recession_impactDestruction_eq
assert_no_sorry MP1994V2.StateEmploymentDistribution.boom_to_recession_totalMass_accounting
assert_no_sorry MP1994V2.StateEmploymentDistribution.boom_to_recession_employmentMass_lt
assert_no_sorry MP1994V2.StateEmploymentDistribution.employmentMass_nonneg
assert_no_sorry MP1994V2.StateEmploymentDistribution.employmentMass_le_one
assert_no_sorry MP1994V2.StateEmploymentDistribution.unemploymentMass_nonneg
assert_no_sorry MP1994V2.StateEmploymentDistribution.unemploymentMass_le_one
assert_no_sorry MP1994V2.StateEmploymentDistribution.employmentMass_add_unemploymentMass
assert_no_sorry MP1994V2.StateEmploymentDistribution.boom_to_recession_unemploymentMass_eq
assert_no_sorry MP1994V2.StateEmploymentDistribution.recession_to_boom_unemploymentMass_eq
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.m9_3_impact_asymmetry_capstone
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.m9_3_full_cyclical_dynamics_capstone

#print axioms MP1994V2.TwoStateValueEquilibrium.equation28
#print axioms MP1994V2.TwoStateValueEquilibrium.equation30
#print axioms MP1994V2.TwoStateValueEquilibrium.workerMeetingHazard_strictMonoOn_pos
#print axioms MP1994V2.TwoStateValueEquilibrium.equation15
#print axioms MP1994V2.TwoStateValueEquilibrium.boom_unemploymentDrift_lt_recession
#print axioms MP1994V2.StateEmploymentDistribution.boom_to_recession_measure_decomposition
#print axioms MP1994V2.StateEmploymentDistribution.boom_to_recession_unemploymentMass_eq
#print axioms MP1994V2.TwoStateValueEquilibrium.m9_3_full_cyclical_dynamics_capstone

#check MP1994V2.FiniteAggregateProcess
#check MP1994V2.FiniteAggregateProcessAssumptions
#check MP1994V2.FiniteAggregateProcess.statePrimitives
#check MP1994V2.FiniteAggregateProcess.statePrimitives_r
#check MP1994V2.FiniteAggregateProcess.statePrimitives_lambda
#check MP1994V2.FiniteAggregateProcess.statePrimitives_sigma
#check MP1994V2.FiniteAggregateProcess.statePrimitives_beta
#check MP1994V2.FiniteAggregateProcess.statePrimitives_c
#check MP1994V2.FiniteAggregateProcess.statePrimitives_b
#check MP1994V2.FiniteAggregateProcess.statePrimitives_epsUpper
#check MP1994V2.FiniteAggregateProcess.statePrimitives_shock
#check MP1994V2.FiniteAggregateProcess.statePrimitives_q
#check MP1994V2.CoreEconomicAssumptions.finiteStatePrimitives
#check MP1994V2.ShockAssumptions.finiteStatePrimitives
#check MP1994V2.MatchingAssumptions.finiteStatePrimitives
#check MP1994V2.FiniteAggregateProcess.nextExpectation
#check MP1994V2.FiniteAggregateProcess.nextExpectation_zero
#check MP1994V2.FiniteAggregateProcess.nextExpectation_const
#check MP1994V2.FiniteAggregateProcess.nextExpectation_add
#check MP1994V2.FiniteAggregateProcess.nextExpectation_smul
#check MP1994V2.FiniteAggregateProcess.nextExpectation_nonneg
#check MP1994V2.FiniteAggregateProcess.nextExpectation_mono
#check MP1994V2.FiniteMarkovCandidate
#check MP1994V2.FiniteMarkovCandidate.workerMeetingHazard
#check MP1994V2.FiniteMarkovCandidate.activeSurplus
#check MP1994V2.FiniteMarkovCandidate.survivingSurplusIntegral
#check MP1994V2.FiniteMarkovEquilibrium
#check MP1994V2.FiniteMarkovEquilibrium.workerMeetingHazard_eq
#check MP1994V2.FiniteMarkovEquilibrium.equation32
#check MP1994V2.FiniteMarkovEquilibrium.equation33
#check MP1994V2.FiniteMarkovEquilibrium.equation34
#check MP1994V2.FiniteMarkovEquilibrium.q_mul_upperSurplus_eq
#check MP1994V2.FiniteMarkovEquilibrium.upperSurplus_pos
#check MP1994V2.FiniteMarkovEquilibrium.workerMeetingHazard_pos
#check MP1994V2.FiniteMarkovEquilibrium.aggregateContinuation_nonneg
#check MP1994V2.FiniteMarkovEquilibrium.SatisfiesFiniteMarkovEquations32To34
#check MP1994V2.FiniteMarkovEquilibrium.m10_1_finiteMarkov_capstone
#check MP1994V2.TwoStatePrimitives.toFiniteAggregateProcess
#check MP1994V2.TwoStatePrimitives.toFiniteAggregateProcess_transitionWeight_nonneg
#check MP1994V2.TwoStatePrimitives.toFiniteAggregateProcess_transitionWeight_sum_one
#check MP1994V2.TwoStatePrimitives.toFiniteAggregateProcess_assumptions
#check MP1994V2.TwoStatePrimitives.nextExpectation_toFiniteAggregateProcess
#check MP1994V2.TwoStateValueEquilibrium.toFiniteMarkovCandidate
#check MP1994V2.TwoStateValueEquilibrium.toFiniteMarkovCandidate_theta
#check MP1994V2.TwoStateValueEquilibrium.toFiniteMarkovCandidate_cutoff
#check MP1994V2.TwoStateValueEquilibrium.toFiniteMarkovCandidate_surplus
#check MP1994V2.TwoStateValueEquilibrium.toFiniteMarkovEquilibrium
#check MP1994V2.TwoStateValueEquilibrium.toFiniteMarkovEquilibrium_theta
#check MP1994V2.TwoStateValueEquilibrium.toFiniteMarkovEquilibrium_cutoff
#check MP1994V2.TwoStateValueEquilibrium.toFiniteMarkovEquilibrium_surplus
#check MP1994V2.TwoStateValueEquilibrium.m10_1_twoState_embedding_capstone
#check MP1994V2.m10_1_finiteState_foundations_capstone
#check MP1994V2.m10_1_twoState_foundations_capstone

assert_no_sorry MP1994V2.FiniteAggregateProcess.nextExpectation_const
assert_no_sorry MP1994V2.FiniteAggregateProcess.nextExpectation_add
assert_no_sorry MP1994V2.FiniteAggregateProcess.nextExpectation_smul
assert_no_sorry MP1994V2.FiniteAggregateProcess.nextExpectation_nonneg
assert_no_sorry MP1994V2.FiniteAggregateProcess.nextExpectation_mono
assert_no_sorry MP1994V2.CoreEconomicAssumptions.finiteStatePrimitives
assert_no_sorry MP1994V2.ShockAssumptions.finiteStatePrimitives
assert_no_sorry MP1994V2.MatchingAssumptions.finiteStatePrimitives
assert_no_sorry MP1994V2.FiniteMarkovEquilibrium.equation32
assert_no_sorry MP1994V2.FiniteMarkovEquilibrium.equation33
assert_no_sorry MP1994V2.FiniteMarkovEquilibrium.equation34
assert_no_sorry MP1994V2.FiniteMarkovEquilibrium.q_mul_upperSurplus_eq
assert_no_sorry MP1994V2.FiniteMarkovEquilibrium.upperSurplus_pos
assert_no_sorry MP1994V2.FiniteMarkovEquilibrium.workerMeetingHazard_pos
assert_no_sorry MP1994V2.FiniteMarkovEquilibrium.aggregateContinuation_nonneg
assert_no_sorry MP1994V2.FiniteMarkovEquilibrium.m10_1_finiteMarkov_capstone
assert_no_sorry MP1994V2.TwoStatePrimitives.toFiniteAggregateProcess_transitionWeight_sum_one
assert_no_sorry MP1994V2.TwoStatePrimitives.toFiniteAggregateProcess_assumptions
assert_no_sorry MP1994V2.TwoStatePrimitives.nextExpectation_toFiniteAggregateProcess
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.toFiniteMarkovEquilibrium
assert_no_sorry MP1994V2.TwoStateValueEquilibrium.m10_1_twoState_embedding_capstone
assert_no_sorry MP1994V2.m10_1_finiteState_foundations_capstone
assert_no_sorry MP1994V2.m10_1_twoState_foundations_capstone

#print axioms MP1994V2.FiniteAggregateProcess.nextExpectation_mono
#print axioms MP1994V2.FiniteAggregateProcess.nextExpectation_const
#print axioms MP1994V2.FiniteMarkovEquilibrium.q_mul_upperSurplus_eq
#print axioms MP1994V2.FiniteMarkovEquilibrium.upperSurplus_pos
#print axioms MP1994V2.FiniteMarkovEquilibrium.aggregateContinuation_nonneg
#print axioms MP1994V2.FiniteMarkovEquilibrium.m10_1_finiteMarkov_capstone
#print axioms MP1994V2.TwoStatePrimitives.nextExpectation_toFiniteAggregateProcess
#print axioms MP1994V2.TwoStateValueEquilibrium.m10_1_twoState_embedding_capstone
#print axioms MP1994V2.TwoStateValueEquilibrium.toFiniteMarkovEquilibrium
#print axioms MP1994V2.m10_1_finiteState_foundations_capstone
#print axioms MP1994V2.m10_1_twoState_foundations_capstone
