import Mathlib.Util.AssertNoSorry
import Lean4Tutorial.i002_replicate_MP_v2.MP1994V2.All

/-!
# MP1994 v2 audit through Milestone 4

This module checks the public foundation interfaces without adding substantive
economic theorems.
-/

#check MP1994V2.Primitives
#check MP1994V2.CoreEconomicAssumptions
#check MP1994V2.ShockAssumptions
#check MP1994V2.ShockNormalizationAssumptions
#check MP1994V2.MatchingAssumptions
#check MP1994V2.Primitives.cdf
#check MP1994V2.Primitives.IsShockUpperBound
#check MP1994V2.MarketTightness
#check MP1994V2.Primitives.vacancyMeetingRate
#check MP1994V2.Primitives.workerMeetingRate
#check MP1994V2.surplus
#check MP1994V2.activeSurplus
#check MP1994V2.continuationTerm
#check MP1994V2.ValueCandidate
#check MP1994V2.ValueEquilibrium
#check MP1994V2.continuationTerm_eq_integral_activeSurplus_sub
#check MP1994V2.ValueEquilibrium.firm_share
#check MP1994V2.ValueEquilibrium.surplus_flow_equation
#check MP1994V2.ValueEquilibrium.surplus_bellman_of_probability
#check MP1994V2.ValueEquilibrium.surplus_bellman
#check MP1994V2.CoreEconomicAssumptions.r_add_lambda_pos
#check MP1994V2.CoreEconomicAssumptions.r_add_lambda_ne
#check MP1994V2.CoreEconomicAssumptions.sigma_ne
#check MP1994V2.CoreEconomicAssumptions.surplus_slope_pos
#check MP1994V2.CoreEconomicAssumptions.one_sub_beta_pos
#check MP1994V2.ValueEquilibrium.surplus_difference_scaled_of_probability
#check MP1994V2.ValueEquilibrium.surplus_difference_scaled
#check MP1994V2.ValueEquilibrium.surplus_difference
#check MP1994V2.ValueEquilibrium.surplus_difference_of_shockAssumptions
#check MP1994V2.ValueEquilibrium.surplus_strictMono
#check MP1994V2.ValueEquilibrium.surplus_strictMono_of_shockAssumptions
#check MP1994V2.ValueEquilibrium.reservationCutoff
#check MP1994V2.ValueEquilibrium.surplus_reservationCutoff_eq_zero
#check MP1994V2.ValueEquilibrium.surplus_reservationCutoff_eq_zero_of_shockAssumptions
#check MP1994V2.ValueEquilibrium.surplus_eq_zero_iff
#check MP1994V2.ValueEquilibrium.existsUnique_surplus_zero
#check MP1994V2.ValueEquilibrium.existsUnique_surplus_zero_of_shockAssumptions
#check MP1994V2.ValueEquilibrium.vacancy_value_eq_zero
#check MP1994V2.ValueEquilibrium.vacancy_meeting_mul_upper_firm_value_eq_cost
#check MP1994V2.ValueEquilibrium.upper_firm_value_pos
#check MP1994V2.ValueEquilibrium.upper_surplus_pos
#check MP1994V2.ValueEquilibrium.reservationCutoff_lt_epsUpper
#check MP1994V2.ValueEquilibrium.reservationCutoff_is_admissible
#check MP1994V2.ValueEquilibrium.equation12
#check MP1994V2.ValueEquilibrium.equation12_of_shockAssumptions
#check MP1994V2.ValueEquilibrium.surplus_eq_slope_mul_sub_cutoff
#check MP1994V2.ValueEquilibrium.surplus_eq_slope_mul_sub_cutoff_of_shockAssumptions
#check MP1994V2.ValueEquilibrium.surplus_neg_iff_lt_reservationCutoff
#check MP1994V2.ValueEquilibrium.surplus_pos_iff_reservationCutoff_lt
#check MP1994V2.ValueEquilibrium.surplus_nonneg_iff_reservationCutoff_le
#check MP1994V2.ValueEquilibrium.firm_value_neg_iff_lt_reservationCutoff
#check MP1994V2.ValueEquilibrium.firm_value_eq_zero_iff
#check MP1994V2.ValueEquilibrium.firm_value_nonneg_iff_reservationCutoff_le
#check MP1994V2.ValueEquilibrium.activeSurplus_eq_slope_mul_positivePart
#check MP1994V2.ValueEquilibrium.milestone2_capstone
#check MP1994V2.Primitives.expectedExcess
#check MP1994V2.Primitives.tailProbability
#check MP1994V2.Primitives.tailOptionValue
#check MP1994V2.Primitives.measureReal_Ioi_eq_one_sub_cdf
#check MP1994V2.Primitives.expectedExcess_nonneg
#check MP1994V2.positivePart_nonneg
#check MP1994V2.measurable_positivePart_sub
#check MP1994V2.ValueEquilibrium.positivePart_sub_cutoff_integrable
#check MP1994V2.ValueEquilibrium.expectedExcess_cutoff_eq_tailOptionValue
#check MP1994V2.ValueEquilibrium.integral_activeSurplus_eq_slope_mul_expectedExcess
#check MP1994V2.ValueEquilibrium.integral_activeSurplus_eq_slope_mul_tailOptionValue
#check MP1994V2.ValueEquilibrium.equation9_measure
#check MP1994V2.ValueEquilibrium.equation9
#check MP1994V2.Primitives.jobDestructionResidualMeasure
#check MP1994V2.Primitives.jobDestructionResidual
#check MP1994V2.Primitives.SatisfiesJobDestructionMeasure
#check MP1994V2.Primitives.SatisfiesJobDestruction
#check MP1994V2.ValueEquilibrium.search_gain_eq
#check MP1994V2.ValueEquilibrium.equation10_measure
#check MP1994V2.ValueEquilibrium.equation10
#check MP1994V2.ValueEquilibrium.satisfiesJobDestructionMeasure
#check MP1994V2.ValueEquilibrium.satisfiesJobDestruction
#check MP1994V2.Primitives.jobCreationResidual
#check MP1994V2.Primitives.SatisfiesJobCreation
#check MP1994V2.ValueEquilibrium.job_creation_product_identity
#check MP1994V2.ValueEquilibrium.equation13
#check MP1994V2.ValueEquilibrium.satisfiesJobCreation
#check MP1994V2.ValueEquilibrium.milestone3_capstone
#check MP1994V2.Primitives.SatisfiesJobCreationProduct
#check MP1994V2.ReducedEquilibrium
#check MP1994V2.ReducedEquilibrium.cutoff_le_epsUpper
#check MP1994V2.ReducedEquilibrium.epsUpper_sub_cutoff_pos
#check MP1994V2.ReducedEquilibrium.epsUpper_sub_cutoff_ne
#check MP1994V2.ReducedEquilibrium.ext
#check MP1994V2.Primitives.positivePart_sub_integrable
#check MP1994V2.Primitives.expectedExcess_eq_tailOptionValue
#check MP1994V2.ReducedEquilibrium.expectedExcess_eq_tailOptionValue
#check MP1994V2.ReducedEquilibrium.equation10_measure
#check MP1994V2.ReducedEquilibrium.equation10
#check MP1994V2.ReducedEquilibrium.equation13
#check MP1994V2.ReducedEquilibrium.satisfiesJobDestruction
#check MP1994V2.ReducedEquilibrium.satisfiesJobCreation
#check MP1994V2.ValueEquilibrium.satisfiesJobCreationProduct
#check MP1994V2.ValueEquilibrium.toReducedEquilibrium
#check MP1994V2.ValueEquilibrium.toReducedEquilibrium_theta
#check MP1994V2.ValueEquilibrium.toReducedEquilibrium_cutoff
#check MP1994V2.ValueEquilibrium.toReducedEquilibrium_satisfies_paper_conditions
#check MP1994V2.ReducedEquilibrium.surplusCandidate
#check MP1994V2.ReducedEquilibrium.vacancyValueCandidate
#check MP1994V2.ReducedEquilibrium.firmValueCandidate
#check MP1994V2.ReducedEquilibrium.unemploymentValueCandidate
#check MP1994V2.ReducedEquilibrium.workerValueCandidate
#check MP1994V2.ReducedEquilibrium.wageCandidate
#check MP1994V2.ReducedEquilibrium.toValueCandidate
#check MP1994V2.ReducedEquilibrium.toValueCandidate_theta
#check MP1994V2.ReducedEquilibrium.toValueCandidate_surplus
#check MP1994V2.ReducedEquilibrium.toValueCandidate_activeSurplus
#check MP1994V2.ReducedEquilibrium.activeSurplus_integrable
#check MP1994V2.ReducedEquilibrium.search_gain_eq
#check MP1994V2.ReducedEquilibrium.vacancy_meeting_mul_firm_value_eq_cost
#check MP1994V2.ReducedEquilibrium.wage_search_term_eq
#check MP1994V2.ReducedEquilibrium.integral_activeSurplus_eq
#check MP1994V2.ReducedEquilibrium.surplus_bellman
#check MP1994V2.ReducedEquilibrium.continuation_eq
#check MP1994V2.ReducedEquilibrium.vacancy_bellman
#check MP1994V2.ReducedEquilibrium.free_entry
#check MP1994V2.ReducedEquilibrium.nash_sharing
#check MP1994V2.ReducedEquilibrium.unemployed_bellman
#check MP1994V2.ReducedEquilibrium.worker_bellman
#check MP1994V2.ReducedEquilibrium.filled_job_bellman
#check MP1994V2.ReducedEquilibrium.toValueEquilibrium
#check MP1994V2.ReducedEquilibrium.toValueEquilibrium_theta
#check MP1994V2.ReducedEquilibrium.toValueEquilibrium_surplus
#check MP1994V2.ReducedEquilibrium.toValueEquilibrium_reservationCutoff
#check MP1994V2.ReducedEquilibrium.toValue_toReduced
#check MP1994V2.ValueEquilibrium.wage_eq_nash_formula
#check MP1994V2.ValueEquilibrium.reconstructed_surplus_eq
#check MP1994V2.ValueEquilibrium.reconstruction_components
#check MP1994V2.ValueEquilibrium.reconstruction_economic_roundtrip
#check MP1994V2.valueEquilibrium_nonempty_iff_reducedEquilibrium_nonempty
#check MP1994V2.exists_valueEquilibrium_iff_exists_reducedEquilibrium
#check MP1994V2.m4_representation_capstone

assert_no_sorry MP1994V2.Primitives.workerMeetingRate_pos
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_eq
assert_no_sorry MP1994V2.continuationTerm_eq_integral_activeSurplus_sub
assert_no_sorry MP1994V2.ValueEquilibrium.firm_share
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_flow_equation
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_bellman_of_probability
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_bellman
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_difference_scaled_of_probability
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_difference
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_strictMono
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_reservationCutoff_eq_zero
assert_no_sorry MP1994V2.ValueEquilibrium.existsUnique_surplus_zero
assert_no_sorry MP1994V2.ValueEquilibrium.vacancy_value_eq_zero
assert_no_sorry MP1994V2.ValueEquilibrium.upper_firm_value_pos
assert_no_sorry MP1994V2.ValueEquilibrium.upper_surplus_pos
assert_no_sorry MP1994V2.ValueEquilibrium.reservationCutoff_lt_epsUpper
assert_no_sorry MP1994V2.ValueEquilibrium.equation12
assert_no_sorry MP1994V2.ValueEquilibrium.surplus_neg_iff_lt_reservationCutoff
assert_no_sorry MP1994V2.ValueEquilibrium.firm_value_neg_iff_lt_reservationCutoff
assert_no_sorry MP1994V2.ValueEquilibrium.activeSurplus_eq_slope_mul_positivePart
assert_no_sorry MP1994V2.ValueEquilibrium.milestone2_capstone
assert_no_sorry MP1994V2.ValueEquilibrium.positivePart_sub_cutoff_integrable
assert_no_sorry MP1994V2.Primitives.measureReal_Ioi_eq_one_sub_cdf
assert_no_sorry MP1994V2.ValueEquilibrium.expectedExcess_cutoff_eq_tailOptionValue
assert_no_sorry MP1994V2.ValueEquilibrium.integral_activeSurplus_eq_slope_mul_expectedExcess
assert_no_sorry MP1994V2.ValueEquilibrium.equation9_measure
assert_no_sorry MP1994V2.ValueEquilibrium.equation9
assert_no_sorry MP1994V2.ValueEquilibrium.search_gain_eq
assert_no_sorry MP1994V2.ValueEquilibrium.equation10_measure
assert_no_sorry MP1994V2.ValueEquilibrium.equation10
assert_no_sorry MP1994V2.ValueEquilibrium.satisfiesJobDestruction
assert_no_sorry MP1994V2.ValueEquilibrium.job_creation_product_identity
assert_no_sorry MP1994V2.ValueEquilibrium.equation13
assert_no_sorry MP1994V2.ValueEquilibrium.satisfiesJobCreation
assert_no_sorry MP1994V2.ValueEquilibrium.milestone3_capstone
assert_no_sorry MP1994V2.Primitives.positivePart_sub_integrable
assert_no_sorry MP1994V2.Primitives.expectedExcess_eq_tailOptionValue
assert_no_sorry MP1994V2.ReducedEquilibrium.equation10
assert_no_sorry MP1994V2.ReducedEquilibrium.equation13
assert_no_sorry MP1994V2.ValueEquilibrium.toReducedEquilibrium
assert_no_sorry MP1994V2.ReducedEquilibrium.toValueCandidate_surplus
assert_no_sorry MP1994V2.ReducedEquilibrium.activeSurplus_integrable
assert_no_sorry MP1994V2.ReducedEquilibrium.search_gain_eq
assert_no_sorry MP1994V2.ReducedEquilibrium.surplus_bellman
assert_no_sorry MP1994V2.ReducedEquilibrium.vacancy_bellman
assert_no_sorry MP1994V2.ReducedEquilibrium.filled_job_bellman
assert_no_sorry MP1994V2.ReducedEquilibrium.worker_bellman
assert_no_sorry MP1994V2.ReducedEquilibrium.unemployed_bellman
assert_no_sorry MP1994V2.ReducedEquilibrium.toValueEquilibrium
assert_no_sorry MP1994V2.ReducedEquilibrium.toValueEquilibrium_reservationCutoff
assert_no_sorry MP1994V2.ReducedEquilibrium.toValue_toReduced
assert_no_sorry MP1994V2.ValueEquilibrium.wage_eq_nash_formula
assert_no_sorry MP1994V2.ValueEquilibrium.reconstruction_components
assert_no_sorry MP1994V2.ValueEquilibrium.reconstruction_economic_roundtrip
assert_no_sorry MP1994V2.valueEquilibrium_nonempty_iff_reducedEquilibrium_nonempty
assert_no_sorry MP1994V2.m4_representation_capstone

#print axioms MP1994V2.Primitives.workerMeetingRate_pos
#print axioms MP1994V2.ValueEquilibrium.surplus_eq
#print axioms MP1994V2.ValueEquilibrium.surplus_bellman_of_probability
#print axioms MP1994V2.ValueEquilibrium.surplus_bellman
#print axioms MP1994V2.ValueEquilibrium.equation12
#print axioms MP1994V2.ValueEquilibrium.existsUnique_surplus_zero
#print axioms MP1994V2.ValueEquilibrium.reservationCutoff_is_admissible
#print axioms MP1994V2.ValueEquilibrium.activeSurplus_eq_slope_mul_positivePart
#print axioms MP1994V2.ValueEquilibrium.milestone2_capstone
#print axioms MP1994V2.ValueEquilibrium.expectedExcess_cutoff_eq_tailOptionValue
#print axioms MP1994V2.ValueEquilibrium.equation9
#print axioms MP1994V2.ValueEquilibrium.equation10
#print axioms MP1994V2.ValueEquilibrium.equation13
#print axioms MP1994V2.ValueEquilibrium.milestone3_capstone
#print axioms MP1994V2.Primitives.expectedExcess_eq_tailOptionValue
#print axioms MP1994V2.ReducedEquilibrium.toValueEquilibrium
#print axioms MP1994V2.ReducedEquilibrium.toValueEquilibrium_reservationCutoff
#print axioms MP1994V2.ReducedEquilibrium.toValue_toReduced
#print axioms MP1994V2.ValueEquilibrium.reconstruction_components
#print axioms MP1994V2.ValueEquilibrium.reconstruction_economic_roundtrip
#print axioms MP1994V2.valueEquilibrium_nonempty_iff_reducedEquilibrium_nonempty
#print axioms MP1994V2.m4_representation_capstone
