import Lean4Tutorial.i003_replicate_aiyagari.DynamicProgramming

/-!
# The bounded continuous-state Aiyagari Bellman problem

The state is excess resources in the nonnegative reals.  The compact action is
a saving share in [0,1], and the compact shock space is the support interval
of the primitive labor law.
-/

open Filter MeasureTheory Set Topology
open scoped ENNReal NNReal ProbabilityTheory Topology

namespace Aiyagari1994

noncomputable section

/-- The labor law viewed as a probability measure on its stated support. -/
def laborSupportProbability (M : HouseholdPrimitives)
    (hM : HouseholdAssumptions M) : ProbabilityMeasure (LaborSupportState M) := by
  refine ⟨laborSupportMeasure M, IsProbabilityMeasure.mk ?_⟩
  rw [laborSupportMeasure, comap_subtype_coe_apply measurableSet_Icc]
  rw [show Subtype.val '' (Set.univ : Set (LaborSupportState M)) =
      Icc M.lmin M.lmax by
    ext x
    simp only [mem_image, mem_Icc]
    constructor
    · rintro ⟨y, -, hy⟩
      rw [← hy]
      exact y.property
    · intro hx
      exact ⟨⟨x, hx⟩, Set.mem_univ _, rfl⟩]
  exact hM.labor_support

/-- Consumption generated by excess resources and a saving share. -/
def shareConsumption (M : HouseholdPrimitives) (φ : ℝ)
    (p : ExcessResource × SavingShare) : ℝ :=
  resourceLevel M φ p.1 * (1 - (p.2 : ℝ))

theorem shareConsumption_nonneg (M : HouseholdPrimitives) (φ : ℝ)
    (hφ : BorrowingLimitAdmissible M φ)
    (p : ExcessResource × SavingShare) : 0 ≤ shareConsumption M φ p := by
  apply mul_nonneg
  · exact add_nonneg hφ.minimumResources_nonneg p.1.property
  · exact sub_nonneg.mpr p.2.property.2

/-- Next excess resources, with a harmless nonnegative clipping outside the
economic support.  On admissible labor shocks the expression inside max is
already nonnegative. -/
def shareNextExcess (M : HouseholdPrimitives) (φ : ℝ)
    (q : (ExcessResource × SavingShare) × LaborSupportState M) :
    ExcessResource :=
  ⟨max 0 ((1 + M.r) * (q.1.2 : ℝ) * resourceLevel M φ q.1.1 +
      M.w * ((q.2 : ℝ) - M.lmin)), le_max_left _ _⟩

theorem continuous_shareNextExcess (M : HouseholdPrimitives) (φ : ℝ) :
    Continuous (shareNextExcess M φ) := by
  exact Continuous.subtype_mk (by
    unfold resourceLevel minimumResources
    fun_prop) _

/-- The bounded continuous current-return function on state-action pairs. -/
def boundedAiyagariReward (M : HouseholdPrimitives) (φ : ℝ)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) :
    BoundedContinuousFunction (ExcessResource × SavingShare) ℝ := by
  let umin := Classical.choose hU.lower_bound
  have humin := Classical.choose_spec hU.lower_bound
  let umax := Classical.choose hU.upper_bound
  have humax := Classical.choose_spec hU.upper_bound
  exact BoundedContinuousFunction.ofNormedAddCommGroup
    (fun p => M.utility (shareConsumption M φ p))
    (hU.continuousOn.comp_continuous (by
      unfold shareConsumption resourceLevel minimumResources
      fun_prop) (fun p => shareConsumption_nonneg M φ hφ p))
    (max |umin| |umax|)
    (fun p => by
      rw [Real.norm_eq_abs]
      exact abs_le_max_abs_abs
        (humin _ (shareConsumption_nonneg M φ hφ p))
        (humax _ (shareConsumption_nonneg M φ hφ p)))

/-- The continuous resource transition used by the generic Bellman theorem. -/
def aiyagariTransition (M : HouseholdPrimitives) (φ : ℝ) :
    C(((ExcessResource × SavingShare) × LaborSupportState M), ExcessResource) :=
  ⟨shareNextExcess M φ, continuous_shareNextExcess M φ⟩

/-- The concrete bounded Aiyagari Bellman operator. -/
def boundedAiyagariBellman (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (V : BoundedContinuousFunction ExcessResource ℝ) :
    BoundedContinuousFunction ExcessResource ℝ :=
  continuousBellmanOperator
    (laborSupportProbability M hM : Measure (LaborSupportState M))
    M.β (boundedAiyagariReward M φ hφ hU)
    (aiyagariTransition M φ) V

/-- The state-action objective whose compact maximum defines the Bellman
operator. -/
def boundedAiyagariObjective (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (V : BoundedContinuousFunction ExcessResource ℝ) :
    BoundedContinuousFunction (ExcessResource × SavingShare) ℝ :=
  boundedAiyagariReward M φ hφ hU + M.β •
    expectedContinuationBCF
      (laborSupportProbability M hM : Measure (LaborSupportState M))
      (aiyagariTransition M φ) V

/-- The same Bellman objective expressed in the paper's shifted-asset choice
instead of a saving share.  It is defined on all real choices using the same
nonnegative clipping as the share formulation; on the feasible interval the
clipping is inactive. -/
def boundedAssetObjective (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (V : BoundedContinuousFunction ExcessResource ℝ)
    (z ahat : ℝ) : ℝ :=
  M.utility (z - ahat) + M.β *
    ∫ l : LaborSupportState M,
      V ⟨max 0 ((1 + M.r) * ahat + M.w * ((l : ℝ) - M.lmin)),
        le_max_left _ _⟩
      ∂(laborSupportProbability M hM : Measure (LaborSupportState M))

/-- Extend a value on nonnegative excess resources to the real line by
clipping the argument at zero. -/
def liftedExcessValue
    (V : BoundedContinuousFunction ExcessResource ℝ) (x : ℝ) : ℝ :=
  V ⟨max 0 x, le_max_left _ _⟩

/-- Concavity of a value function on the economically relevant nonnegative
excess-resource domain. -/
def ConcaveExcessValue
    (V : BoundedContinuousFunction ExcessResource ℝ) : Prop :=
  ConcaveOn ℝ (Ici (0 : ℝ)) (liftedExcessValue V)

/-- Expected continuation value as a function of the shifted asset choice. -/
def boundedAssetContinuation (M : HouseholdPrimitives)
    (hM : HouseholdAssumptions M)
    (V : BoundedContinuousFunction ExcessResource ℝ) (ahat : ℝ) : ℝ :=
  ∫ l : LaborSupportState M,
    liftedExcessValue V
      ((1 + M.r) * ahat + M.w * ((l : ℝ) - M.lmin))
    ∂(laborSupportProbability M hM : Measure (LaborSupportState M))

lemma boundedAssetObjective_eq_utility_add_continuation
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (V : BoundedContinuousFunction ExcessResource ℝ) (z ahat : ℝ) :
    boundedAssetObjective M φ hM V z ahat =
      M.utility (z - ahat) + M.β * boundedAssetContinuation M hM V ahat :=
  rfl

lemma boundedAssetContinuation_integrable
    (M : HouseholdPrimitives) (hM : HouseholdAssumptions M)
    (V : BoundedContinuousFunction ExcessResource ℝ) (ahat : ℝ) :
    Integrable (fun l : LaborSupportState M =>
      liftedExcessValue V
        ((1 + M.r) * ahat + M.w * ((l : ℝ) - M.lmin)))
      (laborSupportProbability M hM : Measure (LaborSupportState M)) := by
  apply Integrable.of_bound
  · apply Continuous.aestronglyMeasurable
    unfold liftedExcessValue
    exact V.continuous.comp (Continuous.subtype_mk (by fun_prop) _)
  · filter_upwards with l
    exact BoundedContinuousFunction.norm_coe_le_norm V _

/-- If the continuation value is concave, expectation preserves concavity in
the shifted asset choice on the nonnegative half-line. -/
lemma boundedAssetContinuation_concave_combo
    (M : HouseholdPrimitives) (hM : HouseholdAssumptions M)
    (V : BoundedContinuousFunction ExcessResource ℝ)
    (hV : ConcaveExcessValue V)
    {a b p q : ℝ} (ha : 0 ≤ a) (hb : 0 ≤ b)
    (hp : 0 ≤ p) (hq : 0 ≤ q) (hpq : p + q = 1) :
    p * boundedAssetContinuation M hM V a +
        q * boundedAssetContinuation M hM V b ≤
      boundedAssetContinuation M hM V (p * a + q * b) := by
  let μ : Measure (LaborSupportState M) := laborSupportProbability M hM
  let f : ℝ → LaborSupportState M → ℝ := fun d l =>
    liftedExcessValue V
      ((1 + M.r) * d + M.w * ((l : ℝ) - M.lmin))
  have hR : 0 ≤ 1 + M.r := by linarith [hM.r_pos]
  have hpoint : ∀ l : LaborSupportState M,
      p * f a l + q * f b l ≤ f (p * a + q * b) l := by
    intro l
    have hla : 0 ≤ (1 + M.r) * a + M.w * ((l : ℝ) - M.lmin) := by
      exact add_nonneg (mul_nonneg hR ha)
        (mul_nonneg hM.w_pos.le (sub_nonneg.mpr l.property.1))
    have hlb : 0 ≤ (1 + M.r) * b + M.w * ((l : ℝ) - M.lmin) := by
      exact add_nonneg (mul_nonneg hR hb)
        (mul_nonneg hM.w_pos.le (sub_nonneg.mpr l.property.1))
    have hjensen := hV.2 hla hlb hp hq hpq
    dsimp [f, liftedExcessValue] at hjensen ⊢
    simp only [max_eq_right hla, max_eq_right hlb] at hjensen
    have hcombo :
        (1 + M.r) * (p * a + q * b) + M.w * ((l : ℝ) - M.lmin) =
          p * ((1 + M.r) * a + M.w * ((l : ℝ) - M.lmin)) +
          q * ((1 + M.r) * b + M.w * ((l : ℝ) - M.lmin)) := by
      calc
        (1 + M.r) * (p * a + q * b) + M.w * ((l : ℝ) - M.lmin) =
            p * ((1 + M.r) * a) + q * ((1 + M.r) * b) +
              (p + q) * (M.w * ((l : ℝ) - M.lmin)) := by
                rw [hpq]
                ring
        _ = p * ((1 + M.r) * a + M.w * ((l : ℝ) - M.lmin)) +
              q * ((1 + M.r) * b + M.w * ((l : ℝ) - M.lmin)) := by
                ring
    rw [hcombo]
    simpa only [max_eq_right hla, max_eq_right hlb] using hjensen
  have hinta := boundedAssetContinuation_integrable M hM V a
  have hintb := boundedAssetContinuation_integrable M hM V b
  have hintc := boundedAssetContinuation_integrable M hM V (p * a + q * b)
  change p * ∫ l, f a l ∂μ + q * ∫ l, f b l ∂μ ≤
    ∫ l, f (p * a + q * b) l ∂μ
  rw [← integral_const_mul, ← integral_const_mul, ← integral_add
    (hinta.const_mul p) (hintb.const_mul q)]
  apply integral_mono_ae (hinta.const_mul p |>.add (hintb.const_mul q)) hintc
  exact Eventually.of_forall hpoint

/-- Saving shares and shifted-asset choices give exactly the same objective. -/
lemma boundedAiyagariObjective_eq_assetObjective
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (V : BoundedContinuousFunction ExcessResource ℝ)
    (x : ExcessResource) (s : SavingShare) :
    boundedAiyagariObjective M φ hM hφ hU V (x, s) =
      boundedAssetObjective M φ hM V (resourceLevel M φ x)
        ((s : ℝ) * resourceLevel M φ x) := by
  change M.utility (shareConsumption M φ (x, s)) + M.β *
      ∫ l : LaborSupportState M, V (shareNextExcess M φ ((x, s), l))
        ∂(laborSupportProbability M hM : Measure (LaborSupportState M)) = _
  unfold boundedAssetObjective shareConsumption shareNextExcess
  congr 2
  · ring
  · apply integral_congr_ae
    filter_upwards with l
    congr 2
    ring

/-- A maximizing share for an arbitrary bounded continuation value. -/
def boundedAiyagariPolicyFor (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (V : BoundedContinuousFunction ExcessResource ℝ)
    (x : ExcessResource) : SavingShare :=
  Classical.choose
    (exists_compactMaximum_eq
      (ContinuousMap.curry
        (boundedAiyagariObjective M φ hM hφ hU V).toContinuousMap x))

lemma boundedAiyagariPolicyFor_isMax
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (V : BoundedContinuousFunction ExcessResource ℝ)
    (x : ExcessResource) (a : SavingShare) :
    boundedAiyagariObjective M φ hM hφ hU V (x, a) ≤
      boundedAiyagariObjective M φ hM hφ hU V
        (x, boundedAiyagariPolicyFor M φ hM hφ hU V x) := by
  let Q := boundedAiyagariObjective M φ hM hφ hU V
  have hchoice := Classical.choose_spec
    (exists_compactMaximum_eq (ContinuousMap.curry Q.toContinuousMap x))
  calc
    boundedAiyagariObjective M φ hM hφ hU V (x, a) ≤
        compactMaximum (ContinuousMap.curry Q.toContinuousMap x) :=
      by simpa [Q] using
        (compactMaximum_le (ContinuousMap.curry Q.toContinuousMap x) a)
    _ = boundedAiyagariObjective M φ hM hφ hU V
        (x, boundedAiyagariPolicyFor M φ hM hφ hU V x) := by
      simpa [Q, boundedAiyagariPolicyFor] using hchoice

/-- Shifted assets selected by the maximizing share. -/
def boundedOptimalAssetFor (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (V : BoundedContinuousFunction ExcessResource ℝ)
    (x : ExcessResource) : ℝ :=
  (boundedAiyagariPolicyFor M φ hM hφ hU V x : ℝ) *
    resourceLevel M φ x

lemma boundedOptimalAssetFor_mem
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (V : BoundedContinuousFunction ExcessResource ℝ)
    (x : ExcessResource) :
    boundedOptimalAssetFor M φ hM hφ hU V x ∈
      Icc 0 (resourceLevel M φ x) := by
  have hz : 0 ≤ resourceLevel M φ x :=
    add_nonneg hφ.minimumResources_nonneg x.property
  have hs := (boundedAiyagariPolicyFor M φ hM hφ hU V x).property
  exact ⟨mul_nonneg hs.1 hz, (mul_le_mul_of_nonneg_right hs.2 hz).trans_eq (one_mul _)⟩

/-- Every shifted asset in `[0,z]` is represented by a saving share when
`z≥0`; at `z=0` all feasible asset choices coincide. -/
lemma exists_savingShare_mul_eq
    {z a : ℝ} (hz : 0 ≤ z) (ha : a ∈ Icc (0 : ℝ) z) :
    ∃ s : SavingShare, (s : ℝ) * z = a := by
  by_cases hz0 : z = 0
  · have ha0 : a = 0 := le_antisymm (by simpa [hz0] using ha.2) ha.1
    exact ⟨⟨0, by norm_num⟩, by simp [ha0]⟩
  · have hzpos : 0 < z := lt_of_le_of_ne hz (Ne.symm hz0)
    refine ⟨⟨a / z, ?_⟩, ?_⟩
    · exact ⟨div_nonneg ha.1 hz, (div_le_one hzpos).2 ha.2⟩
    · exact div_mul_cancel₀ a hz0

lemma boundedAssetObjective_le_optimalAsset
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (V : BoundedContinuousFunction ExcessResource ℝ)
    (x : ExcessResource) {a : ℝ}
    (ha : a ∈ Icc 0 (resourceLevel M φ x)) :
    boundedAssetObjective M φ hM V (resourceLevel M φ x) a ≤
      boundedAssetObjective M φ hM V (resourceLevel M φ x)
        (boundedOptimalAssetFor M φ hM hφ hU V x) := by
  have hz : 0 ≤ resourceLevel M φ x :=
    add_nonneg hφ.minimumResources_nonneg x.property
  obtain ⟨s, hs⟩ := exists_savingShare_mul_eq hz ha
  have hmax := boundedAiyagariPolicyFor_isMax M φ hM hφ hU V x s
  rw [boundedAiyagariObjective_eq_assetObjective M φ hM hφ hU V x s] at hmax
  rw [boundedAiyagariObjective_eq_assetObjective M φ hM hφ hU V x
    (boundedAiyagariPolicyFor M φ hM hφ hU V x)] at hmax
  rw [hs] at hmax
  simpa [boundedOptimalAssetFor] using hmax

lemma boundedAiyagariBellman_apply_eq_optimalAsset
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (V : BoundedContinuousFunction ExcessResource ℝ)
    (x : ExcessResource) :
    boundedAiyagariBellman M φ hM hφ hU V x =
      boundedAssetObjective M φ hM V (resourceLevel M φ x)
        (boundedOptimalAssetFor M φ hM hφ hU V x) := by
  let Q := boundedAiyagariObjective M φ hM hφ hU V
  have hchoice := Classical.choose_spec
    (exists_compactMaximum_eq (ContinuousMap.curry Q.toContinuousMap x))
  change compactMaximum (ContinuousMap.curry Q.toContinuousMap x) = _
  rw [hchoice]
  exact boundedAiyagariObjective_eq_assetObjective M φ hM hφ hU V x
    (boundedAiyagariPolicyFor M φ hM hφ hU V x)

/-- Joint concavity inequality for the asset-form Bellman objective on its
feasible graph. -/
lemma boundedAssetObjective_combo
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hU : BoundedFiniteUtility M)
    (V : BoundedContinuousFunction ExcessResource ℝ)
    (hV : ConcaveExcessValue V)
    {z₁ z₂ a₁ a₂ p q : ℝ}
    (ha₁ : a₁ ∈ Icc 0 z₁) (ha₂ : a₂ ∈ Icc 0 z₂)
    (hp : 0 ≤ p) (hq : 0 ≤ q) (hpq : p + q = 1) :
    p * boundedAssetObjective M φ hM V z₁ a₁ +
        q * boundedAssetObjective M φ hM V z₂ a₂ ≤
      boundedAssetObjective M φ hM V
        (p * z₁ + q * z₂) (p * a₁ + q * a₂) := by
  have hc₁ : z₁ - a₁ ∈ Ici (0 : ℝ) := sub_nonneg.mpr ha₁.2
  have hc₂ : z₂ - a₂ ∈ Ici (0 : ℝ) := sub_nonneg.mpr ha₂.2
  have hu := hU.strictConcaveOn.concaveOn.2 hc₁ hc₂ hp hq hpq
  have hcont := boundedAssetContinuation_concave_combo M hM V hV
    ha₁.1 ha₂.1 hp hq hpq
  have hβcont := mul_le_mul_of_nonneg_left hcont hM.β_pos.le
  simp only [boundedAssetObjective_eq_utility_add_continuation]
  calc
    p * (M.utility (z₁ - a₁) + M.β * boundedAssetContinuation M hM V a₁) +
        q * (M.utility (z₂ - a₂) + M.β * boundedAssetContinuation M hM V a₂) =
      (p * M.utility (z₁ - a₁) + q * M.utility (z₂ - a₂)) +
        M.β * (p * boundedAssetContinuation M hM V a₁ +
          q * boundedAssetContinuation M hM V a₂) := by ring
    _ ≤ M.utility (p * (z₁ - a₁) + q * (z₂ - a₂)) +
        M.β * boundedAssetContinuation M hM V (p * a₁ + q * a₂) :=
      add_le_add hu hβcont
    _ = M.utility (p * z₁ + q * z₂ - (p * a₁ + q * a₂)) +
        M.β * boundedAssetContinuation M hM V (p * a₁ + q * a₂) := by
      ring

/-- The concrete Bellman map preserves concavity; no policy-shape hypothesis
is supplied. -/
theorem boundedAiyagariBellman_preserves_concavity
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (V : BoundedContinuousFunction ExcessResource ℝ)
    (hV : ConcaveExcessValue V) :
    ConcaveExcessValue (boundedAiyagariBellman M φ hM hφ hU V) := by
  refine ⟨convex_Ici (0 : ℝ), ?_⟩
  intro x hx y hy p q hp hq hpq
  have hx0 : 0 ≤ x := hx
  have hy0 : 0 ≤ y := hy
  let X : ExcessResource := ⟨x, hx0⟩
  let Y : ExcessResource := ⟨y, hy0⟩
  have hxy : 0 ≤ p * x + q * y := add_nonneg (mul_nonneg hp hx0) (mul_nonneg hq hy0)
  let XY : ExcessResource := ⟨p * x + q * y, hxy⟩
  let a₁ := boundedOptimalAssetFor M φ hM hφ hU V X
  let a₂ := boundedOptimalAssetFor M φ hM hφ hU V Y
  have ha₁ := boundedOptimalAssetFor_mem M φ hM hφ hU V X
  have ha₂ := boundedOptimalAssetFor_mem M φ hM hφ hU V Y
  have hzcombo :
      p * resourceLevel M φ X + q * resourceLevel M φ Y =
        resourceLevel M φ XY := by
    unfold resourceLevel
    dsimp [X, Y, XY]
    calc
      p * (minimumResources M.w M.lmin M.r φ + x) +
          q * (minimumResources M.w M.lmin M.r φ + y) =
        (p + q) * minimumResources M.w M.lmin M.r φ +
          (p * x + q * y) := by ring
      _ = minimumResources M.w M.lmin M.r φ + (p * x + q * y) := by
        rw [hpq]
        ring
  have hacombo : p * a₁ + q * a₂ ∈
      Icc 0 (resourceLevel M φ XY) := by
    constructor
    · exact add_nonneg (mul_nonneg hp ha₁.1) (mul_nonneg hq ha₂.1)
    · rw [← hzcombo]
      exact add_le_add
        (mul_le_mul_of_nonneg_left ha₁.2 hp)
        (mul_le_mul_of_nonneg_left ha₂.2 hq)
  have hjoint := boundedAssetObjective_combo M φ hM hU V hV
    ha₁ ha₂ hp hq hpq
  rw [hzcombo] at hjoint
  have hmax := boundedAssetObjective_le_optimalAsset M φ hM hφ hU V XY hacombo
  have hX := boundedAiyagariBellman_apply_eq_optimalAsset M φ hM hφ hU V X
  have hY := boundedAiyagariBellman_apply_eq_optimalAsset M φ hM hφ hU V Y
  have hXY := boundedAiyagariBellman_apply_eq_optimalAsset M φ hM hφ hU V XY
  have hfinal : p * boundedAiyagariBellman M φ hM hφ hU V X +
      q * boundedAiyagariBellman M φ hM hφ hU V Y ≤
      boundedAiyagariBellman M φ hM hφ hU V XY := by
    rw [hX, hY, hXY]
    exact hjoint.trans hmax
  simpa [liftedExcessValue, max_eq_right hx0, max_eq_right hy0,
    max_eq_right hxy, X, Y, XY] using hfinal

lemma concaveExcessValue_zero :
    ConcaveExcessValue (0 : BoundedContinuousFunction ExcessResource ℝ) := by
  refine ⟨convex_Ici (0 : ℝ), ?_⟩
  intro x hx y hy p q hp hq hpq
  change p * 0 + q * 0 ≤ (0 : ℝ)
  norm_num

lemma boundedAiyagariBellman_iterate_concave
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) :
    ∀ n : ℕ, ConcaveExcessValue
      ((boundedAiyagariBellman M φ hM hφ hU)^[n]
        (0 : BoundedContinuousFunction ExcessResource ℝ)) := by
  intro n
  induction n with
  | zero => simpa using concaveExcessValue_zero
  | succ n ih =>
      rw [Function.iterate_succ_apply']
      exact boundedAiyagariBellman_preserves_concavity M φ hM hφ hU _ ih

/-- Property 2's bounded value function is obtained from Banach's theorem, not
accepted as an input. -/
def boundedAiyagariValue (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) :
    BoundedContinuousFunction ExcessResource ℝ :=
  boundedBellmanValue
    (laborSupportProbability M hM : Measure (LaborSupportState M))
    M.β hM.β_pos.le hM.β_lt_one
    (boundedAiyagariReward M φ hφ hU) (aiyagariTransition M φ)

/-- Bellman-iterate convergence transfers concavity to the unique bounded
value function. -/
theorem boundedAiyagariValue_concave
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) :
    ConcaveExcessValue (boundedAiyagariValue M φ hM hφ hU) := by
  let T := continuousBellmanOperator
    (laborSupportProbability M hM : Measure (LaborSupportState M))
    M.β (boundedAiyagariReward M φ hφ hU) (aiyagariTransition M φ)
  have hcontract := continuousBellmanOperator_contracting
    (laborSupportProbability M hM : Measure (LaborSupportState M))
    M.β hM.β_pos.le hM.β_lt_one
    (boundedAiyagariReward M φ hφ hU) (aiyagariTransition M φ)
  have hconv : Tendsto (fun n : ℕ => T^[n]
      (0 : BoundedContinuousFunction ExcessResource ℝ)) atTop
      (𝓝 (boundedAiyagariValue M φ hM hφ hU)) := by
    simpa [T, boundedAiyagariValue, boundedBellmanValue] using
      hcontract.tendsto_iterate_fixedPoint
        (0 : BoundedContinuousFunction ExcessResource ℝ)
  refine ⟨convex_Ici (0 : ℝ), ?_⟩
  intro x hx y hy p q hp hq hpq
  have hx0 : 0 ≤ x := hx
  have hy0 : 0 ≤ y := hy
  have hxy : 0 ≤ p * x + q * y :=
    add_nonneg (mul_nonneg hp hx0) (mul_nonneg hq hy0)
  let X : ExcessResource := ⟨x, hx0⟩
  let Y : ExcessResource := ⟨y, hy0⟩
  let XY : ExcessResource := ⟨p * x + q * y, hxy⟩
  have hpoint (Z : ExcessResource) :
      Tendsto (fun n : ℕ => (T^[n]
        (0 : BoundedContinuousFunction ExcessResource ℝ)) Z) atTop
        (𝓝 (boundedAiyagariValue M φ hM hφ hU Z)) := by
    exact ((continuous_eval_const Z).tendsto _).comp hconv
  have hleft : Tendsto (fun n : ℕ =>
      p * (T^[n] (0 : BoundedContinuousFunction ExcessResource ℝ)) X +
      q * (T^[n] (0 : BoundedContinuousFunction ExcessResource ℝ)) Y)
      atTop (𝓝 (p * boundedAiyagariValue M φ hM hφ hU X +
        q * boundedAiyagariValue M φ hM hφ hU Y)) :=
    (tendsto_const_nhds.mul (hpoint X)).add
      (tendsto_const_nhds.mul (hpoint Y))
  have hright : Tendsto (fun n : ℕ =>
      (T^[n] (0 : BoundedContinuousFunction ExcessResource ℝ)) XY)
      atTop (𝓝 (boundedAiyagariValue M φ hM hφ hU XY)) := hpoint XY
  have hineq : ∀ n : ℕ,
      p * (T^[n] (0 : BoundedContinuousFunction ExcessResource ℝ)) X +
        q * (T^[n] (0 : BoundedContinuousFunction ExcessResource ℝ)) Y ≤
      (T^[n] (0 : BoundedContinuousFunction ExcessResource ℝ)) XY := by
    intro n
    have hnConc := boundedAiyagariBellman_iterate_concave M φ hM hφ hU n
    change ConcaveExcessValue
      (T^[n] (0 : BoundedContinuousFunction ExcessResource ℝ)) at hnConc
    have hn := hnConc.2 hx hy hp hq hpq
    simpa [liftedExcessValue, max_eq_right hx0, max_eq_right hy0,
      max_eq_right hxy, X, Y, XY] using hn
  have hlimit := le_of_tendsto_of_tendsto hleft hright (Eventually.of_forall hineq)
  simpa [liftedExcessValue, max_eq_right hx0, max_eq_right hy0,
    max_eq_right hxy, X, Y, XY] using hlimit

/-- At every resource level, strict concavity of utility and concavity of the
solved continuation value make the shifted-asset objective strictly concave. -/
theorem boundedAssetObjective_strictConcave
    (M : HouseholdPrimitives) (φ z : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (hz : 0 ≤ z) :
    StrictConcaveOn ℝ (Icc 0 z)
      (boundedAssetObjective M φ hM
        (boundedAiyagariValue M φ hM hφ hU) z) := by
  let V := boundedAiyagariValue M φ hM hφ hU
  refine ⟨convex_Icc 0 z, ?_⟩
  intro a ha b hb hab p q hp hq hpq
  have hca : z - a ∈ Ici (0 : ℝ) := sub_nonneg.mpr ha.2
  have hcb : z - b ∈ Ici (0 : ℝ) := sub_nonneg.mpr hb.2
  have hneq : z - a ≠ z - b := by
    intro heq
    apply hab
    linarith
  have hu := hU.strictConcaveOn.2 hca hcb hneq hp hq hpq
  have hcont := boundedAssetContinuation_concave_combo M hM V
    (boundedAiyagariValue_concave M φ hM hφ hU)
    ha.1 hb.1 hp.le hq.le hpq
  have hβcont := mul_le_mul_of_nonneg_left hcont hM.β_pos.le
  have harg : p * (z - a) + q * (z - b) =
      z - (p * a + q * b) := by
    calc
      p * (z - a) + q * (z - b) =
          (p + q) * z - (p * a + q * b) := by ring
      _ = z - (p * a + q * b) := by rw [hpq, one_mul]
  simp only [smul_eq_mul, boundedAssetObjective_eq_utility_add_continuation]
  calc
    p * (M.utility (z - a) + M.β * boundedAssetContinuation M hM V a) +
        q * (M.utility (z - b) + M.β * boundedAssetContinuation M hM V b) =
      (p * M.utility (z - a) + q * M.utility (z - b)) +
        M.β * (p * boundedAssetContinuation M hM V a +
          q * boundedAssetContinuation M hM V b) := by ring
    _ < M.utility (p * (z - a) + q * (z - b)) +
        M.β * boundedAssetContinuation M hM V (p * a + q * b) :=
      add_lt_add_of_lt_of_le hu hβcont
    _ = M.utility (z - (p * a + q * b)) +
        M.β * boundedAssetContinuation M hM V (p * a + q * b) := by
      rw [harg]

/-- The shifted-asset optimizer of the solved bounded household problem is
unique.  This theorem derives uniqueness from primitives; it accepts neither
an `ObjectiveConcavity` record nor a uniqueness field. -/
theorem boundedOptimalAsset_unique
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (x : ExcessResource) {a : ℝ}
    (ha : a ∈ Icc 0 (resourceLevel M φ x))
    (hmax : ∀ b ∈ Icc 0 (resourceLevel M φ x),
      boundedAssetObjective M φ hM
          (boundedAiyagariValue M φ hM hφ hU)
          (resourceLevel M φ x) b ≤
        boundedAssetObjective M φ hM
          (boundedAiyagariValue M φ hM hφ hU)
          (resourceLevel M φ x) a) :
    a = boundedOptimalAssetFor M φ hM hφ hU
      (boundedAiyagariValue M φ hM hφ hU) x := by
  have hz : 0 ≤ resourceLevel M φ x :=
    add_nonneg hφ.minimumResources_nonneg x.property
  have hstrict := boundedAssetObjective_strictConcave M φ
    (resourceLevel M φ x) hM hφ hU hz
  have hoptmem := boundedOptimalAssetFor_mem M φ hM hφ hU
    (boundedAiyagariValue M φ hM hφ hU) x
  have hoptmax : ∀ b ∈ Icc 0 (resourceLevel M φ x),
      boundedAssetObjective M φ hM
          (boundedAiyagariValue M φ hM hφ hU)
          (resourceLevel M φ x) b ≤
        boundedAssetObjective M φ hM
          (boundedAiyagariValue M φ hM hφ hU)
          (resourceLevel M φ x)
          (boundedOptimalAssetFor M φ hM hφ hU
            (boundedAiyagariValue M φ hM hφ hU) x) := by
    intro b hb
    exact boundedAssetObjective_le_optimalAsset M φ hM hφ hU _ x hb
  exact hstrict.eq_of_isMaxOn hmax hoptmax ha hoptmem

theorem boundedAiyagariValue_isFixedPoint (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) :
    Function.IsFixedPt (boundedAiyagariBellman M φ hM hφ hU)
      (boundedAiyagariValue M φ hM hφ hU) :=
  boundedBellmanValue_isFixedPoint
    (laborSupportProbability M hM : Measure (LaborSupportState M))
    M.β hM.β_pos.le hM.β_lt_one
    (boundedAiyagariReward M φ hφ hU) (aiyagariTransition M φ)

theorem boundedAiyagariValue_unique (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    {V : BoundedContinuousFunction ExcessResource ℝ}
    (hV : Function.IsFixedPt (boundedAiyagariBellman M φ hM hφ hU) V) :
    V = boundedAiyagariValue M φ hM hφ hU :=
  boundedBellmanValue_unique
    (laborSupportProbability M hM : Measure (LaborSupportState M))
    M.β hM.β_pos.le hM.β_lt_one
    (boundedAiyagariReward M φ hφ hU) (aiyagariTransition M φ) hV

/-- A maximizing saving share at each state, selected only after compact
optimizer existence has been proved. -/
def boundedAiyagariPolicy (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) (x : ExcessResource) : SavingShare :=
  boundedAiyagariPolicyFor M φ hM hφ hU
    (boundedAiyagariValue M φ hM hφ hU) x

/-- The paper's shifted-asset policy generated by the solved bounded problem. -/
def boundedAiyagariAssetPolicy (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) (x : ExcessResource) : ℝ :=
  boundedOptimalAssetFor M φ hM hφ hU
    (boundedAiyagariValue M φ hM hφ hU) x

/-- Consumption generated by the solved bounded household policy. -/
def boundedAiyagariConsumption (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) (x : ExcessResource) : ℝ :=
  resourceLevel M φ x - boundedAiyagariAssetPolicy M φ hM hφ hU x

theorem boundedAiyagariPolicy_isMax (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) (x : ExcessResource) (a : SavingShare) :
    boundedAiyagariObjective M φ hM hφ hU
        (boundedAiyagariValue M φ hM hφ hU) (x, a) ≤
      boundedAiyagariObjective M φ hM hφ hU
        (boundedAiyagariValue M φ hM hφ hU)
        (x, boundedAiyagariPolicy M φ hM hφ hU x) := by
  exact boundedAiyagariPolicyFor_isMax M φ hM hφ hU
    (boundedAiyagariValue M φ hM hφ hU) x a

/-- Berge's maximum-theorem argument specialized to the solved Aiyagari
problem.  Compactness supplies a convergent subsequence of maximizing shares;
continuity passes optimality to its limit, and strict concavity identifies the
unique limiting shifted asset. -/
theorem continuous_boundedAiyagariAssetPolicy
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) :
    Continuous (boundedAiyagariAssetPolicy M φ hM hφ hU) := by
  rw [continuous_iff_seqContinuous]
  intro u x hu
  apply tendsto_of_subseq_tendsto
  intro ns hns
  let sseq : ℕ → SavingShare := fun n =>
    boundedAiyagariPolicy M φ hM hφ hU (u (ns n))
  obtain ⟨sstar, ms, hmsMono, hsstar⟩ := CompactSpace.tendsto_subseq sseq
  have hms : Tendsto ms atTop atTop := hmsMono.tendsto_atTop
  have hstate : Tendsto (fun n => u (ns (ms n))) atTop (𝓝 x) :=
    hu.comp (hns.comp hms)
  let Q := boundedAiyagariObjective M φ hM hφ hU
    (boundedAiyagariValue M φ hM hφ hU)
  have hstarMax : ∀ a : SavingShare, Q (x, a) ≤ Q (x, sstar) := by
    intro a
    have hpairA : Tendsto (fun n => (u (ns (ms n)), a)) atTop
        (𝓝 (x, a)) := by
      simpa only [nhds_prod_eq] using hstate.prodMk tendsto_const_nhds
    have hpairStar : Tendsto (fun n => (u (ns (ms n)), sseq (ms n))) atTop
        (𝓝 (x, sstar)) := by
      simpa only [nhds_prod_eq, Function.comp_apply] using hstate.prodMk hsstar
    have hleft := (Q.continuous.tendsto (x, a)).comp hpairA
    have hright := (Q.continuous.tendsto (x, sstar)).comp hpairStar
    apply le_of_tendsto_of_tendsto hleft hright
    filter_upwards with n
    exact boundedAiyagariPolicy_isMax M φ hM hφ hU (u (ns (ms n))) a
  let z : ℝ := resourceLevel M φ x
  let astar : ℝ := (sstar : ℝ) * z
  have hz : 0 ≤ z := add_nonneg hφ.minimumResources_nonneg x.property
  have hastarMem : astar ∈ Icc (0 : ℝ) z := by
    exact ⟨mul_nonneg sstar.property.1 hz,
      (mul_le_mul_of_nonneg_right sstar.property.2 hz).trans_eq (one_mul z)⟩
  have hastarMax : ∀ b ∈ Icc (0 : ℝ) z,
      boundedAssetObjective M φ hM
          (boundedAiyagariValue M φ hM hφ hU) z b ≤
        boundedAssetObjective M φ hM
          (boundedAiyagariValue M φ hM hφ hU) z astar := by
    intro b hb
    obtain ⟨sb, hsb⟩ := exists_savingShare_mul_eq hz hb
    have hq := hstarMax sb
    change boundedAiyagariObjective M φ hM hφ hU
        (boundedAiyagariValue M φ hM hφ hU) (x, sb) ≤
      boundedAiyagariObjective M φ hM hφ hU
        (boundedAiyagariValue M φ hM hφ hU) (x, sstar) at hq
    rw [boundedAiyagariObjective_eq_assetObjective M φ hM hφ hU _ x sb,
      boundedAiyagariObjective_eq_assetObjective M φ hM hφ hU _ x sstar]
      at hq
    simpa [z, astar, hsb] using hq
  have hastarEq : astar = boundedAiyagariAssetPolicy M φ hM hφ hU x := by
    exact boundedOptimalAsset_unique M φ hM hφ hU x hastarMem hastarMax
  have hshareReal : Tendsto (fun n => (sseq (ms n) : ℝ)) atTop
      (𝓝 (sstar : ℝ)) :=
    (continuous_subtype_val.tendsto sstar).comp hsstar
  have hresource : Tendsto (fun n => resourceLevel M φ (u (ns (ms n)))) atTop
      (𝓝 z) := by
    have hcontinuous : Continuous (fun y : ExcessResource => resourceLevel M φ y) := by
      unfold resourceLevel
      fun_prop
    exact (hcontinuous.tendsto x).comp hstate
  refine ⟨ms, ?_⟩
  have hmul := hshareReal.mul hresource
  have hmul' : Tendsto
      (fun n => (sseq (ms n) : ℝ) * resourceLevel M φ (u (ns (ms n))))
      atTop (𝓝 astar) := by
    simpa [astar] using hmul
  rw [hastarEq] at hmul'
  simpa [Function.comp_def, boundedAiyagariAssetPolicy,
    boundedOptimalAssetFor, boundedAiyagariPolicy, sseq] using hmul'

lemma boundedAiyagariAssetPolicy_mem
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) (x : ExcessResource) :
    boundedAiyagariAssetPolicy M φ hM hφ hU x ∈
      Icc 0 (resourceLevel M φ x) :=
  boundedOptimalAssetFor_mem M φ hM hφ hU
    (boundedAiyagariValue M φ hM hφ hU) x

lemma boundedAiyagariAssetPolicy_isMax
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) (x : ExcessResource)
    {a : ℝ} (ha : a ∈ Icc 0 (resourceLevel M φ x)) :
    boundedAssetObjective M φ hM
        (boundedAiyagariValue M φ hM hφ hU)
        (resourceLevel M φ x) a ≤
      boundedAssetObjective M φ hM
        (boundedAiyagariValue M φ hM hφ hU)
        (resourceLevel M φ x)
        (boundedAiyagariAssetPolicy M φ hM hφ hU x) :=
  boundedAssetObjective_le_optimalAsset M φ hM hφ hU
    (boundedAiyagariValue M φ hM hφ hU) x ha

/-- The fixed-point value equals the Bellman objective evaluated at the
concretely constructed optimal shifted-asset policy. -/
lemma boundedAiyagariValue_eq_optimalAssetObjective
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) (x : ExcessResource) :
    boundedAiyagariValue M φ hM hφ hU x =
      boundedAssetObjective M φ hM
        (boundedAiyagariValue M φ hM hφ hU)
        (resourceLevel M φ x)
        (boundedAiyagariAssetPolicy M φ hM hφ hU x) := by
  let V := boundedAiyagariValue M φ hM hφ hU
  have hfixed := congrArg (fun W : BoundedContinuousFunction ExcessResource ℝ => W x)
    (boundedAiyagariValue_isFixedPoint M φ hM hφ hU)
  have hbell := boundedAiyagariBellman_apply_eq_optimalAsset
    M φ hM hφ hU V x
  change boundedAiyagariBellman M φ hM hφ hU V x = V x at hfixed
  change boundedAiyagariBellman M φ hM hφ hU V x =
    boundedAssetObjective M φ hM V (resourceLevel M φ x)
      (boundedAiyagariAssetPolicy M φ hM hφ hU x) at hbell
  exact hfixed.symm.trans hbell

/-- Holding the optimal asset choice at state `x` fixed produces a feasible
local lower support for the value as current resources vary. -/
def boundedEnvelopeSupport
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) (x : ExcessResource) (y : ℝ) : ℝ :=
  M.utility (minimumResources M.w M.lmin M.r φ + y -
      boundedAiyagariAssetPolicy M φ hM hφ hU x) +
    M.β * boundedAssetContinuation M hM
      (boundedAiyagariValue M φ hM hφ hU)
      (boundedAiyagariAssetPolicy M φ hM hφ hU x)

lemma boundedEnvelopeSupport_touch
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) (x : ExcessResource) :
    boundedEnvelopeSupport M φ hM hφ hU x (x : ℝ) =
      liftedExcessValue (boundedAiyagariValue M φ hM hφ hU) (x : ℝ) := by
  let V := boundedAiyagariValue M φ hM hφ hU
  have hclip :
      (⟨max 0 (x : ℝ), le_max_left _ _⟩ : ExcessResource) = x := by
    apply Subtype.ext
    exact max_eq_right x.property
  change boundedEnvelopeSupport M φ hM hφ hU x (x : ℝ) =
    V ⟨max 0 (x : ℝ), le_max_left _ _⟩
  rw [hclip]
  rw [boundedAiyagariValue_eq_optimalAssetObjective M φ hM hφ hU x]
  simp only [boundedEnvelopeSupport,
    boundedAssetObjective_eq_utility_add_continuation]
  rfl

/-- The envelope equation for the solved bounded household problem.  At an
interior excess-resource state with strictly positive optimal consumption,
concavity and the feasible fixed-action lower support imply
`V'(x) = U'(c(x))`.  No derivative of the policy is assumed. -/
theorem boundedAiyagari_envelope_of_consumption_pos
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) (x : ExcessResource)
    (hx : 0 < (x : ℝ))
    (hc : 0 < resourceLevel M φ x -
      boundedAiyagariAssetPolicy M φ hM hφ hU x) :
    HasDerivAt
      (liftedExcessValue (boundedAiyagariValue M φ hM hφ hU))
      (deriv M.utility (resourceLevel M φ x -
        boundedAiyagariAssetPolicy M φ hM hφ hU x)) (x : ℝ) := by
  let V := boundedAiyagariValue M φ hM hφ hU
  let a := boundedAiyagariAssetPolicy M φ hM hφ hU x
  let c := resourceLevel M φ x - a
  let support := boundedEnvelopeSupport M φ hM hφ hU x
  have hUat : HasDerivAt M.utility (deriv M.utility c) c := by
    exact ((hU.differentiableOn c hc).differentiableAt
      (Ioi_mem_nhds hc)).hasDerivAt
  have hinner : HasDerivAt
      (fun y : ℝ => minimumResources M.w M.lmin M.r φ + y - a) 1 (x : ℝ) := by
    simpa only [sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using
      (hasDerivAt_id' (x : ℝ)).add_const
        (minimumResources M.w M.lmin M.r φ - a)
  have hsupportDeriv : HasDerivAt support (deriv M.utility c) (x : ℝ) := by
    have hcomp := hUat.comp (x : ℝ) hinner
    have hadd := hcomp.add_const
      (M.β * boundedAssetContinuation M hM V a)
    change HasDerivAt
      (fun y : ℝ => M.utility
        (minimumResources M.w M.lmin M.r φ + y - a) +
          M.β * boundedAssetContinuation M hM V a)
      (deriv M.utility c) (x : ℝ)
    simpa only [Function.comp_apply, mul_one] using hadd
  have hlower : ∀ᶠ y in 𝓝 (x : ℝ), support y ≤ liftedExcessValue V y := by
    let δ := min (x : ℝ) c / 2
    have hδ : 0 < δ := div_pos (lt_min hx hc) (by norm_num)
    filter_upwards [Metric.ball_mem_nhds (x : ℝ) hδ] with y hy
    have habs : |y - (x : ℝ)| < δ := by
      simpa [Real.dist_eq] using hy
    have hδx : δ ≤ (x : ℝ) / 2 := by
      dsimp [δ]
      exact div_le_div_of_nonneg_right (min_le_left _ _) (by norm_num)
    have hδc : δ ≤ c / 2 := by
      dsimp [δ]
      exact div_le_div_of_nonneg_right (min_le_right _ _) (by norm_num)
    have hypos : 0 < y := by
      have hlow := (abs_lt.mp habs).1
      linarith
    let Y : ExcessResource := ⟨y, hypos.le⟩
    have ha0 : 0 ≤ a := by
      exact (boundedAiyagariAssetPolicy_mem M φ hM hφ hU x).1
    have hay : a ≤ resourceLevel M φ Y := by
      have hlow := (abs_lt.mp habs).1
      have hcdef : c = minimumResources M.w M.lmin M.r φ + (x : ℝ) - a := by
        rfl
      change a ≤ minimumResources M.w M.lmin M.r φ + y
      linarith
    have hmax := boundedAiyagariAssetPolicy_isMax M φ hM hφ hU Y
      (show a ∈ Icc 0 (resourceLevel M φ Y) from ⟨ha0, hay⟩)
    calc
      support y = boundedAssetObjective M φ hM V
          (resourceLevel M φ Y) a := by
            change M.utility
                (minimumResources M.w M.lmin M.r φ + y - a) +
                M.β * boundedAssetContinuation M hM V a =
              M.utility (resourceLevel M φ Y - a) +
                M.β * boundedAssetContinuation M hM V a
            congr 2
      _ ≤ boundedAssetObjective M φ hM V (resourceLevel M φ Y)
          (boundedAiyagariAssetPolicy M φ hM hφ hU Y) := by
            simpa [V, a] using hmax
      _ = liftedExcessValue V y := by
            rw [← boundedAiyagariValue_eq_optimalAssetObjective
              M φ hM hφ hU Y]
            simp [liftedExcessValue, max_eq_right hypos.le, V, Y]
  exact hasDerivAt_of_concave_local_lowerSupport
    (boundedAiyagariValue_concave M φ hM hφ hU) hx
    (by simpa [c] using hsupportDeriv)
    (by simpa [support, V] using
      boundedEnvelopeSupport_touch M φ hM hφ hU x)
    (by simpa [support, V] using hlower)

/-- Labor-state integrand in the continuation value, parameterized by the
current shifted-asset choice. -/
def boundedContinuationIntegrand
    (M : HouseholdPrimitives)
    (V : BoundedContinuousFunction ExcessResource ℝ)
    (a : ℝ) (l : LaborSupportState M) : ℝ :=
  liftedExcessValue V
    ((1 + M.r) * a + M.w * ((l : ℝ) - M.lmin))

/-- Candidate derivative of the continuation integrand. -/
def boundedContinuationDerivativeIntegrand
    (M : HouseholdPrimitives)
    (V : BoundedContinuousFunction ExcessResource ℝ)
    (a : ℝ) (l : LaborSupportState M) : ℝ :=
  (1 + M.r) * deriv (liftedExcessValue V)
    ((1 + M.r) * a + M.w * ((l : ℝ) - M.lmin))

/-- Dominated differentiation supplies the continuation derivative.  The
closure certificate contains the hypotheses of the parametric-integral
theorem, not this conclusion. -/
theorem boundedAssetContinuation_hasDerivAt
    (M : HouseholdPrimitives) (hM : HouseholdAssumptions M)
    (V : BoundedContinuousFunction ExcessResource ℝ) (a : ℝ)
    (hDiff : LocalDominatedDerivative
      (laborSupportProbability M hM : Measure (LaborSupportState M))
      (boundedContinuationIntegrand M V)
      (boundedContinuationDerivativeIntegrand M V) a) :
    HasDerivAt (boundedAssetContinuation M hM V)
      (∫ l : LaborSupportState M,
        boundedContinuationDerivativeIntegrand M V a l
        ∂(laborSupportProbability M hM : Measure (LaborSupportState M))) a := by
  change HasDerivAt
    (fun b : ℝ => ∫ l : LaborSupportState M,
      liftedExcessValue V
        ((1 + M.r) * b + M.w * ((l : ℝ) - M.lmin))
      ∂(laborSupportProbability M hM : Measure (LaborSupportState M)))
    (∫ l : LaborSupportState M,
      boundedContinuationDerivativeIntegrand M V a l
      ∂(laborSupportProbability M hM : Measure (LaborSupportState M))) a
  exact hDiff.hasDerivAt_integral.2

/-- Derivative of the solved Bellman objective with respect to shifted assets.
The only extra analytic input is the dominated-differentiation certificate for
the continuation integral. -/
theorem boundedAssetObjective_hasDerivAt_at_policy
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) (x : ExcessResource)
    (hc : 0 < resourceLevel M φ x -
      boundedAiyagariAssetPolicy M φ hM hφ hU x)
    (hDiff : LocalDominatedDerivative
      (laborSupportProbability M hM : Measure (LaborSupportState M))
      (boundedContinuationIntegrand M
        (boundedAiyagariValue M φ hM hφ hU))
      (boundedContinuationDerivativeIntegrand M
        (boundedAiyagariValue M φ hM hφ hU))
      (boundedAiyagariAssetPolicy M φ hM hφ hU x)) :
    HasDerivAt
      ((fun b : ℝ => M.utility (resourceLevel M φ x - b)) +
        fun b : ℝ => M.β * boundedAssetContinuation M hM
          (boundedAiyagariValue M φ hM hφ hU) b)
      (-deriv M.utility (resourceLevel M φ x -
          boundedAiyagariAssetPolicy M φ hM hφ hU x) +
        M.β * ∫ l : LaborSupportState M,
          boundedContinuationDerivativeIntegrand M
            (boundedAiyagariValue M φ hM hφ hU)
            (boundedAiyagariAssetPolicy M φ hM hφ hU x) l
          ∂(laborSupportProbability M hM : Measure (LaborSupportState M)))
      (boundedAiyagariAssetPolicy M φ hM hφ hU x) := by
  let V := boundedAiyagariValue M φ hM hφ hU
  let a := boundedAiyagariAssetPolicy M φ hM hφ hU x
  let z := resourceLevel M φ x
  have hUat : HasDerivAt M.utility (deriv M.utility (z - a)) (z - a) :=
    ((hU.differentiableOn (z - a) hc).differentiableAt
      (Ioi_mem_nhds hc)).hasDerivAt
  have hcurrent : HasDerivAt (fun b : ℝ => M.utility (z - b))
      (-deriv M.utility (z - a)) a :=
    hUat.comp_const_sub z a
  have hcontinuation := boundedAssetContinuation_hasDerivAt M hM V a hDiff
  simpa only [V, a, z] using
    hcurrent.add (hcontinuation.const_mul M.β)

/-- Euler inequality and complementary-slackness equality for the solved
bounded household.  At a binding lower asset constraint only rightward
variations are feasible; at a strictly positive asset choice the optimizer is
interior and the derivative vanishes. -/
theorem boundedAiyagari_euler_inequality
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) (x : ExcessResource)
    (hc : 0 < resourceLevel M φ x -
      boundedAiyagariAssetPolicy M φ hM hφ hU x)
    (hDiff : LocalDominatedDerivative
      (laborSupportProbability M hM : Measure (LaborSupportState M))
      (boundedContinuationIntegrand M
        (boundedAiyagariValue M φ hM hφ hU))
      (boundedContinuationDerivativeIntegrand M
        (boundedAiyagariValue M φ hM hφ hU))
      (boundedAiyagariAssetPolicy M φ hM hφ hU x)) :
    let marginal := deriv M.utility (resourceLevel M φ x -
      boundedAiyagariAssetPolicy M φ hM hφ hU x)
    let expectedDerivative := ∫ l : LaborSupportState M,
      boundedContinuationDerivativeIntegrand M
        (boundedAiyagariValue M φ hM hφ hU)
        (boundedAiyagariAssetPolicy M φ hM hφ hU x) l
      ∂(laborSupportProbability M hM : Measure (LaborSupportState M))
    M.β * expectedDerivative ≤ marginal ∧
      (0 < boundedAiyagariAssetPolicy M φ hM hφ hU x →
        M.β * expectedDerivative = marginal) := by
  dsimp only
  let V := boundedAiyagariValue M φ hM hφ hU
  let a := boundedAiyagariAssetPolicy M φ hM hφ hU x
  let z := resourceLevel M φ x
  let dcont := ∫ l : LaborSupportState M,
    boundedContinuationDerivativeIntegrand M V a l
      ∂(laborSupportProbability M hM : Measure (LaborSupportState M))
  let objective : ℝ → ℝ :=
    (fun b : ℝ => M.utility (z - b)) +
      fun b : ℝ => M.β * boundedAssetContinuation M hM V b
  have ha := boundedAiyagariAssetPolicy_mem M φ hM hφ hU x
  have ha' : a ∈ Icc (0 : ℝ) z := by simpa [a, z] using ha
  have haz : a < z := by dsimp [a, z] at hc ⊢; linarith
  have hobj : HasDerivAt objective
      (-deriv M.utility (z - a) + M.β * dcont) a := by
    simpa [objective, V, a, z, dcont] using
      boundedAssetObjective_hasDerivAt_at_policy M φ hM hφ hU x hc hDiff
  have hrightMax : ∀ᶠ b in 𝓝[>] a, objective b ≤ objective a := by
    have hbzEv : ∀ᶠ b in 𝓝[>] a, b < z :=
      (show ∀ᶠ b in 𝓝 a, b < z from Iio_mem_nhds haz).filter_mono
        nhdsWithin_le_nhds
    filter_upwards [hbzEv, self_mem_nhdsWithin] with b hbz hab
    have hab' : a < b := by simpa using hab
    have hbmem : b ∈ Icc (0 : ℝ) z := ⟨ha'.1.trans hab'.le, hbz.le⟩
    simpa [objective, V, a, z, Pi.add_apply,
      boundedAssetObjective_eq_utility_add_continuation] using
      boundedAiyagariAssetPolicy_isMax M φ hM hφ hU x hbmem
  have hnonpos := HasDerivAt.nonpos_of_eventually_right_max hobj hrightMax
  constructor
  · dsimp [V, a, z, dcont] at hnonpos ⊢
    linarith
  · intro hapos
    have hlocal : IsLocalMax objective a := by
      filter_upwards [Ioo_mem_nhds hapos haz] with b hb
      have hbmem : b ∈ Icc (0 : ℝ) z := ⟨hb.1.le, hb.2.le⟩
      simpa [objective, V, a, z, Pi.add_apply,
        boundedAssetObjective_eq_utility_add_continuation] using
        boundedAiyagariAssetPolicy_isMax M φ hM hφ hU x hbmem
    have hzero := hlocal.hasDerivAt_eq_zero hobj
    dsimp [V, a, z, dcont] at hzero ⊢
    linarith

/-- A strict-concavity four-point inequality: moving two points toward one
another while preserving their sum strictly raises the sum of utilities. -/
lemma strictConcave_four_point
    {u : ℝ → ℝ}
    (hu : StrictConcaveOn ℝ (Ici (0 : ℝ)) u)
    {x d e : ℝ} (hx : 0 ≤ x) (hd : 0 < d) (he : 0 < e) :
    u x + u (x + d + e) < u (x + d) + u (x + e) := by
  let α : ℝ := e / (d + e)
  let γ : ℝ := d / (d + e)
  have hde : 0 < d + e := add_pos hd he
  have hα : 0 < α := div_pos he hde
  have hγ : 0 < γ := div_pos hd hde
  have hsum : α + γ = 1 := by
    dsimp [α, γ]
    field_simp [ne_of_gt hde]
    ring
  have hxH : x ≠ x + d + e := by
    intro h
    have hzero : d + e = 0 := by
      calc
        d + e = (x + d + e) - x := by ring
        _ = 0 := by rw [← h]; ring
    exact hde.ne' hzero
  have hH : x + d + e ∈ Ici (0 : ℝ) :=
    add_nonneg (add_nonneg hx hd.le) he.le
  have h₁ := hu.2 hx hH hxH hα hγ hsum
  have h₂ := hu.2 hx hH hxH hγ hα (by simpa [add_comm] using hsum)
  have harg₁ : α * x + γ * (x + d + e) = x + d := by
    dsimp [α, γ]
    field_simp [ne_of_gt hde]
    ring
  have harg₂ : γ * x + α * (x + d + e) = x + e := by
    dsimp [α, γ]
    field_simp [ne_of_gt hde]
    ring
  simp only [smul_eq_mul, harg₁] at h₁
  simp only [smul_eq_mul, harg₂] at h₂
  have hadd := add_lt_add h₁ h₂
  have hweights :
      (α * u x + γ * u (x + d + e)) +
          (γ * u x + α * u (x + d + e)) =
        u x + u (x + d + e) := by
    calc
      (α * u x + γ * u (x + d + e)) +
          (γ * u x + α * u (x + d + e)) =
        (α + γ) * u x + (α + γ) * u (x + d + e) := by ring
      _ = u x + u (x + d + e) := by simp [hsum]
  rw [hweights] at hadd
  exact hadd

/-- The solved shifted-asset policy is weakly increasing in resources.  The
proof is a revealed-preference argument: if a richer household chose fewer
assets, the continuation terms would cancel and strict concavity of current
utility would contradict the four-point inequality above. -/
theorem monotone_boundedAiyagariAssetPolicy
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) :
    Monotone (boundedAiyagariAssetPolicy M φ hM hφ hU) := by
  intro x₁ x₂ hx₁₂
  let z₁ := resourceLevel M φ x₁
  let z₂ := resourceLevel M φ x₂
  let a₁ := boundedAiyagariAssetPolicy M φ hM hφ hU x₁
  let a₂ := boundedAiyagariAssetPolicy M φ hM hφ hU x₂
  have hz : z₁ ≤ z₂ := by
    dsimp [z₁, z₂, resourceLevel]
    have hcoe : (x₁ : ℝ) ≤ (x₂ : ℝ) := by exact_mod_cast hx₁₂
    simpa [add_comm] using
      (add_le_add_right hcoe (minimumResources M.w M.lmin M.r φ))
  have ha₁ := boundedAiyagariAssetPolicy_mem M φ hM hφ hU x₁
  have ha₂ := boundedAiyagariAssetPolicy_mem M φ hM hφ hU x₂
  by_contra hnot
  have ha₂a₁ : a₂ < a₁ := lt_of_not_ge hnot
  have hzstrict : z₁ < z₂ := by
    by_contra hzz
    have hzeq : z₁ = z₂ := le_antisymm hz (le_of_not_gt hzz)
    have hxeq : x₁ = x₂ := by
      apply Subtype.ext
      dsimp [z₁, z₂, resourceLevel] at hzeq
      exact add_left_cancel hzeq
    subst x₂
    exact (lt_irrefl a₁) ha₂a₁
  have ha₂at₁ : a₂ ∈ Icc (0 : ℝ) z₁ :=
    ⟨ha₂.1, ha₂a₁.le.trans ha₁.2⟩
  have ha₁at₂ : a₁ ∈ Icc (0 : ℝ) z₂ :=
    ⟨ha₁.1, ha₁.2.trans hz⟩
  have hopt₁ := boundedAiyagariAssetPolicy_isMax M φ hM hφ hU x₁ ha₂at₁
  have hopt₂ := boundedAiyagariAssetPolicy_isMax M φ hM hφ hU x₂ ha₁at₂
  have hx0 : 0 ≤ z₁ - a₁ := sub_nonneg.mpr ha₁.2
  have hfour := strictConcave_four_point hU.strictConcaveOn hx0
    (sub_pos.mpr ha₂a₁) (sub_pos.mpr hzstrict)
  have hfour' : M.utility (z₁ - a₁) + M.utility (z₂ - a₂) <
      M.utility (z₁ - a₂) + M.utility (z₂ - a₁) := by
    convert hfour using 1 <;> ring
  change boundedAssetObjective M φ hM
      (boundedAiyagariValue M φ hM hφ hU) z₁ a₂ ≤
    boundedAssetObjective M φ hM
      (boundedAiyagariValue M φ hM hφ hU) z₁ a₁ at hopt₁
  change boundedAssetObjective M φ hM
      (boundedAiyagariValue M φ hM hφ hU) z₂ a₁ ≤
    boundedAssetObjective M φ hM
      (boundedAiyagariValue M φ hM hφ hU) z₂ a₂ at hopt₂
  simp only [boundedAssetObjective_eq_utility_add_continuation] at hopt₁ hopt₂
  linarith

/-- Consumption generated by the solved policy is weakly increasing in
resources.  The proof uses revealed preference twice.  If consumption fell,
the two alternative choices would exchange the two consumption levels; strict
optimality would then contradict concavity of expected continuation value. -/
theorem monotone_boundedAiyagariConsumption
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) :
    Monotone (fun x : ExcessResource => resourceLevel M φ x -
      boundedAiyagariAssetPolicy M φ hM hφ hU x) := by
  intro x₁ x₂ hx₁₂
  let z₁ := resourceLevel M φ x₁
  let z₂ := resourceLevel M φ x₂
  let a₁ := boundedAiyagariAssetPolicy M φ hM hφ hU x₁
  let a₂ := boundedAiyagariAssetPolicy M φ hM hφ hU x₂
  have hz : z₁ ≤ z₂ := by
    dsimp [z₁, z₂, resourceLevel]
    have hcoe : (x₁ : ℝ) ≤ (x₂ : ℝ) := by exact_mod_cast hx₁₂
    linarith
  have ha12 : a₁ ≤ a₂ :=
    monotone_boundedAiyagariAssetPolicy M φ hM hφ hU hx₁₂
  have ha₁ := boundedAiyagariAssetPolicy_mem M φ hM hφ hU x₁
  have ha₂ := boundedAiyagariAssetPolicy_mem M φ hM hφ hU x₂
  by_contra hnot
  have hc : z₂ - a₂ < z₁ - a₁ := lt_of_not_ge hnot
  let d := (z₁ - a₁) - (z₂ - a₂)
  let e := z₂ - z₁
  have hd : 0 < d := by dsimp [d]; linarith
  have he : 0 < e := by
    dsimp [e]
    have hxne : x₁ ≠ x₂ := by
      intro hxeq
      subst x₂
      exact hnot le_rfl
    have hxlt : x₁ < x₂ := lt_of_le_of_ne hx₁₂ hxne
    have hcoe : (x₁ : ℝ) < (x₂ : ℝ) := by exact_mod_cast hxlt
    dsimp [z₁, z₂, resourceLevel]
    linarith
  have ha₂eq : a₂ = a₁ + d + e := by
    dsimp [d, e]
    ring
  have hcross₁ : a₁ + d ∈ Icc (0 : ℝ) z₁ := by
    constructor
    · exact add_nonneg ha₁.1 hd.le
    · dsimp [d]
      linarith [ha₂.2]
  have hcross₂ : a₁ + e ∈ Icc (0 : ℝ) z₂ := by
    constructor
    · exact add_nonneg ha₁.1 he.le
    · dsimp [e]
      linarith [ha₁.2]
  have hopt₁ := boundedAiyagariAssetPolicy_isMax M φ hM hφ hU x₁ hcross₁
  have hopt₂ := boundedAiyagariAssetPolicy_isMax M φ hM hφ hU x₂ hcross₂
  have hstrict₁ :
      boundedAssetObjective M φ hM
          (boundedAiyagariValue M φ hM hφ hU) z₁ (a₁ + d) <
        boundedAssetObjective M φ hM
          (boundedAiyagariValue M φ hM hφ hU) z₁ a₁ := by
    apply lt_of_le_of_ne hopt₁
    intro heq
    have hmax : ∀ b ∈ Icc (0 : ℝ) z₁,
        boundedAssetObjective M φ hM
            (boundedAiyagariValue M φ hM hφ hU) z₁ b ≤
          boundedAssetObjective M φ hM
            (boundedAiyagariValue M φ hM hφ hU) z₁ (a₁ + d) := by
      intro b hb
      rw [heq]
      exact boundedAiyagariAssetPolicy_isMax M φ hM hφ hU x₁ hb
    have hu := boundedOptimalAsset_unique M φ hM hφ hU x₁ hcross₁ hmax
    have hu' : a₁ + d = a₁ := by
      simpa [a₁, boundedAiyagariAssetPolicy] using hu
    linarith
  have hstrict₂ :
      boundedAssetObjective M φ hM
          (boundedAiyagariValue M φ hM hφ hU) z₂ (a₁ + e) <
        boundedAssetObjective M φ hM
          (boundedAiyagariValue M φ hM hφ hU) z₂ a₂ := by
    apply lt_of_le_of_ne hopt₂
    intro heq
    have hmax : ∀ b ∈ Icc (0 : ℝ) z₂,
        boundedAssetObjective M φ hM
            (boundedAiyagariValue M φ hM hφ hU) z₂ b ≤
          boundedAssetObjective M φ hM
            (boundedAiyagariValue M φ hM hφ hU) z₂ (a₁ + e) := by
      intro b hb
      rw [heq]
      exact boundedAiyagariAssetPolicy_isMax M φ hM hφ hU x₂ hb
    have hu := boundedOptimalAsset_unique M φ hM hφ hU x₂ hcross₂ hmax
    have hu' : a₁ + e = a₂ := by
      simpa [a₂, boundedAiyagariAssetPolicy] using hu
    rw [ha₂eq] at hu'
    linarith
  have hcont₁ := boundedAssetContinuation_concave_combo M hM
    (boundedAiyagariValue M φ hM hφ hU)
    (boundedAiyagariValue_concave M φ hM hφ hU)
    (a := a₁) (b := a₂) (p := e / (d + e)) (q := d / (d + e))
    ha₁.1 ha₂.1 (by positivity) (by positivity)
    (by field_simp [ne_of_gt (add_pos hd he)]; ring)
  have hcont₂ := boundedAssetContinuation_concave_combo M hM
    (boundedAiyagariValue M φ hM hφ hU)
    (boundedAiyagariValue_concave M φ hM hφ hU)
    (a := a₁) (b := a₂) (p := d / (d + e)) (q := e / (d + e))
    ha₁.1 ha₂.1 (by positivity) (by positivity)
    (by field_simp [ne_of_gt (add_pos hd he)])
  have harg₁ : e / (d + e) * a₁ + d / (d + e) * a₂ = a₁ + d := by
    rw [ha₂eq]
    field_simp [ne_of_gt (add_pos hd he)]
    ring
  have harg₂ : d / (d + e) * a₁ + e / (d + e) * a₂ = a₁ + e := by
    rw [ha₂eq]
    field_simp [ne_of_gt (add_pos hd he)]
    ring
  rw [harg₁] at hcont₁
  rw [harg₂] at hcont₂
  have hcontinuation :
      boundedAssetContinuation M hM
          (boundedAiyagariValue M φ hM hφ hU) a₁ +
        boundedAssetContinuation M hM
          (boundedAiyagariValue M φ hM hφ hU) a₂ ≤
      boundedAssetContinuation M hM
          (boundedAiyagariValue M φ hM hφ hU) (a₁ + d) +
        boundedAssetContinuation M hM
          (boundedAiyagariValue M φ hM hφ hU) (a₁ + e) := by
    have hadd := add_le_add hcont₁ hcont₂
    have hsum : e / (d + e) + d / (d + e) = 1 := by
      field_simp [ne_of_gt (add_pos hd he)]
      ring
    calc
      boundedAssetContinuation M hM
          (boundedAiyagariValue M φ hM hφ hU) a₁ +
          boundedAssetContinuation M hM
            (boundedAiyagariValue M φ hM hφ hU) a₂ =
        1 * boundedAssetContinuation M hM
              (boundedAiyagariValue M φ hM hφ hU) a₁ +
          1 * boundedAssetContinuation M hM
              (boundedAiyagariValue M φ hM hφ hU) a₂ := by ring
      _ =
        (e / (d + e) * boundedAssetContinuation M hM
              (boundedAiyagariValue M φ hM hφ hU) a₁ +
            d / (d + e) * boundedAssetContinuation M hM
              (boundedAiyagariValue M φ hM hφ hU) a₂) +
          (d / (d + e) * boundedAssetContinuation M hM
              (boundedAiyagariValue M φ hM hφ hU) a₁ +
            e / (d + e) * boundedAssetContinuation M hM
              (boundedAiyagariValue M φ hM hφ hU) a₂) := by
                rw [← hsum]
                ring
      _ ≤ _ := hadd
  simp only [boundedAssetObjective_eq_utility_add_continuation] at hstrict₁ hstrict₂
  have hconsume₁ : z₁ - (a₁ + d) = z₂ - a₂ := by
    dsimp [d]
    ring
  have hconsume₂ : z₂ - (a₁ + e) = z₁ - a₁ := by
    dsimp [e]
    ring
  rw [hconsume₁] at hstrict₁
  rw [hconsume₂] at hstrict₂
  nlinarith [hM.β_pos]

/-- Global weak slope bounds in finite-difference form.  They require no
differentiability: monotonicity of assets gives the lower bound, while
monotonicity of consumption gives the upper bound one. -/
theorem boundedAiyagariAssetPolicy_increment_bounds
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    {x₁ x₂ : ExcessResource} (hx : x₁ ≤ x₂) :
    0 ≤ boundedAiyagariAssetPolicy M φ hM hφ hU x₂ -
        boundedAiyagariAssetPolicy M φ hM hφ hU x₁ ∧
      boundedAiyagariAssetPolicy M φ hM hφ hU x₂ -
          boundedAiyagariAssetPolicy M φ hM hφ hU x₁ ≤
        (x₂ : ℝ) - (x₁ : ℝ) := by
  have hA := monotone_boundedAiyagariAssetPolicy M φ hM hφ hU hx
  have hC := monotone_boundedAiyagariConsumption M φ hM hφ hU hx
  constructor
  · linarith
  · dsimp [resourceLevel] at hC
    linarith

/-- Impatience forces zero saving at the minimum excess-resource state,
provided optimal consumption there is positive and the explicitly labeled
dominated-differentiation condition holds.  The proof is Aiyagari's Euler
contradiction: a positive minimum-state asset choice would make every next
state strictly larger, so monotone consumption and decreasing marginal
utility would contradict `β(1+r)<1`. -/
theorem boundedAiyagariAssetPolicy_zero_at_minimum
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (himp : ImpatientHousehold M)
    (hc0 : 0 < resourceLevel M φ (0 : ExcessResource) -
      boundedAiyagariAssetPolicy M φ hM hφ hU 0)
    (hDiff : LocalDominatedDerivative
      (laborSupportProbability M hM : Measure (LaborSupportState M))
      (boundedContinuationIntegrand M
        (boundedAiyagariValue M φ hM hφ hU))
      (boundedContinuationDerivativeIntegrand M
        (boundedAiyagariValue M φ hM hφ hU))
      (boundedAiyagariAssetPolicy M φ hM hφ hU 0)) :
    boundedAiyagariAssetPolicy M φ hM hφ hU 0 = 0 := by
  let V := boundedAiyagariValue M φ hM hφ hU
  let x0 : ExcessResource := 0
  let a0 := boundedAiyagariAssetPolicy M φ hM hφ hU x0
  let c0 := resourceLevel M φ x0 - a0
  let R := 1 + M.r
  let μ : Measure (LaborSupportState M) := laborSupportProbability M hM
  change 0 < c0 at hc0
  have ha0nonneg : 0 ≤ a0 :=
    (boundedAiyagariAssetPolicy_mem M φ hM hφ hU x0).1
  by_contra hzero
  have ha0pos : 0 < a0 := by
    apply lt_of_le_of_ne ha0nonneg
    simpa [a0, x0] using Ne.symm hzero
  have hRpos : 0 < R := by dsimp [R]; linarith [hM.r_pos]
  have heuler := (boundedAiyagari_euler_inequality
    M φ hM hφ hU x0 hc0 hDiff).2 ha0pos
  have huDiffAt : ∀ c ∈ Ioi (0 : ℝ), DifferentiableAt ℝ M.utility c := by
    intro c hc
    exact (hU.differentiableOn c hc).differentiableAt (Ioi_mem_nhds hc)
  have hmarginalAnti : AntitoneOn (deriv M.utility) (Ioi (0 : ℝ)) :=
    (hU.strictConcaveOn.concaveOn.subset Ioi_subset_Ici_self
      (convex_Ioi (0 : ℝ))).antitoneOn_deriv huDiffAt
  have hpoint : ∀ l : LaborSupportState M,
      boundedContinuationDerivativeIntegrand M V a0 l ≤
        R * deriv M.utility c0 := by
    intro l
    have hshock : 0 ≤ M.w * ((l : ℝ) - M.lmin) :=
      mul_nonneg hM.w_pos.le (sub_nonneg.mpr l.property.1)
    have hnextNonneg : 0 ≤ R * a0 + M.w * ((l : ℝ) - M.lmin) :=
      add_nonneg (mul_nonneg hRpos.le ha0nonneg) hshock
    let X : ExcessResource :=
      ⟨R * a0 + M.w * ((l : ℝ) - M.lmin), hnextNonneg⟩
    have hXpos : 0 < (X : ℝ) := by
      dsimp [X]
      exact add_pos_of_pos_of_nonneg (mul_pos hRpos ha0pos) hshock
    have hx0X : x0 ≤ X := by
      exact_mod_cast hnextNonneg
    have hcmono := monotone_boundedAiyagariConsumption
      M φ hM hφ hU hx0X
    have hcX : 0 < resourceLevel M φ X -
        boundedAiyagariAssetPolicy M φ hM hφ hU X := by
      exact hc0.trans_le hcmono
    have henv := boundedAiyagari_envelope_of_consumption_pos
      M φ hM hφ hU X hXpos hcX
    have hmarginal := hmarginalAnti (show c0 ∈ Ioi (0 : ℝ) from hc0)
      (show resourceLevel M φ X -
        boundedAiyagariAssetPolicy M φ hM hφ hU X ∈ Ioi (0 : ℝ) from hcX)
      (by simpa [c0, a0, x0] using hcmono)
    have hderivEq : deriv (liftedExcessValue V) (X : ℝ) =
        deriv M.utility (resourceLevel M φ X -
          boundedAiyagariAssetPolicy M φ hM hφ hU X) := by
      simpa [V] using henv.deriv
    unfold boundedContinuationDerivativeIntegrand
    change R * deriv (liftedExcessValue V) (X : ℝ) ≤
      R * deriv M.utility c0
    rw [hderivEq]
    exact mul_le_mul_of_nonneg_left hmarginal hRpos.le
  have hderivIntegrable : Integrable
      (boundedContinuationDerivativeIntegrand M V a0) μ := by
    simpa [V, a0, x0, μ] using hDiff.hasDerivAt_integral.1
  have hconstantIntegrable : Integrable
      (fun _ : LaborSupportState M => R * deriv M.utility c0) μ :=
    integrable_const _
  have hintegral :
      (∫ l : LaborSupportState M,
        boundedContinuationDerivativeIntegrand M V a0 l ∂μ) ≤
        R * deriv M.utility c0 := by
    have hmono := integral_mono_ae hderivIntegrable hconstantIntegrable
      (Eventually.of_forall hpoint)
    simpa [μ] using hmono
  have hmarginalPos : 0 < deriv M.utility c0 := by
    exact hU.marginal_pos c0 hc0
  have hdiscounted := mul_le_mul_of_nonneg_left hintegral hM.β_pos.le
  dsimp [V, a0, c0, x0, R, μ] at heuler hdiscounted
  rw [heuler] at hdiscounted
  nlinarith [himp.discountedReturn_lt_one]

/-- Any state at which the household saves strictly positive assets has
current marginal utility bounded by discounted gross-return times marginal
utility at the minimum state.  This is the uniform inequality behind the
nondegenerate cutoff argument. -/
theorem boundedAiyagari_marginal_le_minimum_of_policy_pos
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (hc0 : 0 < resourceLevel M φ (0 : ExcessResource) -
      boundedAiyagariAssetPolicy M φ hM hφ hU 0)
    (x : ExcessResource)
    (hapos : 0 < boundedAiyagariAssetPolicy M φ hM hφ hU x)
    (hDiff : LocalDominatedDerivative
      (laborSupportProbability M hM : Measure (LaborSupportState M))
      (boundedContinuationIntegrand M
        (boundedAiyagariValue M φ hM hφ hU))
      (boundedContinuationDerivativeIntegrand M
        (boundedAiyagariValue M φ hM hφ hU))
      (boundedAiyagariAssetPolicy M φ hM hφ hU x)) :
    deriv M.utility (resourceLevel M φ x -
        boundedAiyagariAssetPolicy M φ hM hφ hU x) ≤
      M.β * (1 + M.r) *
        deriv M.utility (resourceLevel M φ (0 : ExcessResource) -
          boundedAiyagariAssetPolicy M φ hM hφ hU 0) := by
  let V := boundedAiyagariValue M φ hM hφ hU
  let x0 : ExcessResource := 0
  let a := boundedAiyagariAssetPolicy M φ hM hφ hU x
  let c0 := resourceLevel M φ x0 -
    boundedAiyagariAssetPolicy M φ hM hφ hU x0
  let R := 1 + M.r
  let μ : Measure (LaborSupportState M) := laborSupportProbability M hM
  change 0 < c0 at hc0
  have hRpos : 0 < R := by dsimp [R]; linarith [hM.r_pos]
  have hcmono0 := monotone_boundedAiyagariConsumption M φ hM hφ hU
    (show x0 ≤ x from bot_le)
  have hcx : 0 < resourceLevel M φ x - a := by
    exact hc0.trans_le (by simpa [c0, a, x0] using hcmono0)
  have heuler := (boundedAiyagari_euler_inequality
    M φ hM hφ hU x hcx hDiff).2 hapos
  have huDiffAt : ∀ c ∈ Ioi (0 : ℝ), DifferentiableAt ℝ M.utility c := by
    intro c hc
    exact (hU.differentiableOn c hc).differentiableAt (Ioi_mem_nhds hc)
  have hmarginalAnti : AntitoneOn (deriv M.utility) (Ioi (0 : ℝ)) :=
    (hU.strictConcaveOn.concaveOn.subset Ioi_subset_Ici_self
      (convex_Ioi (0 : ℝ))).antitoneOn_deriv huDiffAt
  have hpoint : ∀ l : LaborSupportState M,
      boundedContinuationDerivativeIntegrand M V a l ≤
        R * deriv M.utility c0 := by
    intro l
    have ha0 : 0 ≤ a := by
      exact (boundedAiyagariAssetPolicy_mem M φ hM hφ hU x).1
    have hshock : 0 ≤ M.w * ((l : ℝ) - M.lmin) :=
      mul_nonneg hM.w_pos.le (sub_nonneg.mpr l.property.1)
    have hnextNonneg : 0 ≤ R * a + M.w * ((l : ℝ) - M.lmin) :=
      add_nonneg (mul_nonneg hRpos.le ha0) hshock
    let X : ExcessResource :=
      ⟨R * a + M.w * ((l : ℝ) - M.lmin), hnextNonneg⟩
    have hXpos : 0 < (X : ℝ) := by
      dsimp [X]
      exact add_pos_of_pos_of_nonneg (mul_pos hRpos hapos) hshock
    have hcmono := monotone_boundedAiyagariConsumption M φ hM hφ hU
      (show x0 ≤ X from bot_le)
    have hcX : 0 < resourceLevel M φ X -
        boundedAiyagariAssetPolicy M φ hM hφ hU X := hc0.trans_le hcmono
    have henv := boundedAiyagari_envelope_of_consumption_pos
      M φ hM hφ hU X hXpos hcX
    have hmarginal := hmarginalAnti (show c0 ∈ Ioi (0 : ℝ) from hc0)
      (show resourceLevel M φ X -
        boundedAiyagariAssetPolicy M φ hM hφ hU X ∈ Ioi (0 : ℝ) from hcX)
      (by simpa [c0, x0] using hcmono)
    have hderivEq : deriv (liftedExcessValue V) (X : ℝ) =
        deriv M.utility (resourceLevel M φ X -
          boundedAiyagariAssetPolicy M φ hM hφ hU X) := by
      simpa [V] using henv.deriv
    unfold boundedContinuationDerivativeIntegrand
    change R * deriv (liftedExcessValue V) (X : ℝ) ≤
      R * deriv M.utility c0
    rw [hderivEq]
    exact mul_le_mul_of_nonneg_left hmarginal hRpos.le
  have hderivIntegrable : Integrable
      (boundedContinuationDerivativeIntegrand M V a) μ := by
    simpa [V, a, μ] using hDiff.hasDerivAt_integral.1
  have hintegral :
      (∫ l : LaborSupportState M,
        boundedContinuationDerivativeIntegrand M V a l ∂μ) ≤
        R * deriv M.utility c0 := by
    have hmono := integral_mono_ae hderivIntegrable (integrable_const _)
      (Eventually.of_forall hpoint)
    simpa [μ] using hmono
  have hdiscounted := mul_le_mul_of_nonneg_left hintegral hM.β_pos.le
  dsimp [V, a, c0, x0, R, μ] at heuler hdiscounted ⊢
  rw [heuler] at hdiscounted
  linarith

/-- Aiyagari's finite-at-zero cutoff, conditional only on positive minimum
consumption and a dominated-differentiation certificate at each state.  The
cutoff is nondegenerate in excess resources. -/
theorem boundedAiyagari_binding_cutoff
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    (himp : ImpatientHousehold M)
    (hc0 : 0 < resourceLevel M φ (0 : ExcessResource) -
      boundedAiyagariAssetPolicy M φ hM hφ hU 0)
    (hDiff : ∀ x : ExcessResource, LocalDominatedDerivative
      (laborSupportProbability M hM : Measure (LaborSupportState M))
      (boundedContinuationIntegrand M
        (boundedAiyagariValue M φ hM hφ hU))
      (boundedContinuationDerivativeIntegrand M
        (boundedAiyagariValue M φ hM hφ hU))
      (boundedAiyagariAssetPolicy M φ hM hφ hU x)) :
    ∃ xhat : ExcessResource, 0 < (xhat : ℝ) ∧
      ∀ x : ExcessResource, x ≤ xhat →
        boundedAiyagariAssetPolicy M φ hM hφ hU x = 0 := by
  let x0 : ExcessResource := 0
  let cfun : ExcessResource → ℝ := fun x => resourceLevel M φ x -
    boundedAiyagariAssetPolicy M φ hM hφ hU x
  let mfun : ExcessResource → ℝ := fun x => deriv M.utility (cfun x)
  have hcfun : Continuous cfun := by
    dsimp [cfun]
    apply Continuous.sub
    · unfold resourceLevel
      fun_prop
    · exact continuous_boundedAiyagariAssetPolicy M φ hM hφ hU
  have hc0' : 0 < cfun x0 := by simpa [cfun, x0] using hc0
  have hmarginalContinuous : ContinuousAt (deriv M.utility) (cfun x0) := by
    have hcontOn := hU.twice_smooth.continuousOn_deriv_of_isOpen
      isOpen_Ioi (by norm_num)
    exact (hcontOn (cfun x0) hc0').continuousAt (Ioi_mem_nhds hc0')
  have hmfun : ContinuousAt mfun x0 := by
    exact hmarginalContinuous.comp hcfun.continuousAt
  have hm0pos : 0 < mfun x0 := by
    exact hU.marginal_pos (cfun x0) hc0'
  have hgap : M.β * (1 + M.r) * mfun x0 < mfun x0 := by
    nlinarith [himp.discountedReturn_lt_one]
  have hevent : ∀ᶠ x in 𝓝 x0, M.β * (1 + M.r) * mfun x0 < mfun x :=
    continuousAt_const.eventually_lt hmfun hgap
  have hevent0 : ∀ᶠ x in 𝓝 (0 : ExcessResource),
      M.β * (1 + M.r) * mfun x0 < mfun x := by
    simpa [x0] using hevent
  rcases NNReal.nhds_zero_basis.mem_iff.mp hevent0 with
    ⟨δ, hδ, hδsub⟩
  have hδreal : 0 < (δ : ℝ) := by exact_mod_cast hδ
  let xhat : ExcessResource := ⟨(δ : ℝ) / 2, (half_pos hδreal).le⟩
  refine ⟨xhat, half_pos hδreal, ?_⟩
  intro x hx
  by_contra hzero
  have hapos : 0 < boundedAiyagariAssetPolicy M φ hM hφ hU x := by
    apply lt_of_le_of_ne (boundedAiyagariAssetPolicy_mem M φ hM hφ hU x).1
    exact Ne.symm hzero
  have hmarginalBound := boundedAiyagari_marginal_le_minimum_of_policy_pos
    M φ hM hφ hU hc0 x hapos (hDiff x)
  have hxIio : x ∈ Iio δ := by
    have hxreal : (x : ℝ) ≤ (δ : ℝ) / 2 := by exact_mod_cast hx
    apply NNReal.coe_lt_coe.mp
    linarith
  have hstrict := hδsub hxIio
  dsimp [mfun, cfun, x0] at hstrict hmarginalBound
  exact (not_lt_of_ge hmarginalBound) hstrict

/-- The household solution contains only objects produced by the existence
theorem and their defining equations.  It contains no uniqueness field. -/
structure HouseholdSolution (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) where
  value : BoundedContinuousFunction ExcessResource ℝ
  policy : ExcessResource → ℝ
  value_fixedPoint :
    Function.IsFixedPt (boundedAiyagariBellman M φ hM hφ hU) value
  policy_feasible : ∀ x, policy x ∈ Icc 0 (resourceLevel M φ x)
  policy_optimal : ∀ x a, a ∈ Icc 0 (resourceLevel M φ x) →
    boundedAssetObjective M φ hM value (resourceLevel M φ x) a ≤
      boundedAssetObjective M φ hM value (resourceLevel M φ x) (policy x)

/-- The solved bounded household problem. -/
def solveBoundedHousehold (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M) : HouseholdSolution M φ hM hφ hU where
  value := boundedAiyagariValue M φ hM hφ hU
  policy := boundedAiyagariAssetPolicy M φ hM hφ hU
  value_fixedPoint := boundedAiyagariValue_isFixedPoint M φ hM hφ hU
  policy_feasible := boundedAiyagariAssetPolicy_mem M φ hM hφ hU
  policy_optimal := boundedAiyagariAssetPolicy_isMax M φ hM hφ hU

/-- Equality of the economic borrowing-limit parameter gives equality of the
actual solved bounded household objects.  The admissibility witnesses are
proofs only and cannot change the value, policy, or consumption functions. -/
theorem solvedBoundedHousehold_behavior_eq_of_limit_eq
    (M : HouseholdPrimitives) {φ₁ φ₂ : ℝ}
    (hM : HouseholdAssumptions M)
    (hφ₁ : BorrowingLimitAdmissible M φ₁)
    (hφ₂ : BorrowingLimitAdmissible M φ₂)
    (hU : BoundedFiniteUtility M)
    (hφ : φ₁ = φ₂) :
    boundedAiyagariValue M φ₁ hM hφ₁ hU =
        boundedAiyagariValue M φ₂ hM hφ₂ hU ∧
      boundedAiyagariAssetPolicy M φ₁ hM hφ₁ hU =
        boundedAiyagariAssetPolicy M φ₂ hM hφ₂ hU ∧
      boundedAiyagariConsumption M φ₁ hM hφ₁ hU =
        boundedAiyagariConsumption M φ₂ hM hφ₂ hU := by
  subst φ₂
  have hproof : hφ₁ = hφ₂ := Subsingleton.elim _ _
  subst hφ₂
  exact ⟨rfl, rfl, rfl⟩

/-- Changing only the primitive record's statutory `b` field cannot change a
solved household problem at a fixed effective limit.  This lemma discharges
the bookkeeping issue needed for the full equilibrium version of Property 17. -/
theorem solvedBoundedHousehold_behavior_eq_of_borrowingLimit_update
    (M : HouseholdPrimitives) (φ : ℝ)
    (hM : HouseholdAssumptions M)
    (hφ : BorrowingLimitAdmissible M φ)
    (hU : BoundedFiniteUtility M)
    {b₁ b₂ : ℝ} (hb₁ : 0 ≤ b₁) (hb₂ : 0 ≤ b₂) :
    boundedAiyagariValue (M.withBorrowingLimit b₁) φ
        (hM.withBorrowingLimit hb₁) (hφ.withBorrowingLimit)
        (hU.withBorrowingLimit b₁) =
      boundedAiyagariValue (M.withBorrowingLimit b₂) φ
        (hM.withBorrowingLimit hb₂) (hφ.withBorrowingLimit)
        (hU.withBorrowingLimit b₂) ∧
    boundedAiyagariAssetPolicy (M.withBorrowingLimit b₁) φ
        (hM.withBorrowingLimit hb₁) (hφ.withBorrowingLimit)
        (hU.withBorrowingLimit b₁) =
      boundedAiyagariAssetPolicy (M.withBorrowingLimit b₂) φ
        (hM.withBorrowingLimit hb₂) (hφ.withBorrowingLimit)
        (hU.withBorrowingLimit b₂) ∧
    boundedAiyagariConsumption (M.withBorrowingLimit b₁) φ
        (hM.withBorrowingLimit hb₁) (hφ.withBorrowingLimit)
        (hU.withBorrowingLimit b₁) =
      boundedAiyagariConsumption (M.withBorrowingLimit b₂) φ
        (hM.withBorrowingLimit hb₂) (hφ.withBorrowingLimit)
        (hU.withBorrowingLimit b₂) := by
  exact ⟨rfl, rfl, rfl⟩

/-- Simultaneously transporting an equal effective limit and changing only the
stored statutory limit preserves all solved household behavior. -/
theorem solvedBoundedHousehold_behavior_eq_of_b_and_limit
    (M : HouseholdPrimitives)
    (hM : HouseholdAssumptions M) (hU : BoundedFiniteUtility M)
    {b₁ b₂ φ₁ φ₂ : ℝ} (hb₁ : 0 ≤ b₁) (hb₂ : 0 ≤ b₂)
    (hφ₁ : BorrowingLimitAdmissible M φ₁)
    (hφ₂ : BorrowingLimitAdmissible M φ₂) (hlimit : φ₁ = φ₂) :
    boundedAiyagariValue (M.withBorrowingLimit b₁) φ₁
        (hM.withBorrowingLimit hb₁) hφ₁.withBorrowingLimit
        (hU.withBorrowingLimit b₁) =
      boundedAiyagariValue (M.withBorrowingLimit b₂) φ₂
        (hM.withBorrowingLimit hb₂) hφ₂.withBorrowingLimit
        (hU.withBorrowingLimit b₂) ∧
    boundedAiyagariAssetPolicy (M.withBorrowingLimit b₁) φ₁
        (hM.withBorrowingLimit hb₁) hφ₁.withBorrowingLimit
        (hU.withBorrowingLimit b₁) =
      boundedAiyagariAssetPolicy (M.withBorrowingLimit b₂) φ₂
        (hM.withBorrowingLimit hb₂) hφ₂.withBorrowingLimit
        (hU.withBorrowingLimit b₂) ∧
    boundedAiyagariConsumption (M.withBorrowingLimit b₁) φ₁
        (hM.withBorrowingLimit hb₁) hφ₁.withBorrowingLimit
        (hU.withBorrowingLimit b₁) =
      boundedAiyagariConsumption (M.withBorrowingLimit b₂) φ₂
        (hM.withBorrowingLimit hb₂) hφ₂.withBorrowingLimit
        (hU.withBorrowingLimit b₂) := by
  subst φ₂
  exact ⟨rfl, rfl, rfl⟩

/-- The effective limit is always admissible when the return is positive: it
is no larger than the natural debt limit, so minimum shifted resources are
nonnegative. -/
theorem effectiveBorrowingLimit_admissible
    (M : HouseholdPrimitives) (hM : HouseholdAssumptions M) (b : ℝ) :
    BorrowingLimitAdmissible M
      (effectiveBorrowingLimit b M.w M.lmin M.r) := by
  refine ⟨?_⟩
  have hle : effectiveBorrowingLimit b M.w M.lmin M.r ≤
      naturalDebtLimit M.w M.lmin M.r := by
    simp only [effectiveBorrowingLimit, if_pos hM.r_pos]
    exact min_le_right _ _
  have hr0 : M.r ≠ 0 := ne_of_gt hM.r_pos
  have hnatural :
      M.r * naturalDebtLimit M.w M.lmin M.r = M.w * M.lmin := by
    unfold naturalDebtLimit
    field_simp [hr0]
  have hmul := mul_le_mul_of_nonneg_left hle hM.r_pos.le
  unfold minimumResources
  rw [hnatural] at hmul
  linarith

/-- Value of the solved bounded household indexed directly by the statutory
borrowing limit, after applying the model's effective-limit rule. -/
def effectiveBoundedAiyagariValue
    (M : HouseholdPrimitives) (hM : HouseholdAssumptions M)
    (hU : BoundedFiniteUtility M) (b : ℝ) :=
  boundedAiyagariValue M (effectiveBorrowingLimit b M.w M.lmin M.r)
    hM (effectiveBorrowingLimit_admissible M hM b) hU

/-- Optimal shifted-asset policy indexed by the statutory borrowing limit. -/
def effectiveBoundedAiyagariAssetPolicy
    (M : HouseholdPrimitives) (hM : HouseholdAssumptions M)
    (hU : BoundedFiniteUtility M) (b : ℝ) :=
  boundedAiyagariAssetPolicy M (effectiveBorrowingLimit b M.w M.lmin M.r)
    hM (effectiveBorrowingLimit_admissible M hM b) hU

/-- Optimal consumption indexed by the statutory borrowing limit. -/
def effectiveBoundedAiyagariConsumption
    (M : HouseholdPrimitives) (hM : HouseholdAssumptions M)
    (hU : BoundedFiniteUtility M) (b : ℝ) :=
  boundedAiyagariConsumption M (effectiveBorrowingLimit b M.w M.lmin M.r)
    hM (effectiveBorrowingLimit_admissible M hM b) hU

end

end Aiyagari1994
