import Mathlib

/-!
# Aiyagari (1994): concrete model objects

This file contains definitions only.  Economic and analytic assumptions live
in `Assumptions.lean`; theorem conclusions are never stored in model records.
-/

open Filter MeasureTheory Set Topology
open scoped BigOperators ENNReal NNReal ProbabilityTheory Topology

namespace Aiyagari1994

noncomputable section

abbrev HouseholdState := ℝ × ℝ
abbrev RealProcess (Ω : Type*) := ℕ → Ω → ℝ
abbrev AssetSupply := ℝ → ℝ
abbrev CapitalDemand := ℝ → ℝ

/-- The canonical history space for the i.i.d. household model.  Keeping the
shock history concrete makes independence of future coordinates available
from the infinite product measure, rather than hiding it in an arbitrary
process. -/
abbrev LaborHistory := ℕ → ℝ

/-- A resource state measured above the minimum feasible resource level. -/
abbrev ExcessResource := ℝ≥0

/-- Saving is parameterized by a share in the compact interval [0,1].  At
resource level z, share s represents the shifted asset choice s*z. -/
abbrev SavingShare := Set.Icc (0 : ℝ) 1

/-- Household primitives for the i.i.d. income-fluctuation problem. -/
structure HouseholdPrimitives where
  β : ℝ
  r : ℝ
  w : ℝ
  b : ℝ
  lmin : ℝ
  lmax : ℝ
  utility : ℝ → ℝ
  laborLaw : Measure ℝ

namespace HouseholdPrimitives

/-- Change only the statutory borrowing-limit bookkeeping field.  Preferences,
prices, labor support, and the shock law are definitionally unchanged. -/
def withBorrowingLimit (M : HouseholdPrimitives) (b : ℝ) :
    HouseholdPrimitives :=
  { M with b := b }

@[simp] theorem withBorrowingLimit_b
    (M : HouseholdPrimitives) (b : ℝ) :
    (M.withBorrowingLimit b).b = b := rfl

@[simp] theorem withBorrowingLimit_β
    (M : HouseholdPrimitives) (b : ℝ) :
    (M.withBorrowingLimit b).β = M.β := rfl

@[simp] theorem withBorrowingLimit_r
    (M : HouseholdPrimitives) (b : ℝ) :
    (M.withBorrowingLimit b).r = M.r := rfl

@[simp] theorem withBorrowingLimit_w
    (M : HouseholdPrimitives) (b : ℝ) :
    (M.withBorrowingLimit b).w = M.w := rfl

@[simp] theorem withBorrowingLimit_lmin
    (M : HouseholdPrimitives) (b : ℝ) :
    (M.withBorrowingLimit b).lmin = M.lmin := rfl

@[simp] theorem withBorrowingLimit_lmax
    (M : HouseholdPrimitives) (b : ℝ) :
    (M.withBorrowingLimit b).lmax = M.lmax := rfl

@[simp] theorem withBorrowingLimit_utility
    (M : HouseholdPrimitives) (b : ℝ) :
    (M.withBorrowingLimit b).utility = M.utility := rfl

@[simp] theorem withBorrowingLimit_laborLaw
    (M : HouseholdPrimitives) (b : ℝ) :
    (M.withBorrowingLimit b).laborLaw = M.laborLaw := rfl

end HouseholdPrimitives

/-- Labor shocks restricted to the primitive compact support. -/
abbrev LaborSupportState (M : HouseholdPrimitives) :=
  Set.Icc M.lmin M.lmax

/-- The labor probability transported to its compact support subtype. -/
def laborSupportMeasure (M : HouseholdPrimitives) :
    Measure (LaborSupportState M) :=
  Measure.comap Subtype.val M.laborLaw

/-- Utility whose economic domain is strictly positive consumption.  In
particular, the structure has no field representing utility at zero. -/
structure PositiveUtility where
  value : {c : ℝ // 0 < c} → ℝ

namespace PositiveUtility

/-- An analytic representative used only on the positive half-line.  Results
about a positive utility must use this function through Ioi 0; the value of
this representative outside that set carries no economic meaning. -/
noncomputable def onPositive (U : PositiveUtility) (c : ℝ) : ℝ :=
  if h : 0 < c then U.value ⟨c, h⟩ else 0

@[simp] theorem onPositive_of_pos (U : PositiveUtility) {c : ℝ} (hc : 0 < c) :
    U.onPositive c = U.value ⟨c, hc⟩ := by
  simp [onPositive, hc]

end PositiveUtility

/-- Household primitives for the Inada branch.  This is deliberately separate
from HouseholdPrimitives, whose utility is finite at zero. -/
structure PositiveHouseholdPrimitives where
  β : ℝ
  r : ℝ
  w : ℝ
  b : ℝ
  lmin : ℝ
  lmax : ℝ
  utility : PositiveUtility
  laborLaw : Measure ℝ

/-- The product probability law of the canonical i.i.d. labor history. -/
def laborHistoryMeasure (M : HouseholdPrimitives) : Measure LaborHistory :=
  Measure.infinitePi (fun _ : ℕ => M.laborLaw)

/-- The labor realization at date t on the canonical history space. -/
def canonicalLabor (t : ℕ) (ω : LaborHistory) : ℝ := ω t

/-- The finite vector of labor observations available through date `t`. -/
def finiteLaborHistory (t : ℕ) (ω : LaborHistory) :
    (Finset.range (t + 1) : Set ℕ) → ℝ :=
  fun i => ω i

/-- The natural filtration generated by the canonical labor coordinates.
It is written explicitly as the pullback of the finite history vector.  This
definition is equivalent to `Filtration.natural canonicalLabor`, but its
finite-index form makes past/future independence directly usable. -/
noncomputable def canonicalLaborFiltration :
    MeasureTheory.Filtration ℕ (inferInstance : MeasurableSpace LaborHistory) :=
  { seq := fun t => MeasurableSpace.comap (finiteLaborHistory t) inferInstance
    mono' := by
      intro i j hij
      let restrictHistory :
          ((Finset.range (j + 1) : Set ℕ) → ℝ) →
            ((Finset.range (i + 1) : Set ℕ) → ℝ) :=
        fun x k => x ⟨k, Finset.mem_range.mpr
          (lt_of_lt_of_le (Finset.mem_range.mp k.2) (Nat.add_le_add_right hij 1))⟩
      apply MeasurableSpace.comap_le_comap_of_eq_comp restrictHistory
      · exact measurable_pi_lambda _ (fun _ => measurable_pi_apply _)
      · funext ω k
        rfl
    le' := by
      intro t
      exact (measurable_pi_lambda _ (fun _ => measurable_pi_apply _)).comap_le }

/-- Production primitives used by the stationary economy. -/
structure Primitives where
  β : ℝ
  δ : ℝ
  lmin : ℝ
  production : ℝ → ℝ
  marginalProductCapital : ℝ → ℝ
  wageFromCapital : ℝ → ℝ
  capitalDemand : CapitalDemand

def timePreferenceRate (β : ℝ) : ℝ := (1 - β) / β

def naturalDebtLimit (w lmin r : ℝ) : ℝ := w * lmin / r

def effectiveBorrowingLimit (b w lmin r : ℝ) : ℝ :=
  if 0 < r then min b (naturalDebtLimit w lmin r) else b

def presentValueBorrowingLimit (w lmin r : ℝ) : ℝ :=
  naturalDebtLimit w lmin r

def shiftedAsset (a φ : ℝ) : ℝ := a + φ

def totalResources (w l r ahat φ : ℝ) : ℝ :=
  w * l + (1 + r) * ahat - r * φ

def minimumResources (w lmin r φ : ℝ) : ℝ := w * lmin - r * φ

/-- Convert excess resources back to the paper's total-resource variable. -/
def resourceLevel
    (M : HouseholdPrimitives) (φ : ℝ) (x : ExcessResource) : ℝ :=
  minimumResources M.w M.lmin M.r φ + x

/-- Feasible shifted assets at a state expressed in excess resources. -/
def excessFeasibleChoices
    (M : HouseholdPrimitives) (φ : ℝ) (x : ExcessResource) : Set ℝ :=
  Icc 0 (resourceLevel M φ x)

def consumptionFromPolicy (A : ℝ → ℝ) (z : ℝ) : ℝ := z - A z

def resourceTransition (M : HouseholdPrimitives) (φ ahat lnext : ℝ) : ℝ :=
  totalResources M.w lnext M.r ahat φ

/-- The next excess-resource level before coercion to nonnegative reals. -/
def excessResourceTransition
    (M : HouseholdPrimitives) (φ ahat lnext : ℝ) : ℝ :=
  resourceTransition M φ ahat lnext -
    minimumResources M.w M.lmin M.r φ

/-- Feasible shifted assets at resources `z`. -/
def feasibleChoices (z : ℝ) : Set ℝ := Icc 0 z

/-- Expected continuation value under the labor law. -/
def expectedContinuation
    (M : HouseholdPrimitives) (φ : ℝ) (V : ℝ → ℝ) (ahat : ℝ) : ℝ :=
  ∫ l, V (resourceTransition M φ ahat l) ∂M.laborLaw

/-- The concrete one-period Bellman objective. -/
def bellmanObjective
    (M : HouseholdPrimitives) (φ : ℝ) (V : ℝ → ℝ) (z ahat : ℝ) : ℝ :=
  M.utility (z - ahat) + M.β * expectedContinuation M φ V ahat

/-- The Bellman operator is the supremum over the feasible interval. -/
def bellmanOperator
    (M : HouseholdPrimitives) (φ : ℝ) (V : ℝ → ℝ) (z : ℝ) : ℝ :=
  sSup (bellmanObjective M φ V z '' feasibleChoices z)

def IsBellmanFixedPoint
    (M : HouseholdPrimitives) (φ : ℝ) (V : ℝ → ℝ) : Prop :=
  bellmanOperator M φ V = V

/-- A policy is optimal for the concrete Bellman objective. -/
def IsOptimalPolicy
    (M : HouseholdPrimitives) (φ : ℝ) (V A : ℝ → ℝ) : Prop :=
  ∀ z, A z ∈ feasibleChoices z ∧
    ∀ x ∈ feasibleChoices z,
      bellmanObjective M φ V z x ≤ bellmanObjective M φ V z (A z)

/-- A deterministic path satisfies the household budget and feasibility. -/
def FeasiblePath
    (w r : ℝ) (a c l : ℕ → ℝ) : Prop :=
  ∀ t, 0 ≤ c t ∧ c t + a (t + 1) = w * l t + (1 + r) * a t

/-- The worst-case feasible path used in the pathwise core of Proposition 1. -/
def MinimumIncomeFeasiblePath
    (w lmin r : ℝ) (a c : ℕ → ℝ) : Prop :=
  FeasiblePath w r a c (fun _ => lmin)

/-- A stochastic plan satisfies feasibility almost surely at every date. -/
def FeasibleProcess
    {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)
    (w r : ℝ) (a c l : RealProcess Ω) : Prop :=
  ∀ t, ∀ᵐ ω ∂μ,
    0 ≤ c t ω ∧
      c t ω + a (t + 1) ω = w * l t ω + (1 + r) * a t ω

/-- Almost-sure bounded support for the labor process. -/
def LaborSupport
    {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)
    (l : RealProcess Ω) (lmin lmax : ℝ) : Prop :=
  ∀ t, ∀ᵐ ω ∂μ, lmin ≤ l t ω ∧ l t ω ≤ lmax

/-- Adaptedness to a supplied filtration. -/
def Adapted
    {Ω : Type*} (filtration : ℕ → MeasurableSpace Ω)
    (x : RealProcess Ω) : Prop :=
  ∀ t, @Measurable Ω ℝ (filtration t) inferInstance (x t)

/-- A feasible plan on the canonical i.i.d. labor history with the paper's
information timing.  Beginning-of-period assets are chosen one period before
the current labor shock: `assets (t+1)` is measurable at date `t`, while
consumption at `t` may use the current shock.  Initial assets are deterministic.
This predictable timing is essential in the reverse half of Property 1. -/
structure CanonicalIIDPlan (M : HouseholdPrimitives) where
  assets : RealProcess LaborHistory
  consumption : RealProcess LaborHistory
  initialAssets : ℝ
  assets_zero : assets 0 = fun _ => initialAssets
  assets_next_measurable : ∀ t,
    @Measurable LaborHistory ℝ (canonicalLaborFiltration t) inferInstance
      (assets (t + 1))
  consumption_adapted :
    MeasureTheory.Adapted canonicalLaborFiltration consumption
  feasible :
    FeasibleProcess (laborHistoryMeasure M) M.w M.r assets consumption
      canonicalLabor

/-- Pathwise natural debt bound. -/
def NaturalDebtBound (a : ℕ → ℝ) (w lmin r : ℝ) : Prop :=
  ∀ t, -(naturalDebtLimit w lmin r) ≤ a t

/-- Almost-sure natural debt bound. -/
def NaturalDebtBoundAE
    {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)
    (a : RealProcess Ω) (w lmin r : ℝ) : Prop :=
  ∀ t, ∀ᵐ ω ∂μ, -(naturalDebtLimit w lmin r) ≤ a t ω

/-- The pathwise terminal/no-Ponzi condition. -/
def NoPonzi (a : ℕ → ℝ) (r : ℝ) : Prop :=
  ∃ L : ℝ, 0 ≤ L ∧
    Tendsto (fun t : ℕ => a (t + 1) / (1 + r) ^ t) atTop (𝓝 L)

/-- The paper's almost-sure terminal condition. -/
def NoPonziAE
    {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)
    (a : RealProcess Ω) (r : ℝ) : Prop :=
  ∀ᵐ ω ∂μ, NoPonzi (fun t => a t ω) r

def EulerInequality
    (marginalUtility expectedMarginalValue : ℝ → ℝ)
    (β r z : ℝ) : Prop :=
  β * (1 + r) * expectedMarginalValue z ≤ marginalUtility z

def IsBindingCutoff (A : ℝ → ℝ) (zmin zhat : ℝ) : Prop :=
  zmin < zhat ∧ ∀ z, z ∈ Icc zmin zhat → A z = 0

def PolicyShiftedUp (baseline moreRisk : ℝ → ℝ) : Prop :=
  ∀ z, baseline z ≤ moreRisk z

def ConsumptionShiftedDown (baseline moreRisk : ℝ → ℝ) : Prop :=
  ∀ z, consumptionFromPolicy moreRisk z ≤ consumptionFromPolicy baseline z

/-- Convex order for probability laws with finite first moments.  The explicit
mean equality records the mean-preserving part and keeps later uses from
depending on affine-test-function side arguments. -/
def ConvexOrder (μ ν : Measure ℝ) : Prop :=
  Integrable id μ ∧ Integrable id ν ∧
    (∫ x, x ∂μ) = ∫ x, x ∂ν ∧
    ∀ f : ℝ → ℝ, ConvexOn ℝ univ f →
      Integrable f μ → Integrable f ν →
      (∫ x, f x ∂μ) ≤ ∫ x, f x ∂ν

/-- spread is a mean-preserving spread of baseline. -/
def MeanPreservingSpread (baseline spread : Measure ℝ) : Prop :=
  ConvexOrder baseline spread

def ResourcesBoundedAbove
    (transition : ℝ → ℝ → ℝ) (zstar : ℝ) : Prop :=
  ∀ z l, zstar ≤ z → transition z l ≤ z

/-- The kernel induced by a measurable asset policy and the i.i.d. labor law. -/
def resourceKernel
    (M : HouseholdPrimitives) (φ : ℝ) (A : ℝ → ℝ)
    (htransition : Measurable (fun p : ℝ × ℝ =>
      resourceTransition M φ (A p.1) p.2)) :
    ProbabilityTheory.Kernel ℝ ℝ :=
  ProbabilityTheory.Kernel.mapOfMeasurable
    ((ProbabilityTheory.Kernel.id : ProbabilityTheory.Kernel ℝ ℝ) ×ₖ
      ProbabilityTheory.Kernel.const ℝ M.laborLaw)
    (fun p => resourceTransition M φ (A p.1) p.2) htransition

def IsInvariant
    (κ : ProbabilityTheory.Kernel ℝ ℝ) (μ : Measure ℝ) : Prop :=
  ProbabilityTheory.Kernel.Invariant κ μ

/-- Mean net assets generated by a policy and a stationary resource law. -/
def stationaryMeanAssets (φ : ℝ) (A : ℝ → ℝ) (μ : Measure ℝ) : ℝ :=
  ∫ z, A z - φ ∂μ

def MarketClears (K : CapitalDemand) (Ea : AssetSupply) (r : ℝ) : Prop :=
  K r = Ea r

def grossSavingRate (δ : ℝ) (f : ℝ → ℝ) (k : ℝ) : ℝ := δ * k / f k

def FullInsuranceReturn (β r : ℝ) : Prop := r = timePreferenceRate β

def Nonmonotone (f : ℝ → ℝ) : Prop := ¬Monotone f ∧ ¬Antitone f

def DominatesNear (rbar : ℝ) (risky certain : AssetSupply) : Prop :=
  ∃ ε > 0, ∀ r, rbar - ε < r → r < rbar → certain r < risky r

def DivergesToInfinityFromLeft (Ea : AssetSupply) (rbar : ℝ) : Prop :=
  Tendsto Ea (𝓝[<] rbar) atTop

def DivergesToNegInfinityFromRight (Ea : AssetSupply) (rbar : ℝ) : Prop :=
  Tendsto Ea (𝓝[>] rbar) atBot

def excessCapitalDemand (K : CapitalDemand) (Ea : AssetSupply) (r : ℝ) : ℝ :=
  K r - Ea r

def FixedLimitSlack (b w lmin r : ℝ) : Prop :=
  naturalDebtLimit w lmin r ≤ b

def balancedGrowthReturn (β g γ : ℝ) : ℝ :=
  (1 + timePreferenceRate β) * (1 + g) ^ γ - 1

def debtBudgetResources (w l r d a : ℝ) : ℝ :=
  w * l - r * d + (1 + r) * a

def netOfDebt (a d : ℝ) : ℝ := a - d

def taxAdjustedAssetFloor (w lmin r d : ℝ) : ℝ :=
  -(w * lmin - r * d) / r

def realNetMoneyAssets (m p : ℝ) : ℝ := (m - 1) / p

def sharpPrice (rSharp w lmin : ℝ) : ℝ := rSharp / (w * lmin)

namespace Primitives

variable (P : Primitives)

def «λ» : ℝ := timePreferenceRate P.β
def savingRate (k : ℝ) : ℝ := grossSavingRate P.δ P.production k

end Primitives

end

end Aiyagari1994
