import Lean4Tutorial.i003_replicate_aiyagari.Definitions

/-!
# Aiyagari (1994): equilibrium definitions

The main structure below is the stationary recursive competitive equilibrium
of Section 2 of `aiyagari1994_theory_summary.tex`.  The transition of the
cross-sectional distribution is represented by an operator on measures; this
keeps the definition independent of a particular construction of a Markov
kernel while retaining the invariant-distribution equation.
-/

open MeasureTheory Set
open scoped BigOperators ENNReal NNReal

namespace Aiyagari1994

noncomputable section

/-- Aggregate effective labor under a cross-sectional law. -/
def aggregateLabor (μ : Measure HouseholdState) : ℝ :=
  ∫ s, s.2 ∂μ

/-- Aggregate net assets under a cross-sectional law. -/
def aggregateAssets (μ : Measure HouseholdState) : ℝ :=
  ∫ s, s.1 ∂μ

/-- Aggregate consumption generated by a policy. -/
def aggregateConsumption
    (gC : HouseholdState → ℝ) (μ : Measure HouseholdState) : ℝ :=
  ∫ s, gC s ∂μ

/-- Household optimality and feasibility at given prices. -/
structure HouseholdEquilibriumData (r w φ : ℝ) where
  /-- The recursive value function. -/
  V : HouseholdState → ℝ
  /-- Consumption policy. -/
  gC : HouseholdState → ℝ
  /-- Next-period net-asset policy. -/
  gA : HouseholdState → ℝ
  /-- Abstract Bellman equation used by this instance. -/
  solvesBellman : (HouseholdState → ℝ) → Prop
  /-- The recorded value function solves that equation. -/
  value_solves : solvesBellman V
  /-- The Bellman solution is unique. -/
  value_unique : ∀ W, solvesBellman W → W = V
  /-- Budget feasibility. -/
  budget : ∀ s, gC s + gA s = w * s.2 + (1 + r) * s.1
  consumption_nonneg : ∀ s, 0 ≤ gC s
  borrowing_constraint : ∀ s, -φ ≤ gA s

/-- A stationary recursive competitive equilibrium. -/
structure StationaryRecursiveEquilibrium (P : Primitives) where
  /-- Net return on capital. -/
  r : ℝ
  /-- Wage per efficiency unit. -/
  w : ℝ
  /-- Per-capita capital. -/
  k : ℝ
  /-- Aggregate consumption. -/
  C : ℝ
  /-- Maximum fixed debt. -/
  b : ℝ
  /-- Effective debt limit. -/
  φ : ℝ
  /-- Household solution at equilibrium prices. -/
  household : HouseholdEquilibriumData r w φ
  /-- Stationary cross-sectional distribution over `(a,l)`. -/
  μ : Measure HouseholdState
  /-- One-period evolution of a cross-sectional distribution. -/
  evolve : Measure HouseholdState → Measure HouseholdState
  effective_limit : φ = effectiveBorrowingLimit b w P.lmin r
  invariant_distribution : evolve μ = μ
  firm_return : r = P.marginalProductCapital k - P.δ
  firm_wage : w = P.wageFromCapital k
  labor_clears : aggregateLabor μ = 1
  assets_clear : aggregateAssets μ = k
  capital_demand_clears : P.capitalDemand r = k
  consumption_aggregates : aggregateConsumption household.gC μ = C
  goods_clear : C + P.δ * k = P.production k

namespace StationaryRecursiveEquilibrium

variable {P : Primitives} (E : StationaryRecursiveEquilibrium P)

/-- Household capital supply equals firm capital demand in equilibrium. -/
theorem market_clears :
    MarketClears P.capitalDemand (fun _ => aggregateAssets E.μ) E.r := by
  unfold MarketClears
  rw [E.capital_demand_clears, E.assets_clear]

/-- The gross saving rate at this equilibrium. -/
def savingRate : ℝ := P.savingRate E.k

/-- Net aggregate saving in a no-growth stationary equilibrium. -/
def netSaving : ℝ := P.production E.k - E.C - P.δ * E.k

end StationaryRecursiveEquilibrium

/-- The full-insurance representative-agent benchmark. -/
structure FullInsuranceEquilibrium (P : Primitives) where
  r : ℝ
  k : ℝ
  C : ℝ
  return_eq_timePreference : r = P.«λ»
  firm_return : r = P.marginalProductCapital k - P.δ
  capital_demand_clears : P.capitalDemand r = k
  goods_clear : C + P.δ * k = P.production k

/-- A pure-exchange equilibrium with per-capita government debt. -/
structure GovernmentDebtEquilibrium where
  r : ℝ
  w : ℝ
  d : ℝ
  consumption : ℕ → ℝ
  assets : ℕ → ℝ
  labor : ℕ → ℝ
  budget : ∀ t,
    consumption t + assets (t + 1) =
      debtBudgetResources w (labor t) r d (assets t)
  assetMarketClears : ∃ meanAssets : ℝ, meanAssets = d

/-- A monetary equilibrium in which mean net real assets are zero. -/
structure MonetaryStationaryEquilibrium where
  r : ℝ
  p : ℝ
  meanAssets : ℝ → ℝ → ℝ
  p_pos : 0 < p
  clears : MonetaryEquilibrium meanAssets r p

end

end Aiyagari1994
