import Mathlib.Util.AssertNoSorry
import Lean4Tutorial.i003_replicate_aiyagari.PropertiesHousehold
import Lean4Tutorial.i003_replicate_aiyagari.PropertiesStationary
import Lean4Tutorial.i003_replicate_aiyagari.PropertiesEquilibrium
import Lean4Tutorial.i003_replicate_aiyagari.PropertiesExtensions

/-!
# Aiyagari (1994): no-`sorry` verification

Each source property has one numbered theorem below.  `assert_no_sorry` checks
that the theorem and all declarations used by its proof are independent of
Lean's `sorryAx`.
-/

assert_no_sorry Aiyagari1994.property01_naturalDebt_iff_noPonzi
assert_no_sorry Aiyagari1994.property02_value_and_policy_regularity
assert_no_sorry Aiyagari1994.property03_binding_region_at_low_resources
assert_no_sorry Aiyagari1994.property04_monotonicity_and_one_for_one_response
assert_no_sorry Aiyagari1994.property05_mean_preserving_spread

assert_no_sorry Aiyagari1994.property06_bounded_resource_dynamics
assert_no_sorry Aiyagari1994.property07_unique_stable_invariant_distribution
assert_no_sorry Aiyagari1994.property08_continuity_and_possible_nonmonotonicity
assert_no_sorry Aiyagari1994.property09_explosion_at_time_preference_rate
assert_no_sorry Aiyagari1994.property10_uncertainty_raises_assets_near_benchmark

assert_no_sorry Aiyagari1994.property11_factor_price_and_capital_signs
assert_no_sorry Aiyagari1994.property12_saving_rate_sign
assert_no_sorry Aiyagari1994.property13_equilibrium_need_not_be_unique
assert_no_sorry Aiyagari1994.property14_existence_under_alternative_debt_limits
assert_no_sorry Aiyagari1994.property15_general_equilibrium_disciplines_saving
assert_no_sorry Aiyagari1994.property16_more_borrowing_reduces_capital
assert_no_sorry Aiyagari1994.property17_no_effect_when_fixed_limit_slack

assert_no_sorry Aiyagari1994.property18_balanced_growth_extension
assert_no_sorry Aiyagari1994.property19_debt_neutrality_depends_on_constraint
assert_no_sorry Aiyagari1994.property20_monetary_return_upper_bound

-- Additional machine-checked lemmas used in the numbered results.
assert_no_sorry Aiyagari1994.beta_mul_one_add_timePreferenceRate
assert_no_sorry Aiyagari1994.property03_inada_exception
assert_no_sorry Aiyagari1994.consumptionShiftedDown_of_policyShiftedUp
assert_no_sorry Aiyagari1994.continuous_nonmonotone_curve_exists
assert_no_sorry Aiyagari1994.marketClearing_exists_of_sign_change
assert_no_sorry Aiyagari1994.property16_more_borrowing_reduces_saving_rate
assert_no_sorry Aiyagari1994.effectiveBorrowingLimit_eq_natural_of_slack
assert_no_sorry Aiyagari1994.debt_budget_translation
assert_no_sorry Aiyagari1994.debt_budget_iff_net_budget
assert_no_sorry Aiyagari1994.taxAdjusted_floor_iff_net_natural_floor
assert_no_sorry Aiyagari1994.fixed_floor_not_debt_neutral_witness
assert_no_sorry Aiyagari1994.monetary_constraint_slack_above_sharp_return
