import Mathlib.Util.AssertNoSorry
import Lean4Tutorial.i003_replicate_aiyagari.StochasticPaths
import Lean4Tutorial.i003_replicate_aiyagari.PropertiesHousehold
import Lean4Tutorial.i003_replicate_aiyagari.PropertiesStationary
import Lean4Tutorial.i003_replicate_aiyagari.PropertiesEquilibrium
import Lean4Tutorial.i003_replicate_aiyagari.PropertiesExtensions

/-!
# Aiyagari (1994): no-`sorry` verification

Each source property has one numbered theorem below.  `assert_no_sorry` checks
that the theorem and all declarations used by its proof are independent of
Lean's `sorryAx`.
-/

assert_no_sorry Aiyagari1994.property01_naturalDebt_iff_noPonzi
assert_no_sorry Aiyagari1994.property02_value_and_policy_regularity
assert_no_sorry Aiyagari1994.property03_binding_region_at_low_resources
assert_no_sorry Aiyagari1994.property04_monotonicity_and_one_for_one_response
assert_no_sorry Aiyagari1994.property05_mean_preserving_spread

assert_no_sorry Aiyagari1994.property06_bounded_resource_dynamics
assert_no_sorry Aiyagari1994.property07_unique_stable_invariant_distribution
assert_no_sorry Aiyagari1994.property08_continuity_and_possible_nonmonotonicity
assert_no_sorry Aiyagari1994.property09_explosion_at_time_preference_rate
assert_no_sorry Aiyagari1994.property10_uncertainty_raises_assets_near_benchmark

assert_no_sorry Aiyagari1994.property11_factor_price_and_capital_signs
assert_no_sorry Aiyagari1994.property12_saving_rate_sign
assert_no_sorry Aiyagari1994.property13_equilibrium_need_not_be_unique
assert_no_sorry Aiyagari1994.property14_existence_under_alternative_debt_limits
assert_no_sorry Aiyagari1994.property15_general_equilibrium_disciplines_saving
assert_no_sorry Aiyagari1994.property16_more_borrowing_reduces_capital
assert_no_sorry Aiyagari1994.property17_no_effect_when_fixed_limit_slack

assert_no_sorry Aiyagari1994.property18_balanced_growth_extension
assert_no_sorry Aiyagari1994.property19_debt_neutrality_depends_on_constraint
assert_no_sorry Aiyagari1994.property20_monetary_return_upper_bound

-- Additional machine-checked lemmas used in the numbered results.
assert_no_sorry Aiyagari1994.minimumIncome_shifted_budget
assert_no_sorry Aiyagari1994.discountedShiftedAssets_antitone
assert_no_sorry Aiyagari1994.tendsto_naturalDebtLimit_div_pow
assert_no_sorry Aiyagari1994.property01_naturalDebt_iff_noPonzi_ae
assert_no_sorry Aiyagari1994.natural_bound_does_not_imply_noPonzi_without_feasibility
assert_no_sorry Aiyagari1994.noPonzi_does_not_imply_natural_bound_without_feasibility
assert_no_sorry Aiyagari1994.beta_mul_one_add_timePreferenceRate
assert_no_sorry Aiyagari1994.canonicalLabor_map_eq
assert_no_sorry Aiyagari1994.measure_lowerLaborBlock
assert_no_sorry Aiyagari1994.lowerLaborBlock_pos
assert_no_sorry Aiyagari1994.abs_compactMaximum_sub_le
assert_no_sorry Aiyagari1994.continuousFamilyArgmax_isMax
assert_no_sorry Aiyagari1994.continuous_continuousFamilyArgmax
assert_no_sorry Aiyagari1994.maximizeObjective_norm_sub_le
assert_no_sorry Aiyagari1994.maximizeObjective_lipschitz
assert_no_sorry Aiyagari1994.continuous_maximizeObjective
assert_no_sorry Aiyagari1994.abs_integral_bcf_sub_le
assert_no_sorry Aiyagari1994.expectedContinuationBCF_norm_sub_le
assert_no_sorry Aiyagari1994.expectedContinuationBCF_lipschitz
assert_no_sorry Aiyagari1994.continuous_expectedContinuationBCF
assert_no_sorry Aiyagari1994.continuous_boundedContinuousFamily
assert_no_sorry Aiyagari1994.continuous_compactParameterizedExpectation_fixedValue
assert_no_sorry Aiyagari1994.continuous_compactParameterizedExpectation
assert_no_sorry Aiyagari1994.continuousBellmanOperator_norm_sub_le
assert_no_sorry Aiyagari1994.continuousBellmanOperator_contracting
assert_no_sorry Aiyagari1994.continuous_continuousBellmanOperator_reward_value
assert_no_sorry Aiyagari1994.parameterizedContractionFixedPoint_isFixedPt
assert_no_sorry Aiyagari1994.dist_parameterizedContractionFixedPoint_le
assert_no_sorry Aiyagari1994.continuous_parameterizedContractionFixedPoint
assert_no_sorry Aiyagari1994.continuous_boundedBellmanValue_reward
assert_no_sorry Aiyagari1994.continuous_compactParameterizedBellmanOperator
assert_no_sorry Aiyagari1994.continuous_compactParameterizedBellmanValue
assert_no_sorry Aiyagari1994.continuous_compactParameterizedSolvedObjective
assert_no_sorry Aiyagari1994.continuous_compactParameterizedSolvedObjective_apply
assert_no_sorry Aiyagari1994.continuous_compactParameterizedSolvedPolicy
assert_no_sorry Aiyagari1994.boundedAiyagariValue_isFixedPoint
assert_no_sorry Aiyagari1994.boundedAiyagariValue_unique
assert_no_sorry Aiyagari1994.solvedBoundedHousehold_behavior_eq_of_limit_eq
assert_no_sorry Aiyagari1994.effectiveBorrowingLimit_admissible
assert_no_sorry Aiyagari1994.boundedAiyagariPolicy_isMax
assert_no_sorry Aiyagari1994.boundedAiyagariValue_unique
assert_no_sorry Aiyagari1994.boundedAiyagariValue_concave
assert_no_sorry Aiyagari1994.boundedOptimalAsset_unique
assert_no_sorry Aiyagari1994.continuous_boundedAiyagariAssetPolicy
assert_no_sorry Aiyagari1994.hasDerivAt_of_twoSided_slope_sandwich
assert_no_sorry Aiyagari1994.hasDerivAt_of_concave_local_lowerSupport
assert_no_sorry Aiyagari1994.LocalDominatedDerivative.hasDerivAt_integral
assert_no_sorry Aiyagari1994.HasDerivAt.nonpos_of_eventually_right_max
assert_no_sorry Aiyagari1994.boundedAiyagariValue_eq_optimalAssetObjective
assert_no_sorry Aiyagari1994.boundedAiyagari_envelope_of_consumption_pos
assert_no_sorry Aiyagari1994.boundedAssetContinuation_hasDerivAt
assert_no_sorry Aiyagari1994.boundedAssetObjective_hasDerivAt_at_policy
assert_no_sorry Aiyagari1994.boundedAiyagari_euler_inequality
assert_no_sorry Aiyagari1994.monotone_boundedAiyagariAssetPolicy
assert_no_sorry Aiyagari1994.monotone_boundedAiyagariConsumption
assert_no_sorry Aiyagari1994.boundedAiyagariAssetPolicy_increment_bounds
assert_no_sorry Aiyagari1994.boundedAiyagariAssetPolicy_zero_at_minimum
assert_no_sorry Aiyagari1994.boundedAiyagari_marginal_le_minimum_of_policy_pos
assert_no_sorry Aiyagari1994.boundedAiyagari_binding_cutoff
assert_no_sorry Aiyagari1994.EventualRelativeRiskAversionBound.marginal_ratio_le_rpow
assert_no_sorry Aiyagari1994.EventualRelativeRiskAversionBound.tendsto_marginal_ratio_add_const
assert_no_sorry Aiyagari1994.rra_marginal_ratio_bounded_gap_tendsto_one
assert_no_sorry Aiyagari1994.bounded_resource_dynamics_of_policy_tendsto_atTop
assert_no_sorry Aiyagari1994.property03_inada_exception
assert_no_sorry Aiyagari1994.consumptionShiftedDown_of_policyShiftedUp
assert_no_sorry Aiyagari1994.stationaryMeanAssets_mono_same_law
assert_no_sorry Aiyagari1994.integral_mono_of_convexOrder_concave
assert_no_sorry Aiyagari1994.continuationSavingGap_mono_of_meanPreservingSpread
assert_no_sorry Aiyagari1994.oneStepObjectiveSavingGap_mono_of_meanPreservingSpread
assert_no_sorry Aiyagari1994.optimalConsumption_antitone_of_meanPreservingSpread_sameContinuation
assert_no_sorry Aiyagari1994.iidTransitionFeller_of_continuous
assert_no_sorry Aiyagari1994.monotone_solvedResourceTransition
assert_no_sorry Aiyagari1994.feller_solvedResourceTransition
assert_no_sorry Aiyagari1994.cesaro_residual_tendsto_zero_of_map_average
assert_no_sorry Aiyagari1994.exists_fixedPoint_of_compact_cesaro
assert_no_sorry Aiyagari1994.continuous_markovLawEvolution_of_feller
assert_no_sorry Aiyagari1994.markovLawEvolution_probabilityCesaroAverage
assert_no_sorry Aiyagari1994.integral_iterate_markovLawEvolution
assert_no_sorry Aiyagari1994.exists_invariantProbability_of_feller_compact
assert_no_sorry Aiyagari1994.bcfOscillation_iterate_le
assert_no_sorry Aiyagari1994.bcfOscillation_fellerMarkovOperator_le_two
assert_no_sorry Aiyagari1994.bcfOscillation_mul_iterate_le
assert_no_sorry Aiyagari1994.tendsto_bcfOscillation_iterate_of_finiteStepMixing
assert_no_sorry Aiyagari1994.kernelOscillationMixing_of_oneStepSplitting
assert_no_sorry Aiyagari1994.exists_unique_invariant_and_tendsto_of_feller_mixing
assert_no_sorry Aiyagari1994.tendsto_iterate_of_kernelIterateOscillationMixing
assert_no_sorry Aiyagari1994.exists_unique_invariant_and_tendsto_of_feller_finiteStepMixing
assert_no_sorry Aiyagari1994.continuous_integral_bcf_probabilityMeasure
assert_no_sorry Aiyagari1994.continuous_fixedPoint_of_compact_unique
assert_no_sorry Aiyagari1994.continuous_parameterizedMarkovLawEvolution_of_continuous_fellerOperator
assert_no_sorry Aiyagari1994.continuous_invariantProbability_of_jointlyContinuous_evolution
assert_no_sorry Aiyagari1994.solvedNextExcess_le_driftThreshold
assert_no_sorry Aiyagari1994.feller_absorbingSolvedKernel
assert_no_sorry Aiyagari1994.exists_invariantProbability_absorbingSolvedKernel
assert_no_sorry Aiyagari1994.solvedHousehold_invariantProbability_exists
assert_no_sorry Aiyagari1994.tendsto_iterate_zero_of_monotone_strictDecrease
assert_no_sorry Aiyagari1994.exists_uniform_iterate_lt_of_monotone_strictDecrease
assert_no_sorry Aiyagari1994.minimumLaborTransition_strictly_decreases
assert_no_sorry Aiyagari1994.minimumLaborBlock_uniformly_enters_bindingRegion
assert_no_sorry Aiyagari1994.exists_positive_lowOffset_uniformly_enters_bindingRegion
assert_no_sorry Aiyagari1994.lowOffsetBlockTransition_le_constant
assert_no_sorry Aiyagari1994.lowLaborNeighborhoodBlock_uniformly_enters_bindingRegion
assert_no_sorry Aiyagari1994.lowIncomeBlock_positive_and_uniformEntrance
assert_no_sorry Aiyagari1994.supportedLowerLaborBlock_pos
assert_no_sorry Aiyagari1994.continuous_absorbingSolvedBlockTransition
assert_no_sorry Aiyagari1994.exists_oneStepSplitting_absorbingSolvedBlockTransition
assert_no_sorry Aiyagari1994.solvedNextExcess_eq_of_limit_eq
assert_no_sorry Aiyagari1994.solvedResourceKernel_eq_of_limit_eq
assert_no_sorry Aiyagari1994.kernelIterateOscillationMixing_of_blockSplitting
assert_no_sorry Aiyagari1994.finiteIIDBlockTransition_succ_last
assert_no_sorry Aiyagari1994.measurable_finiteIIDBlockTransition
assert_no_sorry Aiyagari1994.continuous_finiteIIDBlockTransition
assert_no_sorry Aiyagari1994.integral_finiteIIDBlockTransition_eq_operator_iterate
assert_no_sorry Aiyagari1994.fellerMarkovOperator_finiteIIDBlock_eq_iterate
assert_no_sorry Aiyagari1994.finiteSupportedLowerLaborBlock_pos
assert_no_sorry Aiyagari1994.exists_oneStepSplitting_finite_absorbingSolvedBlockTransition
assert_no_sorry Aiyagari1994.absorbingSolvedKernel_finiteStepMixing
assert_no_sorry Aiyagari1994.SolvedStationaryHousehold.meanAssets_eq_of_limit_eq_unique
assert_no_sorry Aiyagari1994.finiteStateMeanAssets_continuous
assert_no_sorry Aiyagari1994.continuous_nonmonotone_finiteState_supply
assert_no_sorry Aiyagari1994.reciprocal_gap_diverges
assert_no_sorry Aiyagari1994.marketClearing_exists_of_sign_change
assert_no_sorry Aiyagari1994.property16_more_borrowing_reduces_saving_rate
assert_no_sorry Aiyagari1994.effectiveBorrowingLimit_eq_natural_of_slack
assert_no_sorry Aiyagari1994.debt_budget_translation
assert_no_sorry Aiyagari1994.debt_budget_iff_net_budget
assert_no_sorry Aiyagari1994.taxAdjusted_floor_iff_net_natural_floor
assert_no_sorry Aiyagari1994.debtAdjustedFeasible_iff_net
assert_no_sorry Aiyagari1994.debtAdjustedBellmanObjective_grossAssetOfShifted
assert_no_sorry Aiyagari1994.debtAdjustedBellmanOperator_eq_bellmanOperator
assert_no_sorry Aiyagari1994.debtAdjustedBellmanFixedPoint_of_fixedPoint
assert_no_sorry Aiyagari1994.debtAdjustedPolicy_optimal_of_optimal
assert_no_sorry Aiyagari1994.debtAdjustedResourceTransition_policy
assert_no_sorry Aiyagari1994.taxAdjustedToDebtFree_debtFreeToTaxAdjusted
assert_no_sorry Aiyagari1994.debtFreeToTaxAdjusted_taxAdjustedToDebtFree
assert_no_sorry Aiyagari1994.taxAdjustedAssetFloor_eq_debt_sub_natural
assert_no_sorry Aiyagari1994.fixed_floor_not_debt_neutral_witness
assert_no_sorry Aiyagari1994.monetary_constraint_slack_above_sharp_return
assert_no_sorry Aiyagari1994.monetaryMeanAssets_eq_natural_of_slack

/-! The following commands print Lean's complete transitive axiom dependency
set for every numbered theorem during verification.  Mathematical library
axioms such as choice or quotient soundness may appear; `sorryAx` may not. -/
#print axioms Aiyagari1994.property01_naturalDebt_iff_noPonzi
#print axioms Aiyagari1994.property02_value_and_policy_regularity
#print axioms Aiyagari1994.property03_binding_region_at_low_resources
#print axioms Aiyagari1994.property04_monotonicity_and_one_for_one_response
#print axioms Aiyagari1994.property05_mean_preserving_spread
#print axioms Aiyagari1994.property06_bounded_resource_dynamics
#print axioms Aiyagari1994.property07_unique_stable_invariant_distribution
#print axioms Aiyagari1994.property08_continuity_and_possible_nonmonotonicity
#print axioms Aiyagari1994.property09_explosion_at_time_preference_rate
#print axioms Aiyagari1994.property10_uncertainty_raises_assets_near_benchmark
#print axioms Aiyagari1994.property11_factor_price_and_capital_signs
#print axioms Aiyagari1994.property12_saving_rate_sign
#print axioms Aiyagari1994.property13_equilibrium_need_not_be_unique
#print axioms Aiyagari1994.property14_existence_under_alternative_debt_limits
#print axioms Aiyagari1994.property15_general_equilibrium_disciplines_saving
#print axioms Aiyagari1994.property16_more_borrowing_reduces_capital
#print axioms Aiyagari1994.property17_no_effect_when_fixed_limit_slack
#print axioms Aiyagari1994.property18_balanced_growth_extension
#print axioms Aiyagari1994.property19_debt_neutrality_depends_on_constraint
#print axioms Aiyagari1994.property20_monetary_return_upper_bound
#print axioms Aiyagari1994.boundedAiyagari_envelope_of_consumption_pos
#print axioms Aiyagari1994.boundedAiyagari_euler_inequality
#print axioms Aiyagari1994.exists_invariantProbability_of_feller_compact
#print axioms Aiyagari1994.exists_unique_invariant_and_tendsto_of_feller_mixing
#print axioms Aiyagari1994.exists_unique_invariant_and_tendsto_of_feller_finiteStepMixing
#print axioms Aiyagari1994.kernelOscillationMixing_of_oneStepSplitting
#print axioms Aiyagari1994.solvedHousehold_invariantProbability_exists
#print axioms Aiyagari1994.minimumLaborTransition_strictly_decreases
#print axioms Aiyagari1994.lowIncomeBlock_positive_and_uniformEntrance
#print axioms Aiyagari1994.exists_oneStepSplitting_absorbingSolvedBlockTransition
