import Aiyagari1994.Household.ParameterContinuity
import Mathlib.Util.AssertNoSorry

set_option format.width 100
set_option pp.funBinderTypes true

#check Aiyagari1994.AdmissibleNormalizedPrices
assert_no_sorry Aiyagari1994.AdmissibleNormalizedPrices
#print axioms Aiyagari1994.AdmissibleNormalizedPrices

#check Aiyagari1994.instTopologicalSpaceAdmissibleNormalizedPrices
assert_no_sorry Aiyagari1994.instTopologicalSpaceAdmissibleNormalizedPrices
#print axioms Aiyagari1994.instTopologicalSpaceAdmissibleNormalizedPrices

#check Aiyagari1994.instFirstCountableTopologyAdmissibleNormalizedPrices
assert_no_sorry Aiyagari1994.instFirstCountableTopologyAdmissibleNormalizedPrices
#print axioms Aiyagari1994.instFirstCountableTopologyAdmissibleNormalizedPrices

#check Aiyagari1994.instLocallyCompactSpaceAdmissibleNormalizedPrices
assert_no_sorry Aiyagari1994.instLocallyCompactSpaceAdmissibleNormalizedPrices
#print axioms Aiyagari1994.instLocallyCompactSpaceAdmissibleNormalizedPrices

#check Aiyagari1994.AdmissibleNormalizedPrices.grossReturn
assert_no_sorry Aiyagari1994.AdmissibleNormalizedPrices.grossReturn
#print axioms Aiyagari1994.AdmissibleNormalizedPrices.grossReturn

#check Aiyagari1994.AdmissibleNormalizedPrices.wage
assert_no_sorry Aiyagari1994.AdmissibleNormalizedPrices.wage
#print axioms Aiyagari1994.AdmissibleNormalizedPrices.wage

#check Aiyagari1994.AdmissibleNormalizedPrices.intercept
assert_no_sorry Aiyagari1994.AdmissibleNormalizedPrices.intercept
#print axioms Aiyagari1994.AdmissibleNormalizedPrices.intercept

#check Aiyagari1994.AdmissibleNormalizedPrices.toPrices
assert_no_sorry Aiyagari1994.AdmissibleNormalizedPrices.toPrices
#print axioms Aiyagari1994.AdmissibleNormalizedPrices.toPrices

#check Aiyagari1994.HouseholdPrimitives.withPrices
assert_no_sorry Aiyagari1994.HouseholdPrimitives.withPrices
#print axioms Aiyagari1994.HouseholdPrimitives.withPrices

#check Aiyagari1994.parameterized_value_continuous
assert_no_sorry Aiyagari1994.parameterized_value_continuous
#print axioms Aiyagari1994.parameterized_value_continuous

#check Aiyagari1994.parameterized_assetPolicy_continuous
assert_no_sorry Aiyagari1994.parameterized_assetPolicy_continuous
#print axioms Aiyagari1994.parameterized_assetPolicy_continuous

#check Aiyagari1994.policy_jointly_continuous
assert_no_sorry Aiyagari1994.policy_jointly_continuous
#print axioms Aiyagari1994.policy_jointly_continuous
