import Aiyagari1994.Analysis.Curvature
import Mathlib.Util.AssertNoSorry

set_option format.width 100
set_option pp.funBinderTypes true

#check Aiyagari1994.power_mul_deriv_monotoneOn
assert_no_sorry Aiyagari1994.power_mul_deriv_monotoneOn
#print axioms Aiyagari1994.power_mul_deriv_monotoneOn

#check Aiyagari1994.marginalUtility_ratio_bound
assert_no_sorry Aiyagari1994.marginalUtility_ratio_bound
#print axioms Aiyagari1994.marginalUtility_ratio_bound
