import Aiyagari1994.Stationary.LowerTransition
import Mathlib.Util.AssertNoSorry

set_option format.width 100

#check Aiyagari1994.lowerEffectiveIncome
assert_no_sorry Aiyagari1994.lowerEffectiveIncome
#print axioms Aiyagari1994.lowerEffectiveIncome

#check Aiyagari1994.lowerTransition
assert_no_sorry Aiyagari1994.lowerTransition
#print axioms Aiyagari1994.lowerTransition

#check Aiyagari1994.lowerTransition_continuous
assert_no_sorry Aiyagari1994.lowerTransition_continuous
#print axioms Aiyagari1994.lowerTransition_continuous

#check Aiyagari1994.lowerEffectiveIncome_le_lowerTransition
assert_no_sorry Aiyagari1994.lowerEffectiveIncome_le_lowerTransition
#print axioms Aiyagari1994.lowerEffectiveIncome_le_lowerTransition

#check Aiyagari1994.lower_transition_iterates_tendsto
assert_no_sorry Aiyagari1994.lower_transition_iterates_tendsto
#print axioms Aiyagari1994.lower_transition_iterates_tendsto

#check Aiyagari1994.M05B_lower_transition_iterates_tendsto
assert_no_sorry Aiyagari1994.M05B_lower_transition_iterates_tendsto
#print axioms Aiyagari1994.M05B_lower_transition_iterates_tendsto
