import Lean4Tutorial.i002_replicate_MP_v2.MP1994V2.SteadyState.ReducedAnalytic

/-!
# MP1994 v2: reconstruction from a reduced equilibrium

An admissible reduced pair satisfying the robust job-destruction and
job-creation conditions reconstructs explicit economic value functions and
the Nash wage.  The module proves equations (1)--(7) and packages them as a
`ValueEquilibrium`.
-/

open MeasureTheory

namespace MP1994V2

namespace ReducedEquilibrium

variable {P : Primitives} (R : ReducedEquilibrium P)

/-- Reconstructed affine surplus. -/
noncomputable def surplusCandidate (eps : ℝ) : ℝ :=
  (P.sigma / (P.r + P.lambda)) * (eps - R.cutoff)

/-- Reconstructed vacancy value. -/
def vacancyValueCandidate (_R : ReducedEquilibrium P) : ℝ := 0

/-- Reconstructed firm value, the firm's Nash share of surplus. -/
noncomputable def firmValueCandidate (eps : ℝ) : ℝ :=
  (1 - P.beta) * R.surplusCandidate eps

/-- Reconstructed unemployment value. -/
noncomputable def unemploymentValueCandidate : ℝ :=
  (P.b
      + P.beta * P.workerMeetingRate R.theta *
          R.surplusCandidate P.epsUpper) /
    P.r

/-- Reconstructed worker value. -/
noncomputable def workerValueCandidate (eps : ℝ) : ℝ :=
  R.unemploymentValueCandidate
    + P.beta * R.surplusCandidate eps

/-- Explicit Nash wage used by the reconstructed value equilibrium. -/
noncomputable def wageCandidate (eps : ℝ) : ℝ :=
  P.beta * P.productivity eps
    + (1 - P.beta) * P.b
    + P.beta * P.c * R.theta

/-- Candidate value objects generated by a reduced equilibrium. -/
noncomputable def toValueCandidate : ValueCandidate where
  theta := R.theta
  V := R.vacancyValueCandidate
  U := R.unemploymentValueCandidate
  J := R.firmValueCandidate
  W := R.workerValueCandidate
  wage := R.wageCandidate

@[simp]
theorem toValueCandidate_theta :
    R.toValueCandidate.theta = R.theta :=
  rfl

/-- The surplus computed from reconstructed values is exactly the intended
affine surplus. -/
theorem toValueCandidate_surplus (eps : ℝ) :
    R.toValueCandidate.surplus eps =
      R.surplusCandidate eps := by
  unfold ValueCandidate.surplus MP1994V2.surplus
    toValueCandidate firmValueCandidate workerValueCandidate
  ring

/-- Active reconstructed surplus is the positive part of distance from the
reduced cutoff, scaled by the positive surplus slope. -/
theorem toValueCandidate_activeSurplus
    (A : CoreEconomicAssumptions P)
    (eps : ℝ) :
    R.toValueCandidate.activeSurplus eps =
      (P.sigma / (P.r + P.lambda)) *
        positivePart (eps - R.cutoff) := by
  change positivePart (R.toValueCandidate.surplus eps) =
    (P.sigma / (P.r + P.lambda)) *
      positivePart (eps - R.cutoff)
  rw [R.toValueCandidate_surplus]
  unfold surplusCandidate
  by_cases hNeg : eps - R.cutoff < 0
  · have hProduct :
        (P.sigma / (P.r + P.lambda)) *
            (eps - R.cutoff) < 0 :=
      mul_neg_of_pos_of_neg A.surplus_slope_pos hNeg
    simp [positivePart, max_eq_right hProduct.le, max_eq_right hNeg.le]
  · have hNonneg : 0 ≤ eps - R.cutoff := le_of_not_gt hNeg
    have hProduct :
        0 ≤ (P.sigma / (P.r + P.lambda)) *
            (eps - R.cutoff) :=
      mul_nonneg A.surplus_slope_pos.le hNonneg
    simp [positivePart, max_eq_left hProduct, max_eq_left hNonneg]

/-- Analytic admissibility of the reconstructed active surplus. -/
theorem activeSurplus_integrable
    (A : CoreEconomicAssumptions P)
    (D : ShockAssumptions P) :
    Integrable R.toValueCandidate.activeSurplus P.shock := by
  have hBase :=
    P.positivePart_sub_integrable D R.cutoff
  have hScaled :
      Integrable
        (fun x =>
          (P.sigma / (P.r + P.lambda)) *
            positivePart (x - R.cutoff))
        P.shock :=
    hBase.const_mul _
  exact hScaled.congr
    (Filter.Eventually.of_forall fun x =>
      (R.toValueCandidate_activeSurplus A x).symm)

/-- The product-form job-creation field implies the reduced search-gain
identity without division by the vacancy meeting rate. -/
theorem search_gain_eq
    (A : CoreEconomicAssumptions P) :
    P.beta * P.workerMeetingRate R.theta *
        R.surplusCandidate P.epsUpper =
      (P.beta * P.c / (1 - P.beta)) * R.theta := by
  have hProduct := R.jobCreationProduct
  unfold Primitives.SatisfiesJobCreationProduct at hProduct
  unfold Primitives.workerMeetingRate surplusCandidate
  have hBeta : 1 - P.beta ≠ 0 := A.one_sub_beta_pos.ne'
  field_simp [hBeta]
  linear_combination P.beta * R.theta * hProduct

/-- Vacancy meeting profits exactly cover vacancy cost. -/
theorem vacancy_meeting_mul_firm_value_eq_cost
    (_A : CoreEconomicAssumptions P) :
    P.q R.theta *
        R.firmValueCandidate P.epsUpper =
      P.c := by
  have hProduct := R.jobCreationProduct
  unfold Primitives.SatisfiesJobCreationProduct at hProduct
  unfold firmValueCandidate surplusCandidate
  simpa only [mul_assoc] using hProduct

/-- The search component appearing in the explicit wage is the worker-share
multiple of vacancy cost. -/
theorem wage_search_term_eq
    (A : CoreEconomicAssumptions P) :
    P.beta * (1 - P.beta) *
        P.workerMeetingRate R.theta *
        R.surplusCandidate P.epsUpper =
      P.beta * P.c * R.theta := by
  have hVacancy :=
    R.vacancy_meeting_mul_firm_value_eq_cost A
  unfold Primitives.workerMeetingRate at hVacancy ⊢
  unfold firmValueCandidate at hVacancy
  linear_combination P.beta * R.theta * hVacancy

/-- Integral of reconstructed active surplus in expected-excess form. -/
theorem integral_activeSurplus_eq
    (A : CoreEconomicAssumptions P)
    (_D : ShockAssumptions P) :
    (∫ x, R.toValueCandidate.activeSurplus x ∂P.shock) =
      (P.sigma / (P.r + P.lambda)) *
        P.expectedExcess R.cutoff := by
  rw [Primitives.expectedExcess, ← integral_const_mul]
  exact integral_congr_ae
    (Filter.Eventually.of_forall fun x =>
      R.toValueCandidate_activeSurplus A x)

/-- The reconstructed affine surplus satisfies paper equation (8). -/
theorem surplus_bellman
    (A : CoreEconomicAssumptions P)
    (D : ShockAssumptions P)
    (eps : ℝ) :
    (P.r + P.lambda) * R.surplusCandidate eps =
      P.p + P.sigma * eps - P.b
        + P.lambda *
            (∫ x, R.toValueCandidate.activeSurplus x ∂P.shock)
        - P.beta * P.workerMeetingRate R.theta *
            R.surplusCandidate P.epsUpper := by
  have hJD := R.equation10_measure
  have hSearch := R.search_gain_eq A
  have hIntegral := R.integral_activeSurplus_eq A D
  rw [hIntegral, hSearch]
  unfold surplusCandidate
  field_simp [A.r_add_lambda_ne, A.one_sub_beta_pos.ne'] at hJD ⊢
  ring_nf at hJD ⊢
  linarith

/-- Reconstructed continuation is expected active surplus minus current
surplus. -/
theorem continuation_eq
    (A : CoreEconomicAssumptions P)
    (D : ShockAssumptions P)
    (eps : ℝ) :
    R.toValueCandidate.continuation P eps =
      (∫ x, R.toValueCandidate.activeSurplus x ∂P.shock)
        - R.surplusCandidate eps := by
  letI : IsProbabilityMeasure P.shock := D.isProbability
  unfold ValueCandidate.continuation
  rw [continuationTerm_eq_integral_activeSurplus_sub
    (R.activeSurplus_integrable A D)]
  exact congrArg
    (fun z =>
      (∫ x, R.toValueCandidate.activeSurplus x ∂P.shock) - z)
    (R.toValueCandidate_surplus eps)

/-- Reconstructed paper equation (1). -/
theorem vacancy_bellman
    (A : CoreEconomicAssumptions P) :
    P.r * R.vacancyValueCandidate =
      -P.c
        + P.q R.theta *
            (R.firmValueCandidate P.epsUpper
              - R.vacancyValueCandidate) := by
  simp only [vacancyValueCandidate, mul_zero, sub_zero]
  rw [R.vacancy_meeting_mul_firm_value_eq_cost A]
  ring

/-- Reconstructed paper equation (2). -/
theorem free_entry :
    P.r * R.vacancyValueCandidate = 0 := by
  simp [vacancyValueCandidate]

/-- Reconstructed paper equation (4). -/
theorem nash_sharing (eps : ℝ) :
    R.workerValueCandidate eps
        - R.unemploymentValueCandidate =
      P.beta * R.surplusCandidate eps := by
  unfold workerValueCandidate
  ring

/-- Reconstructed paper equation (7). -/
theorem unemployed_bellman
    (A : CoreEconomicAssumptions P) :
    P.r * R.unemploymentValueCandidate =
      P.b
        + P.workerMeetingRate R.theta *
            (R.workerValueCandidate P.epsUpper
              - R.unemploymentValueCandidate) := by
  have hr : P.r ≠ 0 := A.r_pos.ne'
  rw [R.nash_sharing P.epsUpper]
  unfold unemploymentValueCandidate
  field_simp [hr]

/-- Reconstructed paper equation (6), using the explicit Nash wage. -/
theorem worker_bellman
    (A : CoreEconomicAssumptions P)
    (D : ShockAssumptions P)
    (eps : ℝ) :
    P.r * R.workerValueCandidate eps =
      R.wageCandidate eps
        + P.lambda * P.beta *
            R.toValueCandidate.continuation P eps := by
  have hSurplus := R.surplus_bellman A D eps
  have hUnemployed := R.unemployed_bellman A
  rw [R.nash_sharing P.epsUpper] at hUnemployed
  have hContinuation := R.continuation_eq A D eps
  have hWageSearch := R.wage_search_term_eq A
  unfold workerValueCandidate wageCandidate
  unfold Primitives.productivity
  rw [hContinuation]
  linear_combination
    hUnemployed + P.beta * hSurplus + hWageSearch

/-- Reconstructed paper equation (5), using the explicit Nash wage. -/
theorem filled_job_bellman
    (A : CoreEconomicAssumptions P)
    (D : ShockAssumptions P)
    (eps : ℝ) :
    P.r * R.firmValueCandidate eps =
      P.productivity eps
        - R.wageCandidate eps
        + P.lambda * (1 - P.beta) *
            R.toValueCandidate.continuation P eps := by
  have hSurplus := R.surplus_bellman A D eps
  have hContinuation := R.continuation_eq A D eps
  have hWageSearch := R.wage_search_term_eq A
  unfold firmValueCandidate wageCandidate
  unfold Primitives.productivity
  rw [hContinuation]
  linear_combination
    (1 - P.beta) * hSurplus - hWageSearch

/-- Construct a primitive value equilibrium from a reduced equilibrium. -/
noncomputable def toValueEquilibrium
    (A : CoreEconomicAssumptions P)
    (D : ShockAssumptions P) :
    ValueEquilibrium P where
  toValueCandidate := R.toValueCandidate
  theta_pos := R.theta_pos
  active_surplus_integrable := R.activeSurplus_integrable A D
  vacancy_bellman := R.vacancy_bellman A
  free_entry := R.free_entry
  nash_sharing := by
    intro eps
    change
      R.workerValueCandidate eps - R.unemploymentValueCandidate =
        P.beta * R.toValueCandidate.surplus eps
    rw [R.nash_sharing eps, R.toValueCandidate_surplus eps]
  filled_job_bellman := R.filled_job_bellman A D
  worker_bellman := R.worker_bellman A D
  unemployed_bellman := R.unemployed_bellman A

@[simp]
theorem toValueEquilibrium_theta
    (A : CoreEconomicAssumptions P)
    (D : ShockAssumptions P) :
    (R.toValueEquilibrium A D).theta = R.theta :=
  rfl

/-- The reconstructed value-equilibrium surplus is the candidate affine
surplus. -/
theorem toValueEquilibrium_surplus
    (A : CoreEconomicAssumptions P)
    (D : ShockAssumptions P)
    (eps : ℝ) :
    (R.toValueEquilibrium A D).toValueCandidate.surplus eps =
      R.surplusCandidate eps :=
  R.toValueCandidate_surplus eps

/-- Reconstruction preserves the reduced cutoff exactly. -/
theorem toValueEquilibrium_reservationCutoff
    (A : CoreEconomicAssumptions P)
    (D : ShockAssumptions P) :
    (R.toValueEquilibrium A D).reservationCutoff =
      R.cutoff := by
  unfold ValueEquilibrium.reservationCutoff
  rw [R.toValueEquilibrium_surplus A D P.epsUpper]
  unfold surplusCandidate
  field_simp [A.sigma_ne, A.r_add_lambda_ne]
  ring

end ReducedEquilibrium

end MP1994V2
