import Lean4Tutorial.i002_replicate_MP_v2.MP1994V2.Equilibrium.Value

/-!
# MP1994 v2: the surplus Bellman equation

This module derives paper equation (8) from the primitive value system
(3)--(7).  It uses the actual surplus generated by `J`, `W`, and `U`; no
cutoff, affine-surplus formula, or reduced equilibrium is introduced.
-/

open MeasureTheory

namespace MP1994V2

/-- Under a probability law, the shared continuation term is expected active
surplus minus current surplus:

`∫ [max {S(x), 0} - S(ε)] dF(x)
  = ∫ max {S(x), 0} dF(x) - S(ε)`.
-/
theorem continuationTerm_eq_integral_activeSurplus_sub
    {P : Primitives}
    [IsProbabilityMeasure P.shock]
    {J W : ℝ → ℝ} {U eps : ℝ}
    (hInt : Integrable (fun x => activeSurplus J W U x) P.shock) :
    continuationTerm P J W U eps =
      (∫ x, activeSurplus J W U x ∂P.shock) -
        surplus J W U eps := by
  have hConst :
      Integrable (fun _ : ℝ => surplus J W U eps) P.shock :=
    integrable_const _
  unfold continuationTerm
  rw [integral_sub hInt hConst]
  simp

namespace ValueEquilibrium

variable {P : Primitives}

/-- Equations (3) and (4) imply the firm's complementary Nash share:
`J(ε) = (1 - β) S(ε)`.

This is an algebraic identity and requires no sign restriction on `β`.
-/
theorem firm_share (E : ValueEquilibrium P) (eps : ℝ) :
    E.J eps =
      (1 - P.beta) * E.toValueCandidate.surplus eps := by
  change E.J eps =
    (1 - P.beta) * (E.J eps + E.W eps - E.U)
  have hShare := E.nash_sharing eps
  change E.W eps - E.U =
    P.beta * (E.J eps + E.W eps - E.U) at hShare
  linear_combination -hShare

/-- Adding equations (5) and (6), cancelling the wage, and subtracting
equation (7) gives the surplus flow equation before probability normalization.

Nash sharing is not used here.
-/
theorem surplus_flow_equation (E : ValueEquilibrium P) (eps : ℝ) :
    P.r * E.toValueCandidate.surplus eps =
      P.productivity eps - P.b
        + P.lambda * E.toValueCandidate.continuation P eps
        - P.workerMeetingRate E.theta *
            (E.W P.epsUpper - E.U) := by
  have hFirm := E.filled_job_bellman eps
  have hWorker := E.worker_bellman eps
  have hUnemployed := E.unemployed_bellman
  change
    P.r * (E.J eps + E.W eps - E.U) =
      P.productivity eps - P.b
        + P.lambda * continuationTerm P E.J E.W E.U eps
        - P.workerMeetingRate E.theta *
            (E.W P.epsUpper - E.U)
  calc
    P.r * (E.J eps + E.W eps - E.U) =
        (P.r * E.J eps + P.r * E.W eps) - P.r * E.U := by
          ring
    _ = P.productivity eps - P.b
        + P.lambda * continuationTerm P E.J E.W E.U eps
        - P.workerMeetingRate E.theta *
            (E.W P.epsUpper - E.U) := by
          rw [hFirm, hWorker, hUnemployed]
          ring

/-- Paper equation (8) under its weakest analytic requirement: the shock law
is a probability measure and active surplus is integrable.
-/
theorem surplus_bellman_of_probability
    [IsProbabilityMeasure P.shock]
    (E : ValueEquilibrium P) (eps : ℝ) :
    (P.r + P.lambda) * E.toValueCandidate.surplus eps =
      P.p + P.sigma * eps - P.b
        + P.lambda *
            (∫ x, E.toValueCandidate.activeSurplus x ∂P.shock)
        - P.beta * P.workerMeetingRate E.theta *
            E.toValueCandidate.surplus P.epsUpper := by
  have hFlow := E.surplus_flow_equation eps
  have hContinuation :=
    continuationTerm_eq_integral_activeSurplus_sub
      (eps := eps)
      E.active_surplus_integrable
  have hSharing := E.nash_sharing P.epsUpper
  change
    P.r * surplus E.J E.W E.U eps =
      P.productivity eps - P.b
        + P.lambda * continuationTerm P E.J E.W E.U eps
        - P.workerMeetingRate E.theta *
            (E.W P.epsUpper - E.U) at hFlow
  change
    E.W P.epsUpper - E.U =
      P.beta * surplus E.J E.W E.U P.epsUpper at hSharing
  change
    (P.r + P.lambda) * surplus E.J E.W E.U eps =
      P.p + P.sigma * eps - P.b
        + P.lambda *
            (∫ x, activeSurplus E.J E.W E.U x ∂P.shock)
        - P.beta * P.workerMeetingRate E.theta *
            surplus E.J E.W E.U P.epsUpper
  rw [hContinuation, hSharing] at hFlow
  unfold Primitives.productivity at hFlow
  linear_combination hFlow

/-- Paper-level equation (8) interface.  The distributional bundle is kept
outside `ValueEquilibrium`; only its probability field is installed locally.
-/
theorem surplus_bellman
    (D : ShockAssumptions P) (E : ValueEquilibrium P) (eps : ℝ) :
    (P.r + P.lambda) * E.toValueCandidate.surplus eps =
      P.p + P.sigma * eps - P.b
        + P.lambda *
            (∫ x, E.toValueCandidate.activeSurplus x ∂P.shock)
        - P.beta * P.workerMeetingRate E.theta *
            E.toValueCandidate.surplus P.epsUpper := by
  letI : IsProbabilityMeasure P.shock := D.isProbability
  exact E.surplus_bellman_of_probability eps

end ValueEquilibrium

end MP1994V2
